import sqlite3, unicodedata, re

conn = sqlite3.connect('/home/user/mundial2026/data/mundial2026.db')
conn.row_factory = sqlite3.Row

def norm(s):
    s = unicodedata.normalize('NFD', s.lower())
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    return re.sub(r'\s+', ' ', s).strip()

# ─── CONVOCATORIAS OFICIALES (solo los que serán titulares / están convocados) ───
OFFICIAL = {
'Mexico': ['Alex Padilla','Antonio Rodriguez','Carlos Acevedo','Carlos Moreno','Guillermo Ochoa','Raul Rangel',
    'Bryan Gonzalez','Cesar Montes','Edson Alvarez','Eduardo Aguila','Everardo Lopez','Israel Reyes',
    'Jesus Angulo','Jesus Gallardo','Jesus Gomez','Johan Vasquez','Jorge Sanchez','Julian Araujo',
    'Luis Rey','Mateo Chavez','Ramon Juarez','Richard Ledezma','Victor Guzman',
    'Alexei Dominguez','Alexis Gutierrez','Alvaro Fidalgo','Brian Gutierrez','Carlos Rodriguez',
    'Denzell Garcia','Diego Lainez','Efrain Alvarez','Elias Montiel','Erick Sanchez','Erik Lira',
    'Gilberto Mora','Isaias Violante','Jeremy Marquez','Jordan Carrillo','Jorge Ruvalcaba',
    'Kevin Castaneda','Luis Chavez','Luis Romo','Marcel Ruiz','Obed Vargas','Orbelin Pineda',
    'Alexis Vega','Armando Gonzalez','Cesar Huerta','German Berterame','Guillermo Martinez',
    'Julian Quinoones','Raul Jimenez','Roberto Alvarado','Santiago Gimenez'],
'South Africa': ['Ronwen Williams','Ricardo Goss','Sipho Chaine',
    'Khuliso Mudau','Olwethu Makhanya','Bradley Cross','Thabang Matuludi','Nkosinathi Sibisi',
    'Aubrey Modiba','Khulumani Ndamane','Ime Okon','Samukele Kabini','Mbekezeli Mbokazi',
    'Teboho Mokoena','Jayden Adams','Thalente Mbatha','Sphephelo Sithole',
    'Oswin Appollis','Tshepang Moremi','Evidence Makgopa','Lyle Foster','Iqraam Rayners',
    'Relebohile Mokofoeng','Themba Zwane','Kamogelo Sebelebele','Thapelo Maseko'],
'South Korea': ['Jo Hyun-Woo','Kim Seung-Gyu','Song Bum-Keun',
    'Kim Min-Jae','Jo Yu-Min','Lee Han-Beom','Kim Tae-Hyun','Park Jin-Seop','Lee Ki-Hyeok',
    'Lee Tae-Seok','Seol Young-Woo','Jens Castrop','Kim Moon-Hwan',
    'Yang Hyun-Jun','Paik Seung-Ho','Hwang In-Beom','Kim Jin-Kyu','Bae Jun-Ho','Um Ji-Sung',
    'Hwang Hee-Chan','Lee Dong-Gyeong','Lee Jae-Sung','Lee Kang-In',
    'Oh Hyun-Kyu','Son Heung-Min','Cho Kyu-Sung'],
'Czechia': ['Lukas Hornicek','Matej Kovar','Jindrich Stanek',
    'Vladimir Coufal','David Doudera','Tomas Holes','Robin Hranac','Stepan Chaloupek',
    'David Jurasek','Ladislav Krejci','Jaroslav Zeleny','David Zima',
    'Pavel Bucha','Lukas Cerv','Vladimir Darida','Tomas Ladra','Lukas Provod','Michal Sadilek',
    'Hugo Sochurek','Alexandr Sojka','Tomas Soucek','Pavel Sulc','Denis Visinsky',
    'Adam Hlozek','Tomas Chory','Mojmir Chytil','Christophe Kabongo','Jan Kuchta','Patrik Schick'],
'Canada': ['Maxime Crepeau','Owen Goodman','Dayne St. Clair',
    'Moise Bombito','Derek Cornelius','Alphonso Davies','Luc de Fougerolles','Alistair Johnston',
    'Alfie Jones','Richie Laryea','Niko Sigur','Joel Waterman',
    'Ali Ahmed','Tajon Buchanan','Mathieu Choiniere','Stephen Eustachio','Marcelo Flores',
    'Ismael Kone','Liam Millar','Jonathan Osorio','Nathan Saliba','Jacob Shaffelburg',
    'Jonathan David','Promise David','Cyle Larin','Tani Oluwaseyi'],
'Bosnia and Herzegovina': ['Nikola Vasilj','Martin Zlomislic','Osman Hadzikic',
    'Sead Kolasinac','Amar Dedic','Nihad Mujakic','Nikola Katic','Tarik Muharemovic',
    'Stjepan Radeljic','Dennis Hadzikadunic','Nidal Celik',
    'Amir Hadziahmetovic','Ivan Sunjic','Ivan Basic','Dzenis Burnic','Ermin Mahmic',
    'Benjamin Tahirovic','Amar Memic','Armin Gigovic','Kerim Alajbegovic','Esmir Bajraktarevic',
    'Ermedin Demirovic','Jovo Lukic','Samed Bazdar','Haris Tabakovic','Edin Dzeko'],
'Qatar': ['Shehab Elleithy','Salah Zakaria','Meshaal Barsham','Mahmoud Abunada',
    'Boualem Khoukhi','Pedro Miguel','Sultan Al Brake','Tarek Salman','Al-Hashmi Al-Hussain',
    'Ayoub Al-Alawi','Bassam Al-Rawi','Rayyan Al-Ali','Issa Laye','Lucas Mendes',
    'Mohammed Waad','Niall Mason',
    'Ahmed Fathi','Jassim Gaber','Assim Madibo','Abdulaziz Hatem','Karim Boudiaf',
    'Mohammed Mannai','Homam Al-Amin',
    'Almoez Ali','Akram Afif','Tahsin Mohammed','Edmilson Junior','Ahmed Al-Ganehi',
    'Ahmed Alaa','Sebastian Soria','Hassan Al-Haydos','Mubarak Shannan','Mohammed Muntari',
    'Yusuf Abdurisag'],
'Switzerland': ['Gregor Kobel','Yvon Mvogo','Marvin Keller',
    'Manuel Akanji','Nico Elvedi','Ricardo Rodriguez','Silvan Widmer','Miro Muheim',
    'Aurele Amenda','Eray Comert','Luca Jaquez',
    'Granit Xhaka','Johan Manzambi','Remo Freuler','Denis Zakaria','Ardon Jashari',
    'Djibril Sow','Christian Fassnacht','Michel Aebischer','Fabian Rieder','Ruben Vargas',
    'Breel Embolo','Noah Okafor','Dan Ndoye','Zeki Amdouni','Cedric Itten'],
'Brazil': ['Alisson','Ederson','Weverton',
    'Alex Sandro','Bremer','Danilo','Douglas Santos','Gabriel Magalhaes','Leo Pereira',
    'Marquinhos','Roger Ibanez','Wesley',
    'Bruno Guimaraes','Casemiro','Danilo Santos','Fabinho','Lucas Paqueta',
    'Endrick','Gabriel Martinelli','Igor Thiago','Luiz Henrique','Matheus Cunha',
    'Neymar','Raphinha','Rayan','Vinicius Junior'],
'Morocco': ['Yassine Bounou','Munir Kajoui','Ahmed Reda Tagnaouti',
    'Achraf Hakimi','Noussair Mazraoui','Anass Salah-Eddine','Youssef Belammari',
    'Issa Diop','Chadi Riad','Zakaria El Ouahdi','Redouane Halhal','Nayef Aguerd',
    'Neil El Aynaoui','Azzedine Ounahi','Ismael Saibari','Bilal El Khannouss',
    'Samir El Mourabet','Sofyan Amrabat','Ayyoub Bouaddi',
    'Brahim Diaz','Ayoub El Kaabi','Abde Ezzalzouli','Soufiane Rahimi',
    'Gessime Yassine','Ayoube Amaimouni','Chemsdine Talbi'],
'Haiti': ['Johny Placide','Alexandre Pierre','Josue Duverger',
    'Carlens Arcus','Wilguens Paugain','Duke Lacroix','Martin Experience','Jean-Kevin Duverne',
    'Ricardo Ade','Hannes Delcroix','Keeto Thermoncy',
    'Carl Fred Sainte','Leverton Pierre','Danley Jean Jacques','Jean-Ricner Bellegarde',
    'Woodensky Pierre','Dominique Simon',
    'Don Deedson Louicius','Josue Casimir','Derrick Etienne','Ruben Providence',
    'Duckens Nazon','Frantzdy Pierrot','Wilson Isidor','Yassin Fortune','Lenny Joseph'],
'Scotland': ['Craig Gordon','Angus Gunn','Liam Kelly',
    'Grant Hanley','Jack Hendry','Aaron Hickey','Dom Hyam','Scott McKenna','Nathan Patterson',
    'Anthony Ralston','Andy Robertson','John Souttar','Kieran Tierney',
    'Ryan Christie','Finlay Curtis','Lewis Ferguson','Ben Doak','Billy Gilmour',
    'John McGinn','Kenny McLean','Scott McTominay',
    'Che Adams','Lyndon Dykes','George Hirst','Lawrence Shankland','Ross Stewart'],
'USA': ['Matt Freese','Matt Turner','Chris Brady',
    'Max Arfsten','Sergino Dest','Alex Freeman','Mark McKenzie','Tim Ream','Chris Richards',
    'Antonee Robinson','Miles Robinson','Joe Scally','Auston Trusty',
    'Tyler Adams','Sebastian Berhalter','Weston McKennie','Cristian Roldan','Brenden Aaronson',
    'Christian Pulisic','Gio Reyna','Malik Tillman','Tim Weah','Alejandro Zendejas',
    'Folarin Balogun','Ricardo Pepi','Haji Wright'],
'Paraguay': ['Roberto Fernandez','Orlando Gill','Gaston Olveira','Carlos Coronel',
    'Gustavo Gomez','Junior Alonso','Fabian Balbuena','Omar Alderete','Blas Riveros',
    'Alan Benitez','Agustin Sandez','Mateo Gamarra','Saul Salcedo',
    'Miguel Almiron','Mathias Villasanti','Kaku','Andres Cubas','Ramon Sosa','Diego Gomez',
    'Damian Bobadilla','Braian Ojeda','Matias Galarza',
    'Oscar Romero','Angel Romero','Antonio Sanabria','Julio Enciso','Adam Bareiro'],
'Turkey': ['Altay Bayindir','Ersin Destanoglu','Mert Gunok','Ugurcan Cakir',
    'Abdulkerim Bardakci','Ahmetcan Kaplan','Caglar Soyuncu','Eren Elmali','Ferdi Kadioglu',
    'Merih Demiral','Mert Muldur','Ozan Kabak','Zeki Celik',
    'Atakan Karazor','Hakan Calhanoglu','Ismail Yuksek','Kaan Ayhan','Orkun Kokcu',
    'Salih Ozcan','Arda Guler','Baris Alper Yilmaz','Can Uzun',
    'Deniz Gul','Irfan Can Kahveci','Kenan Yildiz','Karem Akturkoglu','Yunus Akgun'],
'Germany': ['Oliver Baumann','Manuel Neuer','Alexander Nubel',
    'Waldemar Anton','Nathaniel Brown','David Raum','Antonio Rudiger','Nico Schlotterbeck',
    'Jonathan Tah','Malick Thiaw',
    'Pascal Gross','Joshua Kimmich','Aleksandar Pavlovic','Felix Nmecha','Angelo Stiller',
    'Nadiem Amiri','Leon Goretzka','Jamie Leweling',
    'Maximilian Beier','Kai Havertz','Lennart Karl','Jamal Musiala','Leroy Sane',
    'Deniz Undav','Florian Wirtz','Nick Woltemade'],
'Curacao': ['Eloy Room','Tyrick Bodak','Trevor Doornbusch',
    'Riechedly Bazoer','Joshua Brenet','Roshon van Eijma','Sherel Floranus','Deveron Fonville',
    'Jurien Gaari','Armando Obispo','Shurandy Sambo',
    'Juninho Bacuna','Leandro Bacuna','Livano Comenencia','Kevin Felida',
    'Arjany Martha','Tyrese Noslin','Godfried Roemeratoe',
    'Jeremy Antonisse','Tahith Chong','Kenji Gorre','Sontje Hansen','Gervane Kastaneer',
    'Brandley Kuwas','Jurgen Locadia','Jearl Margaritha'],
'Ivory Coast': ['Yahia Fofana','Mohamed Kone','Alban Lafont',
    'Emmanuel Agbadou','Clement Akpa','Ousmane Diomande','Guela Doue','Ghislain Konan',
    'Odilon Kossounou','Evan Ndicka','Wilfried Singo',
    'Seko Fofana','Parfait Guiagon','Franck Kessie','Christ Inao Oulai',
    'Ibrahim Sangare','Jean Michael Seri',
    'Simon Adingra','Ange-Yoan Bonny','Amad Diallo','Oumar Diakite','Yan Diomande',
    'Evann Guessand','Nicolas Pepe','Bazoumana Toure','Elye Wahi'],
'Netherlands': ['Mark Flekken','Robin Roefs','Bart Verbruggen',
    'Nathan Ake','Denzel Dumfries','Jorrel Hato','Jurrien Timber','Jan Paul van Hecke',
    'Micky van de Ven','Virgil van Dijk',
    'Frenkie de Jong','Marten de Roon','Ryan Gravenberch','Teun Koopmeiners',
    'Tijjani Reijnders','Guus Til','Quinten Timber','Mats Wieffer',
    'Brian Brobbey','Memphis Depay','Cody Gakpo','Justin Kluivert','Noa Lang',
    'Donyell Malen','Crysencio Summerville','Wout Weghorst'],
'Japan': ['Zion Suzuki','Keisuke Osako','Tomoki Hayakawa',
    'Yuto Nagatomo','Shogo Taniguchi','Ko Itakura','Tsuyoshi Watanabe','Takehiro Tomiyasu',
    'Hiroki Ito','Ayumu Seko','Yukinari Sugawara',
    'Junnosuke Suzuki','Wataru Endo','Junya Ito','Daichi Kamada','Ritsu Doan',
    'Ao Tanaka','Keito Nakamura','Kaishu Sano','Takefusa Kubo','Yuito Suzuki',
    'Koki Ogawa','Daizen Maeda','Ayase Ueda','Kento Shiogai','Keisuke Goto'],
'Sweden': ['Viktor Johansson','Kristoffer Nordfeldt','Jacob Widell Zetterstrom',
    'Hjalmar Ekdal','Gabriel Gudmundsson','Isak Hien','Emil Holm','Gustaf Lagerbielke',
    'Victor Lindelof','Erik Smith','Carl Starfelt','Elliot Stroud','Daniel Svensson',
    'Taha Ali','Yasin Ayari','Lucas Bergvall','Jesper Karlstrom','Ken Sema',
    'Mattias Svanberg','Besfort Zeneli',
    'Alexander Bernhardsson','Anthony Elanga','Viktor Gyokeres','Alexander Isak',
    'Gustaf Nilsson','Benjamin Nygren'],
'Tunisia': ['Aymen Dahmen','Sabri Ben Hessen','Abdelmouhib Chamakh',
    'Montassar Talbi','Dylan Bronn','Omar Rekik','Yan Valery','Ali Abdi','Moutaz Neffati',
    'Raed Chikhaoui','Adam Arous','Mohamed Amine Ben Hamida',
    'Ellyes Skhiri','Hannibal Mejbri','Anis Ben Slimane','Hadj Mahmoud',
    'Rani Khedira','Mortadha Ben Ouanes',
    'Elias Achouri','Ismael Gharbi','Elias Saad','Sebastian Tounekti','Firas Chaouat',
    'Khalil Ayari','Hazem Mastouri','Rayan Elloumi'],
'Belgium': ['Thibaut Courtois','Senne Lammens','Mike Penders',
    'Timothy Castagne','Zeno Debast','Maxim De Cuyper','Koni De Winter','Brandon Mechele',
    'Thomas Meunier','Nathan Ngoy','Joaquin Seys','Arthur Theate',
    'Kevin De Bruyne','Amadou Onana','Nicolas Raskin','Youri Tielemans',
    'Hans Vanaken','Axel Witsel',
    'Charles De Ketelaere','Jeremy Doku','Matias Fernandez-Pardo','Romelu Lukaku',
    'Dodi Lukebakio','Diego Moreira','Alexis Saelemaekers','Leandro Trossard'],
'Egypt': ['Mohamed El Shenawy','Mostafa Shobeir','El Mahdi Soliman','Mohamed Alaa',
    'Mohamed Hany','Tarek Alaa','Hamdi Fathi','Rami Rabia','Yasser Ibrahim',
    'Hossam Abdelmaguid','Mohamed Abdelmonemn','Ahmed Fatouh','Karim Hafez',
    'Marwan Ateya','Mohanad Lasheen','Nabil Emad','Mahmoud Saber','Ahmed Zizo',
    'Emam Ashour','Mostafa Ziko','Mahmoud Trezeguet','Ibrahim Adel','Haissem Hassan',
    'Omar Marmoush','Mohamed Salah','Aqtay Abdallah','Hamza Abdelkarim'],
'Iran': ['Alireza Beiranvand','Hossein Hosseini','Payam Niazmand','Mohammed Khalifeh',
    'Danial Eiri','Ehsan Hajsafi','Saleh Hardani','Hossein Kanaani','Shoka Khalilzadeh',
    'Milad Mohammadi','Ali Nemati','Omid Noorafkan','Ramin Rezaeian',
    'Rouzbeh Cheshmi','Saeid Ezatolahi','Mehdi Ghaedi','Saman Ghoddos','Mohammad Ghorbani',
    'Alireza Jahanbakhsh','Mohammad Mohebi','Mehdi Torabi','Aria Yousefi',
    'Ali Alipour','Dennis Dargahi','Hadi Habibinejad','Mehdi Taremi'],
'New Zealand': ['Max Crocombe','Alex Paulsen','Michael Woud',
    'Tim Payne','Francis De Vries','Tyler Bindon','Michael Boxall','Liberato Cacace',
    'Nando Pijnaker','Finn Surman','Callan Elliot','Tommy Smith',
    'Joe Bell','Matt Garbett','Marko Stamenic','Sarpreet Singh','Alex Rufer','Ryan Thomas',
    'Chris Wood','Eli Just','Kosta Barbarouses','Ben Waine','Ben Old',
    'Callum McCowatt','Jesse Randall','Lachlan Bayliss'],
'Spain': ['Unai Simon','David Raya','Joan Garcia',
    'Marc Cucurella','Pau Cubarsi','Aymeric Laporte','Alex Grimaldo','Pedro Porro',
    'Eric Garcia','Marcos Llorente','Marc Pubill',
    'Gavi','Rodri','Pedri','Martin Zubimendi','Fabian Ruiz','Alex Baena','Mikel Merino',
    'Lamine Yamal','Nico Williams','Dani Olmo','Ferran Torres','Mikel Oyarzabal',
    'Yeremy Pino','Borja Iglesias','Victor Munoz'],
'Cape Verde': ['Vozinha','Marcio Rosa','CJ dos Santos',
    'Steven Moreira','Wagner Pina','Joao Paulo','Sidny Lopes Cabral','Logan Costa',
    'Pico','Kelvin Pires','Stopira','Diney',
    'Jamiro Monteiro','Telmo Arcanjo','Yannick Semedo','Laros Duarte','Deroy Duarte','Kevin Pina',
    'Ryan Mendes','Willy Semedo','Garry Rodrigues','Jovane Cabral','Nuno da Costa',
    'Dailon Livramento','Gilson Benchimol','Helio Varela'],
'France': ['Mike Maignan','Robin Risser','Brice Samba',
    'Lucas Digne','Malo Gusto','Lucas Hernandez','Theo Hernandez','Ibrahima Konate',
    'Jules Kounde','Maxence Lacroix','William Saliba','Dayot Upamecano',
    'N Golo Kante','Manu Kone','Adrien Rabiot','Aurelien Tchouameni','Warren Zaire-Emery',
    'Maghnes Akliouche','Bradley Barcola','Rayan Cherki','Desire Doue','Jean-Philippe Mateta',
    'Kylian Mbappe','Michael Olise','Marcus Thuram','Ousmane Dembele'],
'Senegal': ['Edouard Mendy','Mory Diaw','Yehvann Diouf',
    'Krepin Diatta','Antoine Mendy','Kalidou Koulibaly','El Hadji Malick Diouf',
    'Mamadou Sarr','Moussa Niakhate','Moustapha Mbow','Abdoulaye Seck',
    'Ismail Jakobs','Ilay Camara',
    'Idrissa Gana Gueye','Pape Gueye','Lamine Camara','Habib Diarra','Pathe Ciss',
    'Pape Matar Sarr','Bara Sapoko Ndiaye',
    'Sadio Mane','Ismaila Sarr','Iliman Ndiaye','Assane Diao','Ibrahim Mbaye',
    'Nicolas Jackson','Bamba Dieng','Cherif Ndiaye'],
'Norway': ['Orjan Nyland','Egil Selvik','Sander Tangvik',
    'Julian Ryerson','Kristoffer Ajer','Leo Ostigard','David Moller Wolfe','Marcus Pedersen',
    'Torbjorn Heggem','Fredrik Andre Bjorkan','Henrik Falchener','Sondre Langas',
    'Martin Odegaard','Sander Berge','Patrick Berg','Kristian Thorstvedt','Morten Thorsby',
    'Thelo Aasgaard','Andreas Schjelderup','Jens Petter Hauge','Fredrik Aursnes',
    'Oscar Bobb','Antonio Nusa',
    'Erling Haaland','Alexander Sorloth','Jorgen Strand Larsen'],
'Argentina': ['Emiliano Martinez','Geronimo Rulli','Juan Musso',
    'Gonzalo Montiel','Nahuel Molina','Lisandro Martinez','Nicolas Otamendi','Leonardo Balerdi',
    'Cristian Romero','Facundo Medina','Nicolas Tagliafico',
    'Leandro Paredes','Rodrigo De Paul','Exequiel Palacios','Enzo Fernandez',
    'Alexis Mac Allister','Giovani Lo Celso','Valentin Barco',
    'Lionel Messi','Nico Paz','Thiago Almada','Nicolas Gonzalez','Giuliano Simeone',
    'Lautaro Martinez','Jose Manuel Lopez','Julian Alvarez'],
'Austria': ['Alexander Schlager','Florian Wiegele','Patrick Pentz',
    'David Affengruber','Kevin Danso','Stefan Posch','David Alaba','Philipp Lienhart',
    'Philipp Mwene','Alexander Prass','Marco Friedl','Michael Svoboda',
    'Xaver Schlager','Nicolas Seiwald','Marcel Sabitzer','Florian Grillitsch',
    'Carney Chukwuemeka','Romano Schmid','Christoph Baumgartner','Konrad Laimer',
    'Patrick Wimmer','Paul Wanner','Alessandro Schopf',
    'Marko Arnautovic','Michael Gregoritsch','Sasa Kalajdzic'],
'Portugal': ['Diogo Costa','Jose Sa','Rui Silva','Ricardo Velho',
    'Ruben Dias','Joao Cancelo','Diogo Dalot','Nuno Mendes','Nelson Semedo',
    'Matheus Nunes','Goncalo Inacio','Renato Veiga','Tomas Araujo',
    'Bruno Fernandes','Bernardo Silva','Vitinha','Joao Neves','Ruben Neves','Samu Costa',
    'Cristiano Ronaldo','Rafael Leao','Joao Felix','Goncalo Ramos','Pedro Neto',
    'Francisco Conceicao','Goncalo Guedes','Francisco Trincao'],
'DR Congo': ['Lionel Mpasi','Timothy Fayulu','Matthieu Epolo',
    'Chancel Mbemba','Axel Tuanzebe','Arthur Masuaku','Gedeon Kalulu','Joris Kayembe',
    'Aaron Wan-Bissaka','Aaron Tshibola','Steve Kapuadi','Dylan Batubinsika',
    'Noah Sadiki','Charles Pickel','Edo Kayembe','Samuel Moutoussamy','Ngal ayel Mukau',
    'Nathanael Mbuku','Meschak Elia','Brian Cipenga','Gael Kakuta','Theo Bongonda',
    'Simon Banza','Yoane Wissa','Fiston Mayele','Cedric Bakambu'],
'Uzbekistan': ['Vladimir Nazarov','Utkir Yusupov','Botirali Ergashev','Abduvokhid Nematov',
    'Ibrohimkhalil Yuldoshev','Avazbek Ulmasaliev','Jakhongir Urozov','Rustamjon Ashurmatov',
    'Mukhammadkodir Hamraliev','Umarbek Eshmurodov','Abdukodir Khusanov','Abdulla Abdullaev',
    'Farrukh Sayfiev','Khojiakbar Alijonov','Sherzod Nasrullaev','Behruz Karimov',
    'Kuvondik Ruziev','Sherzod Esanov','Nodirbek Abdurazzokov','Odiljon Khamrobekov',
    'Umarali Rakhmonaliev','Alisher Odilov','Sardorbek Rakhmonov','Akmal Mozgovoy',
    'Otabek Shukurov','Jamshid Iskanderov','Azizjon Ganiev',
    'Abbosbek Fayzullayev','Jaloliddin Masharipov','Dostonbek Khamdamov','Oston Urunov',
    'Eldor Shomurodov'],
'Colombia': ['Alvaro Montero','David Ospina','Camilo Vargas',
    'Santiago Arias','Willer Ditta','Jhon Lucumi','Deiver Machado','Yerry Mina','Johan Mojica',
    'Daniel Munoz','Davinson Sanchez',
    'Jhon Arias','Jaminton Campaz','Jorge Carrascal','Kevin Castano','Jefferson Lerma',
    'Juan Camilo Portilla','Gustavo Puerta','Juan Fernando Quintero','James Rodriguez',
    'Richard Rios',
    'Jhon Cordoba','Carlos Andres Gomez','Juan Camilo Hernandez','Luis Suarez','Luis Diaz'],
'England': ['Jordan Pickford','Dean Henderson','James Trafford',
    'Reece James','Ezri Konsa','Jarell Quansah','John Stones','Marc Guehi','Dan Burn',
    'Nico O Reilly','Djed Spence','Tino Livramento',
    'Declan Rice','Elliot Anderson','Kobbie Mainoo','Jordan Henderson','Morgan Rogers',
    'Jude Bellingham','Eberechi Eze',
    'Harry Kane','Ivan Toney','Ollie Watkins','Bukayo Saka','Marcus Rashford',
    'Anthony Gordon','Noni Madueke'],
'Croatia': ['Dominik Livakovic','Dominik Kotarski','Ivor Pandur',
    'Josko Gvardiol','Duje Caleta-Car','Josip Sutalo','Josip Stanisic','Marin Pongracic',
    'Martin Erlic','Luka Vuskovic',
    'Luka Modric','Mateo Kovacic','Mario Pasalic','Nikola Vlasic','Luka Sucic',
    'Martin Baturina','Kristijan Jakic','Petar Sucic','Nikola Moro','Toni Fruk',
    'Ivan Perisic','Andrej Kramaric','Ante Budimir','Marco Pasalic','Petar Musa','Igor Matanovic'],
'Ghana': ['Benjamin Asare','Lawrence Ati-Zigi','Joseph Anang','Solomon Agbasi','Paul Reverson',
    'Baba Abdul Rahman','Gideon Mensah','Marvin Senaya','Alidu Seidu','Abdul Mumin',
    'Jerome Opoku','Jonas Adjetey','Kojo Oppong Peprah','Alexander Djiku','Elisha Owusu',
    'Thomas Partey','Kwasi Sibo','Augustine Boakye','Caleb Yirenkyi','Abdul Fatawu Issahaku',
    'Kamal Deen Sulemana','Christopher Bonsu Baah','Ernest Nuamah','Antoine Semenyo',
    'Brandon Thomas-Asante','Prince Kwabena Adu','Inaki Williams','Jordan Ayew'],
'Panama': ['Orlando Mosquera','Luis Mejia','Cesar Samudio',
    'Cesar Blackman','Jorge Gutierrez','Amir Murillo','Fidel Escobar','Andres Andrade',
    'Edgardo Farina','Jose Cordoba','Eric Davis','Jiovany Ramos','Roderick Miller',
    'Anibal Godoy','Adalberto Carrasquilla','Carlos Harvey','Cristian Martinez',
    'Jose Luis Rodriguez','Cesar Yanis','Yoel Barcenas','Alberto Quintero',
    'Azarias Londono','Ismael Diaz','Cecilio Waterman','Jose Fajardo','Tomas Rodriguez'],
}

# Build normalized lookup for each team
official_norm = {t: {norm(p): p for p in players} for t, players in OFFICIAL.items()}

# DB team name aliases
DB_ALIASES = {
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'South Africa': 'South Africa', 'South Korea': 'South Korea',
    'DR Congo': 'DR Congo', 'Ivory Coast': 'Ivory Coast',
    'New Zealand': 'New Zealand', 'Cape Verde': 'Cape Verde',
}

changes = []
errors = []

for team_name, off_norm in official_norm.items():
    db_name = DB_ALIASES.get(team_name, team_name)
    row = conn.execute('SELECT id FROM teams WHERE name=?', (db_name,)).fetchone()
    if not row:
        errors.append(f"Team not in DB: {db_name}")
        continue
    tid = row['id']
    
    xi = conn.execute('''SELECT pl.id as lid, p.id as pid, p.name
        FROM projected_lineups pl JOIN players p ON pl.player_id=p.id
        WHERE pl.team_id=? AND pl.is_starter=1''', (tid,)).fetchall()
    
    for player in xi:
        pnorm = norm(player['name'])
        if pnorm not in off_norm:
            changes.append({
                'team': db_name, 'tid': tid,
                'out_name': player['name'], 'out_pid': player['pid'], 'out_lid': player['lid']
            })

print(f"\n{'='*65}")
print(f"JUGADORES EN XI QUE NO ESTÁN EN CONVOCATORIA OFICIAL: {len(changes)}")
print(f"{'='*65}")
for c in changes:
    print(f"  ❌ {c['team']}: {c['out_name']}")

