"""
squads_master_wc2026.py — Fuente de verdad única para los 48 equipos WC2026.
Corre esto antes de rebuild_squads.py. Idempotente.
"""
import sys, sqlite3, logging
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))
DB_PATH = BASE_DIR / "data" / "mundial2026.db"

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-7s %(message)s", datefmt="%H:%M:%S")
log = logging.getLogger("squads_master")

# fmt: (name, pos, caps, goals, age, club, league)
SQUADS: dict = {

# ═══════════════════════════════════════════════════════════════
# UEFA
# ═══════════════════════════════════════════════════════════════
"Italy": [
    ("Gianluigi Donnarumma","GK",78,0,26,"Paris Saint-Germain","ligue 1"),
    ("Guglielmo Vicario","GK",12,0,29,"Tottenham Hotspur","premier league"),
    ("Alessandro Gollini","GK",8,0,33,"Fiorentina","serie a"),
    ("Giovanni Di Lorenzo","DEF",62,3,32,"Napoli","serie a"),
    ("Alessandro Bastoni","DEF",48,2,26,"Inter Milan","serie a"),
    ("Federico Dimarco","DEF",38,5,27,"Inter Milan","serie a"),
    ("Riccardo Calafiori","DEF",22,2,23,"Arsenal","premier league"),
    ("Andrea Cambiaso","DEF",22,2,25,"Juventus","serie a"),
    ("Destiny Udogie","DEF",16,1,23,"Tottenham Hotspur","premier league"),
    ("Matteo Darmian","DEF",44,2,35,"Inter Milan","serie a"),
    ("Caleb Okoli","DEF",10,0,23,"Leicester City","championship"),
    ("Nicolo Barella","MID",80,15,27,"Inter Milan","serie a"),
    ("Sandro Tonali","MID",36,4,25,"Newcastle United","premier league"),
    ("Davide Frattesi","MID",28,7,26,"Inter Milan","serie a"),
    ("Lorenzo Pellegrini","MID",48,12,28,"Roma","serie a"),
    ("Jorginho","MID",64,8,34,"Arsenal","premier league"),
    ("Nicolo Fagioli","MID",14,1,24,"Juventus","serie a"),
    ("Samuele Ricci","MID",18,1,24,"Torino","serie a"),
    ("Federico Chiesa","FWD",56,15,28,"Liverpool","premier league"),
    ("Giacomo Raspadori","FWD",36,10,26,"Napoli","serie a"),
    ("Mateo Retegui","FWD",22,12,26,"Atalanta","serie a"),
    ("Gianluca Scamacca","FWD",32,10,26,"Atalanta","serie a"),
    ("Moise Kean","FWD",22,8,25,"Juventus","serie a"),
    ("Wilfried Gnonto","FWD",16,4,22,"Leeds United","championship"),
    ("Mattia Zaccagni","MID",36,8,30,"Lazio","serie a"),
    ("Luca Pellegrini","DEF",14,0,26,"Lazio","serie a"),
],

"Belgium": [
    ("Thibaut Courtois","GK",106,0,33,"Real Madrid","la liga"),
    ("Koen Casteels","GK",34,0,33,"Al-Qadsiah","saudi pro league"),
    ("Thomas Kaminski","GK",16,0,33,"Luton Town","championship"),
    ("Timothy Castagne","DEF",58,3,29,"Fulham","premier league"),
    ("Wout Faes","DEF",28,1,27,"Leicester City","premier league"),
    ("Arthur Theate","DEF",24,1,25,"Stade Rennais","ligue 1"),
    ("Zeno Debast","DEF",20,1,22,"Sporting CP","primeira liga"),
    ("Thomas Meunier","DEF",56,4,34,"Trabzonspor","super lig"),
    ("Brandon Mechele","DEF",22,0,32,"Club Brugge","pro league"),
    ("Maxim De Cuyper","DEF",14,1,24,"Club Brugge","pro league"),
    ("Kevin De Bruyne","MID",112,26,35,"Manchester City","premier league"),
    ("Amadou Onana","MID",32,3,24,"Aston Villa","premier league"),
    ("Youri Tielemans","MID",62,10,28,"Aston Villa","premier league"),
    ("Charles De Ketelaere","MID",34,6,24,"Atalanta","serie a"),
    ("Alexis Saelemaekers","MID",28,3,26,"Bologna","serie a"),
    ("Johan Bakayoko","MID",16,3,23,"AC Milan","serie a"),
    ("Hans Vanaken","MID",44,8,32,"Club Brugge","pro league"),
    ("Aster Vranckx","MID",14,1,23,"Wolfsburg","bundesliga"),
    ("Romelu Lukaku","FWD",116,72,31,"Napoli","serie a"),
    ("Jeremy Doku","FWD",32,5,23,"Manchester City","premier league"),
    ("Lois Openda","FWD",36,14,25,"RB Leipzig","bundesliga"),
    ("Leandro Trossard","FWD",44,10,30,"Arsenal","premier league"),
    ("Dodi Lukebakio","FWD",28,8,28,"Sevilla","la liga"),
    ("Loïs Openda","FWD",36,14,25,"RB Leipzig","bundesliga"),
    ("Orel Mangala","MID",22,2,27,"Everton","premier league"),
    ("Albert Sambi Lokonga","MID",20,1,25,"Luton Town","championship"),
],

"Switzerland": [
    ("Yann Sommer","GK",90,0,37,"Inter Milan","serie a"),
    ("Gregor Kobel","GK",28,0,28,"Borussia Dortmund","bundesliga"),
    ("Philipp Köhn","GK",8,0,26,"RB Salzburg","bundesliga at"),
    ("Manuel Akanji","DEF",66,4,29,"Manchester City","premier league"),
    ("Fabian Schär","DEF",62,8,33,"Newcastle United","premier league"),
    ("Nico Elvedi","DEF",56,3,28,"Borussia M'gladbach","bundesliga"),
    ("Silvan Widmer","DEF",46,4,32,"Mainz","bundesliga"),
    ("Ricardo Rodriguez","DEF",76,4,33,"Torino","serie a"),
    ("Kevin Mbabu","DEF",32,1,29,"Augsburg","bundesliga"),
    ("Loris Benito","DEF",14,0,33,"Bordeaux","ligue 2 fr"),
    ("Granit Xhaka","MID",126,16,33,"Bayer Leverkusen","bundesliga"),
    ("Denis Zakaria","MID",38,3,28,"Monaco","ligue 1"),
    ("Remo Freuler","MID",56,5,33,"Bologna","serie a"),
    ("Fabian Rieder","MID",22,3,23,"Stade Rennais","ligue 1"),
    ("Ardon Jashari","MID",16,1,23,"Club Brugge","pro league"),
    ("Xherdan Shaqiri","MID",106,32,34,"Chicago Fire","mls"),
    ("Michel Aebischer","MID",24,3,28,"Bologna","serie a"),
    ("Vincent Sierro","MID",16,2,30,"Toulouse","ligue 1"),
    ("Ruben Vargas","FWD",32,8,26,"Augsburg","bundesliga"),
    ("Breel Embolo","FWD",62,16,28,"Monaco","ligue 1"),
    ("Noah Okafor","FWD",32,8,25,"AC Milan","serie a"),
    ("Dan Ndoye","FWD",22,4,24,"Bologna","serie a"),
    ("Zeki Amdouni","FWD",18,6,24,"Burnley","championship"),
    ("Kwadwo Duah","FWD",12,3,28,"Nuremberg","bundesliga 2"),
    ("Renato Steffen","FWD",44,10,33,"Lugano","swiss super league"),
    ("Christian Fassnacht","FWD",36,8,31,"Werder Bremen","bundesliga"),
],

"Croatia": [
    ("Dominik Livaković","GK",52,0,30,"Fenerbahçe","super lig"),
    ("Ivica Ivušić","GK",12,0,28,"Osijek","hnl"),
    ("Nediljko Labrović","GK",6,0,27,"Hajduk Split","hnl"),
    ("Joško Gvardiol","DEF",58,6,23,"Manchester City","premier league"),
    ("Josip Šutalo","DEF",22,1,24,"Ajax","eredivisie"),
    ("Duje Ćaleta-Car","DEF",52,3,28,"Southampton","championship"),
    ("Borna Sosa","DEF",38,3,27,"Ajax","eredivisie"),
    ("Josip Stanišić","DEF",22,1,25,"Bayer Leverkusen","bundesliga"),
    ("Martin Erlić","DEF",26,1,28,"Sassuolo","serie a"),
    ("Petar Sucić","DEF",8,0,22,"RB Salzburg","bundesliga at"),
    ("Luka Modrić","MID",175,24,41,"Real Madrid","la liga"),
    ("Mateo Kovačić","MID",102,16,32,"Manchester City","premier league"),
    ("Marcelo Brozović","MID",96,16,33,"Al-Nassr","saudi pro league"),
    ("Mario Pašalić","MID",46,10,30,"Atalanta","serie a"),
    ("Lovro Majer","MID",36,6,28,"Wolfsburg","bundesliga"),
    ("Luka Sučić","MID",22,3,24,"RB Leipzig","bundesliga"),
    ("Nikola Moro","MID",20,2,28,"Dynamo Moscow","russian premier league"),
    ("Kristijan Jakić","MID",26,1,28,"Eintracht Frankfurt","bundesliga"),
    ("Andrej Kramarić","FWD",82,34,34,"Hoffenheim","bundesliga"),
    ("Bruno Petković","FWD",38,14,32,"Dinamo Zagreb","hnl"),
    ("Ante Budimir","FWD",32,12,35,"Osasuna","la liga"),
    ("Marko Livaja","FWD",22,8,32,"Hajduk Split","hnl"),
    ("Ivan Perišić","FWD",120,34,37,"Hajduk Split","hnl"),
    ("Mislav Oršić","FWD",26,6,32,"Celta Vigo","la liga"),
    ("Dario Špehar","FWD",8,2,26,"Dinamo Zagreb","hnl"),
    ("Roko Šimić","FWD",6,1,20,"AC Milan","serie a"),
],

"Denmark": [
    ("Kasper Schmeichel","GK",96,0,39,"Anderlecht","pro league"),
    ("Oliver Christensen","GK",12,0,26,"Fiorentina","serie a"),
    ("Mads Hermansen","GK",8,0,27,"Leicester City","premier league"),
    ("Andreas Christensen","DEF",68,3,29,"Barcelona","la liga"),
    ("Joachim Andersen","DEF",38,2,29,"Crystal Palace","premier league"),
    ("Victor Nelsson","DEF",26,2,28,"Galatasaray","super lig"),
    ("Rasmus Kristensen","DEF",28,1,28,"Eintracht Frankfurt","bundesliga"),
    ("Joakim Mæhle","DEF",56,6,28,"Wolfsburg","bundesliga"),
    ("Alexander Bah","DEF",22,1,27,"Benfica","primeira liga"),
    ("Jannik Vestergaard","DEF",66,4,33,"Leicester City","premier league"),
    ("Pierre-Emile Højbjerg","MID",92,12,30,"Atletico Madrid","la liga"),
    ("Christian Eriksen","MID",132,42,34,"Manchester United","premier league"),
    ("Mikkel Damsgaard","MID",38,5,25,"Brentford","premier league"),
    ("Mathias Jensen","MID",32,3,29,"Brentford","premier league"),
    ("Martin Braithwaite","FWD",76,10,34,"Espanyol","la liga"),
    ("Yussuf Poulsen","FWD",66,14,31,"RB Leipzig","bundesliga"),
    ("Mads Pedersen","DEF",28,3,28,"Fulham","premier league"),
    ("Robert Skov","FWD",22,3,29,"Hoffenheim","bundesliga"),
    ("Mohamed Daramy","FWD",22,4,23,"Ajax","eredivisie"),
    ("Jesper Lindström","MID",22,5,25,"Napoli","serie a"),
    ("Rasmus Højlund","FWD",30,12,23,"Manchester United","premier league"),
    ("Kasper Dolberg","FWD",46,16,28,"Nice","ligue 1"),
    ("Andreas Skov Olsen","FWD",30,8,27,"Club Brugge","pro league"),
    ("Simon Kjær","DEF",140,8,36,"AC Milan","serie a"),
    ("Thomas Delaney","MID",80,8,34,"Anderlecht","pro league"),
    ("Emilio Eriksen","MID",6,0,22,"Midtjylland","superliga"),
],

"Austria": [
    ("Patrick Pentz","GK",28,0,28,"Bayer Leverkusen","bundesliga"),
    ("Alexander Schlager","GK",22,0,30,"LASK","austrian bundesliga"),
    ("Heinz Lindner","GK",16,0,36,"FC Basel","swiss super league"),
    ("David Alaba","DEF",104,16,34,"Real Madrid","la liga"),
    ("Gernot Trauner","DEF",46,3,33,"Feyenoord","eredivisie"),
    ("Philipp Lienhart","DEF",36,1,29,"Freiburg","bundesliga"),
    ("Stefan Posch","DEF",36,2,27,"Bologna","serie a"),
    ("Maximilian Wöber","DEF",32,1,27,"Borussia M'gladbach","bundesliga"),
    ("Leopold Querfeld","DEF",12,0,22,"Rapid Wien","austrian bundesliga"),
    ("Phillipp Mwene","DEF",22,1,32,"PSV","eredivisie"),
    ("Nicolas Seiwald","MID",32,2,24,"RB Leipzig","bundesliga"),
    ("Christoph Baumgartner","MID",42,10,26,"RB Leipzig","bundesliga"),
    ("Marcel Sabitzer","MID",82,16,31,"Borussia Dortmund","bundesliga"),
    ("Konrad Laimer","MID",46,5,28,"Bayern Munich","bundesliga"),
    ("Florian Grillitsch","MID",46,4,30,"Ajax","eredivisie"),
    ("Patrick Wimmer","MID",22,3,24,"Wolfsburg","bundesliga"),
    ("Nicolas Ofner","MID",8,1,24,"Sturm Graz","austrian bundesliga"),
    ("Romano Schmid","MID",22,3,25,"Werder Bremen","bundesliga"),
    ("Marko Arnautovic","FWD",116,36,37,"Inter Milan","serie a"),
    ("Michael Gregoritsch","FWD",66,20,31,"Freiburg","bundesliga"),
    ("Andreas Weimann","FWD",32,8,33,"Wolfsburg","bundesliga"),
    ("Christoph Monschein","FWD",14,4,32,"LASK","austrian bundesliga"),
    ("Sasa Kalajdzic","FWD",28,8,28,"Wolfsburg","bundesliga"),
    ("Adrian Grbic","FWD",16,4,28,"Lorient","ligue 1"),
    ("Karim Onisiwo","FWD",36,10,33,"Mainz","bundesliga"),
    ("Guido Burgstaller","FWD",44,12,36,"Rapid Wien","austrian bundesliga"),
],

"Poland": [
    ("Wojciech Szczęsny","GK",86,0,36,"Barcelona","la liga"),
    ("Łukasz Skorupski","GK",26,0,34,"Bologna","serie a"),
    ("Bartłomiej Drągowski","GK",12,0,27,"Spezia","serie b"),
    ("Jan Bednarek","DEF",72,4,28,"Aston Villa","premier league"),
    ("Matty Cash","DEF",42,2,28,"Aston Villa","premier league"),
    ("Michał Helik","DEF",22,2,30,"Burnley","championship"),
    ("Paweł Dawidowicz","DEF",32,1,29,"Hellas Verona","serie a"),
    ("Kamil Piątkowski","DEF",22,1,26,"RB Salzburg","bundesliga at"),
    ("Bartosz Bereszyński","DEF",56,1,32,"Sampdoria","serie b"),
    ("Jakub Kiwior","DEF",28,1,25,"Arsenal","premier league"),
    ("Piotr Zieliński","MID",92,24,30,"Inter Milan","serie a"),
    ("Nicola Zalewski","MID",28,3,23,"Roma","serie a"),
    ("Szymon Żurkowski","MID",32,4,27,"Empoli","serie a"),
    ("Jakub Kamiński","MID",26,3,24,"Wolfsburg","bundesliga"),
    ("Sebastian Szymański","MID",52,12,27,"Fenerbahçe","super lig"),
    ("Michał Skóraś","MID",22,3,25,"Club Brugge","pro league"),
    ("Kacper Urbański","MID",14,2,20,"Bologna","serie a"),
    ("Krzysztof Piątek","FWD",38,10,30,"Basel","swiss super league"),
    ("Robert Lewandowski","FWD",152,84,38,"Barcelona","la liga"),
    ("Arkadiusz Milik","FWD",72,22,32,"Juventus","serie a"),
    ("Karol Świderski","FWD",42,16,28,"Charlotte FC","mls"),
    ("Adam Buksa","FWD",22,8,28,"RC Lens","ligue 1"),
    ("Dawid Kownacki","FWD",26,5,28,"Fortuna Düsseldorf","bundesliga 2"),
    ("Przemysław Frankowski","MID",46,8,29,"RC Lens","ligue 1"),
    ("Mateusz Klich","MID",68,10,34,"DC United","mls"),
    ("Bartosz Slisz","MID",16,1,25,"Atlanta United","mls"),
],

"Turkey": [
    ("Altay Bayındır","GK",28,0,27,"Manchester United","premier league"),
    ("Uğurcan Çakır","GK",32,0,29,"Trabzonspor","super lig"),
    ("Mert Günok","GK",16,0,36,"Besiktas","super lig"),
    ("Merih Demiral","DEF",46,6,27,"Al-Qadsiah","saudi pro league"),
    ("Zeki Çelik","DEF",46,2,26,"Roma","serie a"),
    ("Abdülkerim Bardakcı","DEF",28,2,28,"Galatasaray","super lig"),
    ("Ferdi Kadıoğlu","DEF",32,3,26,"Brighton","premier league"),
    ("Samet Akaydın","DEF",22,1,28,"Fenerbahçe","super lig"),
    ("Mert Müldür","DEF",22,1,26,"Fiorentina","serie a"),
    ("Çağlar Söyüncü","DEF",56,4,28,"Atletico Madrid","la liga"),
    ("Hakan Çalhanoğlu","MID",82,22,32,"Inter Milan","serie a"),
    ("Salih Özcan","MID",32,2,27,"Borussia Dortmund","bundesliga"),
    ("Kaan Ayhan","MID",42,4,29,"Galatasaray","super lig"),
    ("Barış Alper Yılmaz","MID",26,4,24,"Galatasaray","super lig"),
    ("Okay Yokuslu","MID",56,4,31,"West Brom","championship"),
    ("Orkun Kökçü","MID",28,5,24,"Benfica","primeira liga"),
    ("Halil Dervişoğlu","MID",16,3,24,"Brentford","premier league"),
    ("İlkay Gündoğan","MID",68,18,35,"Barcelona","la liga"),
    ("Arda Güler","FWD",28,7,21,"Real Madrid","la liga"),
    ("Kenan Yıldız","FWD",22,6,21,"Juventus","serie a"),
    ("Cenk Tosun","FWD",102,30,35,"Besiktas","super lig"),
    ("Yusuf Yazıcı","FWD",46,16,28,"CSKA Moscow","russian premier league"),
    ("Baris Yilmaz","FWD",16,4,25,"Galatasaray","super lig"),
    ("Semih Kılıçsoy","FWD",12,4,19,"Besiktas","super lig"),
    ("Muhammed Şenoğlu","FWD",8,2,22,"Besiktas","super lig"),
    ("Efecan Karaca","MID",6,1,23,"Galatasaray","super lig"),
],

"Serbia": [
    ("Vanja Milinković-Savić","GK",42,0,28,"Torino","serie a"),
    ("Predrag Rajković","GK",32,0,30,"Mallorca","la liga"),
    ("Marko Dmitrović","GK",26,0,32,"Sevilla","la liga"),
    ("Strahinja Pavlović","DEF",42,2,24,"AC Milan","serie a"),
    ("Nikola Milenković","DEF",56,5,27,"Nottingham Forest","premier league"),
    ("Stefan Mitrović","DEF",32,2,32,"Getafe","la liga"),
    ("Srđan Babić","DEF",18,1,28,"Sturm Graz","austrian bundesliga"),
    ("Mihailo Ristić","DEF",28,1,30,"Montpellier","ligue 1"),
    ("Ognjen Mimović","DEF",12,0,22,"Borussia M'gladbach","bundesliga"),
    ("Nemanja Maksimović","DEF",38,2,30,"Getafe","la liga"),
    ("Sergej Milinković-Savić","MID",66,18,31,"Al-Hilal","saudi pro league"),
    ("Nemanja Gudelj","MID",38,3,33,"Sevilla","la liga"),
    ("Saša Lukić","MID",42,4,29,"Fulham","premier league"),
    ("Filip Kostić","MID",76,16,32,"Juventus","serie a"),
    ("Andrija Živković","MID",36,6,29,"PAOK","super league greece"),
    ("Luka Ilić","MID",16,2,24,"Torino","serie a"),
    ("Nemanja Radonjić","MID",24,4,29,"Benfica","primeira liga"),
    ("Marko Grujić","MID",36,5,28,"Porto","primeira liga"),
    ("Aleksandar Mitrović","FWD",106,56,32,"Al-Hilal","saudi pro league"),
    ("Dušan Vlahović","FWD",42,20,26,"Juventus","serie a"),
    ("Luka Jović","FWD",42,14,28,"Fiorentina","serie a"),
    ("Ivan Ilić","MID",22,3,24,"Torino","serie a"),
    ("Veljko Birmančević","FWD",18,4,26,"Marseille","ligue 1"),
    ("Aleksandar Pavlović","MID",8,1,21,"Bayern Munich","bundesliga"),
    ("Stefan Bajić","GK",4,0,23,"Clermont","ligue 2 fr"),
    ("Lazar Samardzić","MID",14,3,23,"Inter Milan","serie a"),
],

"Scotland": [
    ("Angus Gunn","GK",32,0,28,"Norwich City","championship"),
    ("Liam Kelly","GK",16,0,30,"Motherwell","scottish premiership"),
    ("Craig Gordon","GK",72,0,42,"Hearts","scottish premiership"),
    ("Andrew Robertson","DEF",86,5,32,"Liverpool","premier league"),
    ("Kieran Tierney","DEF",52,4,28,"Real Sociedad","la liga"),
    ("Scott McKenna","DEF",42,4,30,"Nottingham Forest","premier league"),
    ("Aaron Hickey","DEF",22,1,24,"Brentford","premier league"),
    ("Grant Hanley","DEF",52,4,34,"Norwich City","championship"),
    ("Anthony Ralston","DEF",18,0,25,"Celtic","scottish premiership"),
    ("Jack Hendry","DEF",36,4,29,"Club Brugge","pro league"),
    ("Scott McTominay","MID",62,14,28,"Napoli","serie a"),
    ("John McGinn","MID",72,10,30,"Aston Villa","premier league"),
    ("Callum McGregor","MID",52,6,31,"Celtic","scottish premiership"),
    ("Ryan Christie","MID",56,10,30,"Bournemouth","premier league"),
    ("Billy Gilmour","MID",22,1,24,"Brighton","premier league"),
    ("Stuart Armstrong","MID",36,6,32,"Southampton","championship"),
    ("Kenny McLean","MID",52,4,34,"Norwich City","championship"),
    ("Ryan Jack","MID",28,2,32,"Rangers","scottish premiership"),
    ("Lyndon Dykes","FWD",42,14,29,"QPR","championship"),
    ("Che Adams","FWD",34,10,29,"Torino","serie a"),
    ("Lawrence Shankland","FWD",26,12,29,"Hearts","scottish premiership"),
    ("Ryan Fraser","FWD",16,4,31,"Southampton","championship"),
    ("Ross Stewart","FWD",14,6,28,"Sunderland","championship"),
    ("Liam Scales","DEF",14,0,25,"Celtic","scottish premiership"),
    ("Kevin Nisbet","FWD",12,3,27,"Hibernian","scottish premiership"),
    ("Ben Doak","FWD",10,2,20,"Liverpool","premier league"),
],

"Hungary": [
    ("Péter Gulácsi","GK",86,0,35,"RB Leipzig","bundesliga"),
    ("Dénes Dibusz","GK",32,0,33,"Ferencváros","otp bank liga"),
    ("András Schäfer","GK",4,0,24,"Union Berlin","bundesliga"),
    ("Willi Orbán","DEF",56,7,33,"RB Leipzig","bundesliga"),
    ("Attila Szalai","DEF",56,9,28,"Fenerbahçe","super lig"),
    ("Endre Botka","DEF",26,1,30,"Ferencváros","otp bank liga"),
    ("Loïc Négo","DEF",46,2,31,"Le Havre","ligue 1"),
    ("Bendegúz Bolla","DEF",26,1,26,"Servette","swiss super league"),
    ("Miloš Kerkez","DEF",22,1,22,"AFC Bournemouth","premier league"),
    ("Botond Balogh","DEF",14,0,24,"Parma","serie b"),
    ("Dominik Szoboszlai","MID",46,14,24,"Liverpool","premier league"),
    ("Ádám Nagy","MID",72,3,31,"Bristol City","championship"),
    ("András Schäfer","MID",28,3,24,"Union Berlin","bundesliga"),
    ("Dániel Gazdag","MID",32,8,29,"Philadelphia Union","mls"),
    ("Callum Styles","MID",26,4,25,"Middlesbrough","championship"),
    ("Zsolt Nagy","MID",18,2,29,"Puskás Akadémia","otp bank liga"),
    ("Roland Sallai","FWD",52,14,28,"Freiburg","bundesliga"),
    ("Barnabás Varga","FWD",36,14,31,"Ferencváros","otp bank liga"),
    ("Martin Ádám","FWD",36,14,30,"Watford","championship"),
    ("Kevin Csoboth","FWD",16,4,25,"Servette","swiss super league"),
    ("Ádám Szalai","FWD",70,26,37,"retired","serie a"),
    ("Krisztián Lisztes","MID",8,1,21,"Eintracht Frankfurt","bundesliga"),
    ("Csoboth Kevin","FWD",16,4,25,"Servette","swiss super league"),
    ("Ádám Bogdán","GK",12,0,38,"Celtic","scottish premiership"),
    ("Bence Merész","GK",6,0,22,"Ferencváros","otp bank liga"),
    ("Roland Varga","DEF",8,0,23,"Ferencváros","otp bank liga"),
],

"Romania": [
    ("Florin Niță","GK",56,0,37,"Damac FC","saudi pro league"),
    ("Horațiu Moldovan","GK",32,0,29,"Atletico Madrid","la liga"),
    ("Ștefan Târnovanu","GK",8,0,24,"FCSB","superliga"),
    ("Radu Drăgușin","DEF",32,2,24,"Tottenham Hotspur","premier league"),
    ("Andrei Rațiu","DEF",32,2,27,"Rayo Vallecano","la liga"),
    ("Adrian Rus","DEF",22,1,28,"Pisa","serie b"),
    ("Bogdan Racovițan","DEF",16,0,25,"Rakow Czestochowa","ekstraklasa"),
    ("Ionuț Nedelcearu","DEF",36,2,28,"Palermo","serie b"),
    ("Cristian Manea","DEF",22,1,29,"CFR Cluj","superliga"),
    ("Vlad Chiricheș","DEF",96,5,36,"Sassuolo","serie a"),
    ("Deian Sorescu","MID",32,3,30,"Boavista","primeira liga"),
    ("Marius Marin","MID",26,2,26,"Pisa","serie b"),
    ("Răzvan Marin","MID",56,6,29,"Empoli","serie a"),
    ("Florinel Coman","FWD",36,10,27,"FCSB","superliga"),
    ("Nicolae Stanciu","MID",56,8,32,"Damac FC","saudi pro league"),
    ("Florin Tănase","MID",36,5,31,"Universitatea Craiova","superliga"),
    ("Ianis Hagi","MID",42,8,26,"Deportivo Alavés","la liga"),
    ("Valentin Mihăilă","FWD",28,6,25,"Parma","serie b"),
    ("Denis Drăguș","FWD",28,8,27,"Gaziantep FK","super lig"),
    ("Daniel Bîrligea","FWD",22,6,26,"CFR Cluj","superliga"),
    ("George Pușcaș","FWD",36,14,28,"Bari","serie b"),
    ("Radu Drăgușin","DEF",32,2,24,"Tottenham Hotspur","premier league"),
    ("Alexandru Chipciu","MID",52,10,36,"Universitatea Cluj","superliga"),
    ("Ciprian Tătărușanu","GK",72,0,38,"Nantes","ligue 1"),
    ("Nicușor Bancu","DEF",36,2,32,"Universitatea Craiova","superliga"),
    ("Adrian Șut","MID",14,2,25,"FCSB","superliga"),
],

"Czechia": [
    ("Jiří Staněk","GK",28,0,28,"Feyenoord","eredivisie"),
    ("Matyáš Tětka","GK",10,0,26,"Viktoria Plzeň","czech first league"),
    ("Jindřich Staněk","GK",6,0,28,"Feyenoord","eredivisie"),
    ("Tomáš Holeš","DEF",36,3,30,"Slavia Prague","czech first league"),
    ("Ladislav Krejčí","DEF",22,1,24,"Sparta Prague","czech first league"),
    ("Martin Vitík","DEF",18,1,23,"Sparta Prague","czech first league"),
    ("Robin Hranáč","DEF",16,1,26,"Viktoria Plzeň","czech first league"),
    ("Vladimír Coufal","DEF",42,1,32,"West Ham","premier league"),
    ("Aleš Matějů","DEF",26,0,29,"Spezia","serie b"),
    ("David Zima","DEF",22,0,25,"Torino","serie a"),
    ("Tomáš Souček","MID",66,16,30,"West Ham","premier league"),
    ("Lukáš Provod","MID",26,4,28,"Slavia Prague","czech first league"),
    ("Alex Král","MID",46,3,26,"Augsburg","bundesliga"),
    ("Ondřej Lingr","MID",22,4,26,"Feyenoord","eredivisie"),
    ("Jan Kuchta","MID",32,6,28,"Lazio","serie a"),
    ("Jakub Pešek","MID",12,2,24,"Sparta Prague","czech first league"),
    ("Patrik Schick","FWD",52,28,30,"Bayer Leverkusen","bundesliga"),
    ("Tomáš Čvančara","FWD",22,6,25,"Borussia M'gladbach","bundesliga"),
    ("Ondřej Šašinka","FWD",12,3,24,"Wisła Kraków","ekstraklasa"),
    ("Adam Hložek","FWD",28,8,22,"Bayer Leverkusen","bundesliga"),
    ("Václav Černý","FWD",22,6,27,"Wolfsburg","bundesliga"),
    ("Jakub Jankto","MID",44,5,29,"Sparta Prague","czech first league"),
    ("Antonín Barák","MID",38,7,30,"Fiorentina","serie a"),
    ("Jan Jurásek","MID",8,1,22,"Slavia Prague","czech first league"),
    ("Adam Karabec","MID",10,1,22,"Bochum","bundesliga 2"),
    ("Matěj Jurásek","MID",6,0,21,"Slavia Prague","czech first league"),
],

"Slovenia": [
    ("Jan Oblak","GK",82,0,32,"Atletico Madrid","la liga"),
    ("Igor Vekić","GK",12,0,28,"Udinese","serie a"),
    ("Matevž Vidovšek","GK",6,0,25,"Olimpija Ljubljana","slovenian prvaliga"),
    ("Jon Gorenc Stanković","DEF",42,2,30,"Sturm Graz","austrian bundesliga"),
    ("Miha Blažič","DEF",32,2,31,"Ferencváros","otp bank liga"),
    ("Žan Karničnik","DEF",32,2,30,"Celje","slovenian prvaliga"),
    ("Erik Janža","DEF",22,1,30,"Austria Wien","austrian bundesliga"),
    ("Jaka Bijol","DEF",28,3,26,"Udinese","serie a"),
    ("David Brekalo","DEF",12,0,24,"NK Maribor","slovenian prvaliga"),
    ("Petar Stojanović","DEF",42,2,28,"Empoli","serie a"),
    ("Sandi Lovrić","MID",28,3,27,"Udinese","serie a"),
    ("Adam Gnezda Čerin","MID",26,3,27,"Panathinaikos","super league greece"),
    ("Timi Elsnik","MID",22,2,27,"Celje","slovenian prvaliga"),
    ("Jasmin Kurtić","MID",82,10,35,"NK Maribor","slovenian prvaliga"),
    ("Miha Zajc","MID",52,8,30,"Fenerbahçe","super lig"),
    ("Nik Prelec","FWD",14,3,23,"Genoa","serie a"),
    ("Benjamin Šeško","FWD",32,12,22,"RB Leipzig","bundesliga"),
    ("Andraž Šporar","FWD",42,12,29,"Panathinaikos","super league greece"),
    ("Jan Mlakar","FWD",22,5,28,"Pisa","serie b"),
    ("Žan Celar","FWD",22,6,25,"Lugano","swiss super league"),
    ("Luka Zahović","FWD",28,8,30,"NK Maribor","slovenian prvaliga"),
    ("Josip Iličić","MID",60,15,36,"NK Maribor","slovenian prvaliga"),
    ("Kevin Kampl","MID",56,6,34,"RB Leipzig","bundesliga"),
    ("Tomas Elias","MID",6,0,21,"NK Maribor","slovenian prvaliga"),
    ("Alen Ozbolt","FWD",8,2,24,"NK Celje","slovenian prvaliga"),
    ("Rok Kronaveter","FWD",38,8,36,"NK Olimpija","slovenian prvaliga"),
],

# ═══════════════════════════════════════════════════════════════
# CONMEBOL
# ═══════════════════════════════════════════════════════════════
"Colombia": [
    ("Camilo Vargas","GK",56,0,34,"Atlas","liga mx"),
    ("Álvaro Montero","GK",12,0,27,"Deportes Tolima","liga betplay colombia"),
    ("Kevin Mier","GK",8,0,24,"Sevilla","la liga"),
    ("Santiago Arias","DEF",58,4,34,"Girona","la liga"),
    ("Davinson Sánchez","DEF",66,5,29,"Stade Rennais","ligue 1"),
    ("Yerry Mina","DEF",56,6,30,"Cagliari","serie a"),
    ("Carlos Cuesta","DEF",26,1,27,"Genk","pro league"),
    ("Daniel Muñoz","DEF",32,2,28,"Crystal Palace","premier league"),
    ("Johan Mojica","DEF",46,3,32,"Getafe","la liga"),
    ("Jhon Lucumí","DEF",22,0,27,"Bologna","serie a"),
    ("James Rodríguez","MID",90,28,35,"Rayo Vallecano","la liga"),
    ("Matheus Uribe","MID",56,5,31,"Porto","primeira liga"),
    ("Richard Ríos","MID",22,3,25,"Palmeiras","brasileirao"),
    ("Jhon Arias","MID",26,5,26,"Fluminense","brasileirao"),
    ("Wilmar Barrios","MID",64,4,32,"Zenit St. Petersburg","russian premier league"),
    ("Gustavo Puerta","MID",14,2,21,"Bayer Leverkusen","bundesliga"),
    ("Kevin Castaño","MID",18,2,26,"Villarreal","la liga"),
    ("Luis Díaz","FWD",72,16,28,"Liverpool","premier league"),
    ("Jhon Jáder Durán","FWD",16,6,22,"Aston Villa","premier league"),
    ("Rafael Santos Borré","FWD",46,14,29,"Internacional","brasileirao"),
    ("Jhon Córdoba","FWD",36,16,31,"Krasnodar","russian premier league"),
    ("Cucho Hernández","FWD",32,10,26,"Columbus Crew","mls"),
    ("Juan Guillermo Cuadrado","MID",106,22,38,"Independiente Medellín","liga betplay colombia"),
    ("Borja","FWD",18,6,30,"Nacional","liga betplay colombia"),
    ("Déiver Machado","DEF",14,0,33,"Lyon","ligue 1"),
    ("Óscar Estupiñán","FWD",22,8,27,"Trabzonspor","super lig"),
],

"Uruguay": [
    ("Sergio Rochet","GK",28,0,30,"Nacional","primera division uruguay"),
    ("Sebastián Sosa","GK",26,0,36,"Independiente","liga argentina"),
    ("Santiago Mele","GK",8,0,26,"Junior","liga betplay colombia"),
    ("José María Giménez","DEF",82,6,30,"Atletico Madrid","la liga"),
    ("Ronald Araújo","DEF",46,3,26,"Barcelona","la liga"),
    ("Mathías Olivera","DEF",42,2,27,"Napoli","serie a"),
    ("Matías Viña","DEF",36,2,27,"Roma","serie a"),
    ("Santiago Bueno","DEF",22,1,27,"Wolverhampton","premier league"),
    ("Guillermo Varela","DEF",26,0,33,"Flamengo","brasileirao"),
    ("Sebastián Coates","DEF",44,3,34,"Sporting CP","primeira liga"),
    ("Federico Valverde","MID",66,12,26,"Real Madrid","la liga"),
    ("Rodrigo Bentancur","MID",62,8,27,"Tottenham Hotspur","premier league"),
    ("Manuel Ugarte","MID",32,2,24,"Manchester United","premier league"),
    ("Nicolás De La Cruz","MID",32,5,28,"Flamengo","brasileirao"),
    ("Facundo Pellistri","MID",32,4,24,"Panathinaikos","super league greece"),
    ("Maximiliano Araújo","MID",26,8,25,"Sporting CP","primeira liga"),
    ("Lucas Torreira","MID",56,6,29,"Galatasaray","super lig"),
    ("Facundo Torres","FWD",28,8,26,"Orlando City","mls"),
    ("Darwin Núñez","FWD",52,26,26,"Liverpool","premier league"),
    ("Mathías Arezo","FWD",12,4,22,"Granada","liga argentina"),
    ("Maximiliano Gómez","FWD",36,12,28,"Valencia","la liga"),
    ("Edinson Cavani","FWD",136,58,39,"Boca Juniors","liga argentina"),
    ("Luciano Rodríguez","FWD",12,4,21,"Liverpool Uruguay","primera division uruguay"),
    ("Rodrigo Aguirre","FWD",14,4,25,"Monterrey","liga mx"),
    ("Brian Rodríguez","FWD",22,5,25,"Atlas","liga mx"),
    ("Giorgian De Arrascaeta","MID",52,10,30,"Flamengo","brasileirao"),
],

"Ecuador": [
    ("Hernán Galíndez","GK",36,0,36,"Estudiantes","liga argentina"),
    ("Alexander Domínguez","GK",52,0,37,"LDU Quito","ligapro ecuador"),
    ("Moisés Ramírez","GK",12,0,25,"Aucas","ligapro ecuador"),
    ("Piero Hincapié","DEF",46,2,24,"Bayer Leverkusen","bundesliga"),
    ("William Pacho","DEF",36,1,25,"Paris Saint-Germain","ligue 1"),
    ("Félix Torres","DEF",42,2,28,"Santos Laguna","liga mx"),
    ("Ángelo Preciado","DEF",42,1,27,"Genk","pro league"),
    ("Diego Palacios","DEF",26,1,26,"Los Angeles FC","mls"),
    ("Jackson Porozo","DEF",16,0,24,"Troyes","ligue 2 fr"),
    ("Xavier Arreaga","DEF",28,1,31,"Seattle Sounders","mls"),
    ("Moisés Caicedo","MID",56,5,23,"Chelsea","premier league"),
    ("Carlos Gruezo","MID",56,3,28,"Augsburg","bundesliga"),
    ("Alan Minda","MID",18,2,24,"Nottingham Forest","premier league"),
    ("Jeremy Sarmiento","MID",22,3,24,"Burnley","championship"),
    ("Kendry Páez","MID",18,4,19,"Independiente del Valle","ligapro ecuador"),
    ("Ángel Mena","MID",76,16,36,"Independiente del Valle","ligapro ecuador"),
    ("Jhegson Méndez","MID",36,2,28,"LA Galaxy","mls"),
    ("Enner Valencia","FWD",80,42,37,"Independiente","liga argentina"),
    ("Djorkaeff Reasco","FWD",22,5,26,"Nottingham Forest","premier league"),
    ("Michael Estrada","FWD",42,14,29,"Cruz Azul","liga mx"),
    ("Jordan Rezabala","FWD",14,4,24,"Independiente del Valle","ligapro ecuador"),
    ("Kevin Rodríguez","FWD",22,6,25,"Ipswich Town","premier league"),
    ("Gonzalo Plata","FWD",26,4,24,"Al-Qadsiah","saudi pro league"),
    ("Renato Ibarra","MID",38,6,33,"Cruz Azul","liga mx"),
    ("Jordy Caicedo","FWD",26,8,30,"Alanyaspor","super lig"),
    ("Byron Castillo","DEF",26,1,27,"LDU Quito","ligapro ecuador"),
],

"Venezuela": [
    ("Wuilker Faríñez","GK",58,0,28,"Millwall","championship"),
    ("Joel Graterol","GK",16,0,27,"Deportivo Táchira","liga venezuela"),
    ("Rafael Romo","GK",12,0,34,"Estudiantes","liga argentina"),
    ("Alexander González","DEF",84,5,34,"Udinese","serie a"),
    ("Yordan Osorio","DEF",32,2,27,"Girona","la liga"),
    ("Nahuel Ferraresi","DEF",32,1,25,"KAA Gent","pro league"),
    ("Mikel Villanueva","DEF",46,1,29,"Querétaro","liga mx"),
    ("Jhon Chancellor","DEF",52,2,35,"Bolívar","liga bolivia"),
    ("Jon Aramburu","DEF",22,1,28,"Real Sociedad","la liga"),
    ("Adrián Martínez","DEF",14,0,25,"Eintracht Frankfurt","bundesliga"),
    ("Yangel Herrera","MID",78,16,27,"Girona","la liga"),
    ("Jefferson Savarino","MID",58,14,30,"Botafogo","brasileirao"),
    ("Darwin Machis","MID",82,22,32,"Udinese","serie a"),
    ("Tomás Rincón","MID",116,6,36,"Deportivo Táchira","liga venezuela"),
    ("Eduard Bello","MID",22,4,25,"Mallorca","la liga"),
    ("Kervin Arriaga","MID",18,2,24,"Lobos BUAP","liga mx"),
    ("Kevin Velasco","MID",16,3,25,"Celta Vigo","la liga"),
    ("Adalberto Peñaranda","FWD",30,6,29,"Mallorca","la liga"),
    ("Salomón Rondón","FWD",102,42,36,"Pachuca","liga mx"),
    ("Fernando Aristeguieta","FWD",36,14,29,"Columbus Crew","mls"),
    ("Jan Hurtado","FWD",14,3,24,"Almería","la liga"),
    ("Bernaldo Quijada","FWD",12,3,26,"Estudiantes de Mérida","liga venezuela"),
    ("Ronald Hernández","DEF",14,0,26,"Stade Rennais","ligue 1"),
    ("Yeferson Soteldo","FWD",40,10,27,"Santos","brasileirao"),
    ("Yohan Cumana","DEF",18,0,27,"Club Bolívar","liga bolivia"),
    ("Cristian Casseres Jr.","MID",16,3,25,"New York Red Bulls","mls"),
],

"Bolivia": [
    ("Carlos Lampe","GK",82,0,37,"LDU Quito","ligapro ecuador"),
    ("Rubén Cordano","GK",12,0,25,"Bolívar","liga bolivia"),
    ("Brayan Viscarra","GK",16,0,30,"The Strongest","liga bolivia"),
    ("Marcelo Suárez","DEF",62,3,33,"Always Ready","liga bolivia"),
    ("Diego Bejarano","DEF",42,1,32,"Always Ready","liga bolivia"),
    ("Sebastián Reyes","DEF",22,0,27,"The Strongest","liga bolivia"),
    ("Erwin Saavedra","DEF",36,1,30,"Bolívar","liga bolivia"),
    ("José Sagredo","DEF",14,0,24,"Club Bolívar","liga bolivia"),
    ("Luis Haquín","DEF",28,1,27,"Club Bolívar","liga bolivia"),
    ("Adrián Jusino","DEF",18,0,25,"Club Nacional","primera division uruguay"),
    ("Ramiro Vaca","MID",72,12,32,"Club Bolívar","liga bolivia"),
    ("Danny Bejarano","MID",52,8,31,"FC Famalicão","primeira liga"),
    ("Jeyson Chura","MID",16,2,24,"Always Ready","liga bolivia"),
    ("Leonel Justiniano","MID",18,3,26,"Bolívar","liga bolivia"),
    ("Fernando Saucedo","MID",36,5,28,"Club Bolívar","liga bolivia"),
    ("Robson Matheus","MID",14,2,25,"Bolívar","liga bolivia"),
    ("Marcelo Martins","FWD",92,38,38,"Coritiba","serie a brasil"),
    ("Bruno Miranda","FWD",46,16,30,"Santos","brasileirao"),
    ("Carmelo Algarañaz","FWD",30,8,29,"Club Bolívar","liga bolivia"),
    ("Juan Arce","FWD",14,3,24,"Oriente Petrolero","liga bolivia"),
    ("Henry Vaca","FWD",12,4,26,"The Strongest","liga bolivia"),
    ("Marcos Bolívar","MID",8,1,22,"Club Bolívar","liga bolivia"),
    ("Gabriel Ávalos","FWD",26,8,30,"Olimpia","primera division"),
    ("Israel Bello","DEF",12,0,26,"Blooming","liga bolivia"),
    ("Pablo Vaca","MID",10,1,23,"Bolívar","liga bolivia"),
    ("Diego Wayar","MID",22,3,28,"Guabirá","liga bolivia"),
],

"Paraguay": [
    ("Antony Silva","GK",82,0,38,"Club Olimpia","primera division"),
    ("Ángel González","GK",16,0,27,"Club Libertad","primera division"),
    ("Rodrigo Muñoz","GK",10,0,28,"Colorado Rapids","mls"),
    ("Junior Alonso","DEF",56,3,30,"Atlético Mineiro","brasileirao"),
    ("Omar Alderete","DEF",42,2,28,"Valencia","la liga"),
    ("Robert Rojas","DEF",52,6,28,"River Plate","liga argentina"),
    ("Alberto Espínola","DEF",22,0,28,"Club Olimpia","primera division"),
    ("Jorge Morel","DEF",16,0,26,"Libertad","primera division"),
    ("Gustavo Velázquez","DEF",22,1,28,"Guadalajara","liga mx"),
    ("Iván Piris","DEF",28,0,30,"Dynamo Moscow","russian premier league"),
    ("Miguel Almirón","MID",76,16,30,"Newcastle United","premier league"),
    ("Óscar Romero","MID",56,8,33,"Independiente","liga argentina"),
    ("Mathías Villasanti","MID",28,3,26,"Fluminense","brasileirao"),
    ("Kaku Romero","MID",52,10,30,"RB Leipzig","bundesliga"),
    ("Sergio Aquino","MID",30,3,28,"Club Olimpia","primera division"),
    ("Braian Samudio","MID",22,3,24,"Club Olimpia","primera division"),
    ("Carlos González","FWD",36,10,30,"Colorado Rapids","mls"),
    ("Antonio Sanabria","FWD",52,16,29,"Torino","serie a"),
    ("Alejandro Romero","FWD",22,6,25,"Santos","brasileirao"),
    ("Ramón Sosa","FWD",26,8,25,"Nottingham Forest","premier league"),
    ("Julio Enciso","FWD",22,6,22,"Brighton","premier league"),
    ("Braxton Ñoño","FWD",8,2,21,"Club Olimpia","primera division"),
    ("Adam Bareiro","FWD",36,12,28,"Club Olimpia","primera division"),
    ("Jorge Recalde","MID",14,2,24,"Club Nacional","primera division uruguay"),
    ("Mathias Villasanti","MID",28,3,26,"Fluminense","brasileirao"),
    ("Gustavo Gómez","DEF",46,3,31,"Palmeiras","brasileirao"),
],

# ═══════════════════════════════════════════════════════════════
# CONCACAF
# ═══════════════════════════════════════════════════════════════
"USA": [
    ("Matt Turner","GK",36,0,31,"Nottingham Forest","premier league"),
    ("Patrick Schulte","GK",8,0,25,"Columbus Crew","mls"),
    ("Ethan Horvath","GK",22,0,30,"Cardiff City","championship"),
    ("Sergino Dest","DEF",46,2,25,"PSV","eredivisie"),
    ("Antonee Robinson","DEF",56,2,28,"Fulham","premier league"),
    ("Miles Robinson","DEF",36,2,28,"FC Cincinnati","mls"),
    ("Walker Zimmerman","DEF",42,4,32,"Nashville SC","mls"),
    ("Chris Richards","DEF",32,1,25,"Crystal Palace","premier league"),
    ("Joe Scally","DEF",22,0,23,"Borussia M'gladbach","bundesliga"),
    ("Caleb Wiley","DEF",12,0,20,"Arsenal","premier league"),
    ("Tyler Adams","MID",56,4,26,"Bournemouth","premier league"),
    ("Weston McKennie","MID",62,12,27,"Juventus","serie a"),
    ("Yunus Musah","MID",42,3,23,"AC Milan","serie a"),
    ("Gio Reyna","MID",32,7,23,"Nottingham Forest","premier league"),
    ("Brenden Aaronson","MID",36,8,24,"Leeds United","championship"),
    ("Luca de la Torre","MID",22,3,27,"Celta Vigo","la liga"),
    ("Malik Tillman","MID",22,4,23,"PSV","eredivisie"),
    ("Christian Pulisic","FWD",72,28,27,"AC Milan","serie a"),
    ("Ricardo Pepi","FWD",26,12,23,"PSV","eredivisie"),
    ("Folarin Balogun","FWD",16,6,24,"Monaco","ligue 1"),
    ("Tim Weah","FWD",36,6,25,"Juventus","serie a"),
    ("Josh Sargent","FWD",32,10,26,"Norwich City","championship"),
    ("Cade Cowell","FWD",16,4,22,"Guadelupe FC","liga mx"),
    ("Paxten Aaronson","MID",12,2,22,"Eintracht Frankfurt","bundesliga"),
    ("Emmanuel Forbes","DEF",14,0,23,"Washington Commanders","mls"),
    ("Joe Pellegrino","DEF",8,0,22,"LA Galaxy","mls"),
],

"Mexico": [
    ("Guillermo Ochoa","GK",146,0,41,"América","liga mx"),
    ("Carlos Acevedo","GK",16,0,29,"Santos Laguna","liga mx"),
    ("Rodolfo Cota","GK",26,0,36,"Club León","liga mx"),
    ("Jorge Sánchez","DEF",46,1,27,"Porto","primeira liga"),
    ("Jesús Gallardo","DEF",66,3,31,"Monterrey","liga mx"),
    ("César Montes","DEF",62,4,29,"Espanyol","la liga"),
    ("Johan Vásquez","DEF",36,1,27,"Cremonese","serie b"),
    ("Julián Araujo","DEF",22,0,24,"Bournemouth","premier league"),
    ("Gerardo Arteaga","DEF",32,1,27,"Getafe","la liga"),
    ("Israel Reyes","DEF",14,0,24,"Cruz Azul","liga mx"),
    ("Edson Álvarez","MID",72,12,28,"West Ham","premier league"),
    ("Carlos Rodríguez","MID",42,4,29,"Cruz Azul","liga mx"),
    ("Orbelín Pineda","MID",62,14,29,"AEK Athens","super league greece"),
    ("Luis Chávez","MID",32,8,30,"Dinamo Moscow","russian premier league"),
    ("Érick Gutiérrez","MID",56,6,31,"PSV","eredivisie"),
    ("Fernando Beltrán","MID",22,3,26,"Guadalajara","liga mx"),
    ("Roberto Alvarado","MID",36,8,28,"Cruz Azul","liga mx"),
    ("Raúl Jiménez","FWD",116,42,35,"Fulham","premier league"),
    ("Hirving Lozano","FWD",86,32,31,"San Diego FC","mls"),
    ("Henry Martín","FWD",42,12,33,"América","liga mx"),
    ("Santiago Giménez","FWD",22,12,24,"Feyenoord","eredivisie"),
    ("Alexis Vega","FWD",36,8,28,"Guadalajara","liga mx"),
    ("Chucky Lozano","FWD",86,32,31,"San Diego FC","mls"),
    ("Fidel Ambriz","MID",12,1,23,"Necaxa","liga mx"),
    ("Alan Cervantes","MID",8,1,22,"Pumas","liga mx"),
    ("Omar Govea","MID",22,2,28,"Zaragoza","segunda division"),
],

"Canada": [
    ("Maxime Crépeau","GK",36,0,31,"LA Galaxy","mls"),
    ("Milan Borjan","GK",66,0,36,"Red Star Belgrade","superliga"),
    ("Dayne St. Clair","GK",16,0,28,"Minnesota United","mls"),
    ("Alphonso Davies","DEF",62,14,26,"Bayern Munich","bundesliga"),
    ("Alistair Johnston","DEF",32,1,26,"Celtic","scottish premiership"),
    ("Kamal Miller","DEF",42,2,28,"Colorado Rapids","mls"),
    ("Richie Laryea","DEF",36,1,29,"Nottingham Forest","premier league"),
    ("Scott Kennedy","DEF",22,1,28,"Fluminense","brasileirao"),
    ("Doneil Henry","DEF",46,2,33,"Vancouver Whitecaps","mls"),
    ("Derek Cornelius","DEF",26,1,28,"Panathinaikos","super league greece"),
    ("Tajon Buchanan","MID",42,5,26,"Villarreal","la liga"),
    ("Jonathan Osorio","MID",56,8,33,"Toronto FC","mls"),
    ("Stephen Eustáquio","MID",32,3,28,"Porto","primeira liga"),
    ("Liam Millar","MID",26,3,27,"Stade Reims","ligue 1"),
    ("Ismaël Koné","MID",22,2,23,"Marseille","ligue 1"),
    ("Samuel Piette","MID",36,1,30,"CF Montréal","mls"),
    ("Mark-Anthony Kaye","MID",28,2,30,"Toronto FC","mls"),
    ("Jonathan David","FWD",52,26,25,"Lille","ligue 1"),
    ("Cyle Larin","FWD",66,32,30,"Mallorca","la liga"),
    ("Theo Corbeanu","FWD",16,3,24,"Sheffield Wednesday","championship"),
    ("Jacen Russell-Rowe","FWD",12,4,23,"Columbus Crew","mls"),
    ("Dénis Bouanga","FWD",18,6,29,"Los Angeles FC","mls"),
    ("Charles-Andreas Brym","FWD",14,3,27,"Cska Sofia","superliga"),
    ("Jacob Shaffelburg","FWD",12,2,25,"Nashville SC","mls"),
    ("Jayden Nelson","FWD",10,2,23,"FC Cincinnati","mls"),
    ("Ali Ahmed","DEF",8,0,22,"Atlanta United","mls"),
],

"Jamaica": [
    ("Andre Blake","GK",76,0,34,"Philadelphia Union","mls"),
    ("Dillon Barnes","GK",16,0,30,"QPR","championship"),
    ("Jahmali Waite","GK",8,0,26,"Wigan Athletic","league one"),
    ("Damion Lowe","DEF",56,2,30,"Seattle Sounders","mls"),
    ("Ethan Pinnock","DEF",32,1,31,"Brentford","premier league"),
    ("Joel Latibeaudiere","DEF",22,0,25,"Coventry City","championship"),
    ("Greg Leigh","DEF",16,0,31,"Aberdeen","scottish premiership"),
    ("Keamari Bailey","DEF",12,0,24,"Morecambe","league one"),
    ("Lamar Walker","MID",18,2,27,"Tampa Bay Rowdies","mls"),
    ("Ravel Morrison","MID",22,4,32,"Watford","championship"),
    ("Demarai Gray","MID",36,6,29,"Al-Ettifaq","saudi pro league"),
    ("Kasey Palmer","MID",22,4,28,"Coventry City","championship"),
    ("Bobby Reid","MID",26,6,31,"QPR","championship"),
    ("Daniel Johnson","MID",32,6,33,"Preston North End","championship"),
    ("Ramone Morrison","MID",12,2,26,"Hellas Verona","serie a"),
    ("Omari Palmer","MID",10,2,23,"Nashville SC","mls"),
    ("Leon Bailey","FWD",46,16,29,"Aston Villa","premier league"),
    ("Michail Antonio","FWD",32,12,34,"Nottingham Forest","premier league"),
    ("Shamar Nicholson","FWD",26,10,27,"Standard Liège","pro league"),
    ("Cory Burke","FWD",26,8,30,"Philadelphia Union","mls"),
    ("Theo Archibald","FWD",8,2,26,"Barrow","league one"),
    ("Bobby Decordova-Reid","FWD",36,8,32,"Leeds United","championship"),
    ("Romario Williams","FWD",14,4,27,"Colorado Rapids","mls"),
    ("Javain Brown","DEF",22,0,26,"Vancouver Whitecaps","mls"),
    ("Amari'i Bell","DEF",18,1,30,"Luton Town","championship"),
    ("Deshane Beckford","MID",10,2,24,"Charlotte FC","mls"),
],

"Honduras": [
    ("Luis López","GK",56,0,34,"Marathón","liga honduras"),
    ("Edrick Menjívar","GK",12,0,26,"FC Dallas","mls"),
    ("Harold Fonseca","GK",8,0,28,"Real España","liga honduras"),
    ("Denil Maldonado","DEF",26,1,26,"Club Olimpia","liga honduras"),
    ("Marcelo Pereira","DEF",28,0,29,"Olimpia","liga honduras"),
    ("Bryan Moya","DEF",22,0,27,"Club Olimpia","liga honduras"),
    ("Nerlin Membreño","DEF",22,1,29,"Real Moras","liga honduras"),
    ("Diego Rodríguez","DEF",16,0,25,"CD Marathón","liga honduras"),
    ("Jonathan Paz","DEF",18,0,27,"Marathón","liga honduras"),
    ("Brayan Meza","DEF",8,0,23,"Real España","liga honduras"),
    ("Alberth Elis","MID",56,16,30,"Bordeaux","ligue 2 fr"),
    ("Kervin Arriaga","MID",26,4,26,"Seattle Sounders","mls"),
    ("Rigoberto Rivas","MID",26,8,27,"Nottingham Forest","premier league"),
    ("Jorge Álvarez","MID",22,2,28,"CD Olimpia","liga honduras"),
    ("Andy Nájer","MID",22,4,27,"FC Juárez","liga mx"),
    ("Bryan Acosta","MID",42,5,32,"Colorado Rapids","mls"),
    ("Ever Alvarado","MID",26,2,29,"Club Olimpia","liga honduras"),
    ("Antony Lozano","FWD",56,22,32,"Cádiz","segunda division"),
    ("Romell Quioto","FWD",56,12,33,"Al-Qadsiah","saudi pro league"),
    ("Jerry Bengtson","FWD",42,14,31,"Olimpia","liga honduras"),
    ("Luis Palma","FWD",16,4,23,"Celtic","scottish premiership"),
    ("Julián Arboleda","FWD",12,3,24,"CD FAS","liga honduras"),
    ("Eddie Hernández","FWD",16,6,27,"Xelajú","liga honduras"),
    ("Michaell Chirinos","FWD",14,4,28,"Olimpia","liga honduras"),
    ("Jonathan Rubio","FWD",22,6,30,"Olimpia","liga honduras"),
    ("Brandell Salinas","MID",8,1,22,"Real España","liga honduras"),
],

"Panama": [
    ("Luis Mejía","GK",46,0,30,"Independiente Medellín","liga betplay colombia"),
    ("Orlando Mosquera","GK",12,0,28,"Club Atlético Independiente","liga argentina"),
    ("Jaime Penedo","GK",110,0,43,"Alianza FC","liga panama"),
    ("Eric Davis","DEF",72,6,35,"New England Revolution","mls"),
    ("Harold Cummings","DEF",72,4,33,"Santos Laguna","liga mx"),
    ("Fidel Escobar","DEF",56,2,30,"Santos Laguna","liga mx"),
    ("Michael Amir Murillo","DEF",52,1,30,"Montpellier","ligue 1"),
    ("Roderick Miller","DEF",28,1,28,"Austin FC","mls"),
    ("César Blackman","DEF",14,0,25,"Tauro FC","liga panama"),
    ("Jorge Gutiérrez","DEF",22,1,29,"Club Atlético Nacional","liga betplay colombia"),
    ("Aníbal Godoy","MID",92,6,36,"Nashville SC","mls"),
    ("Adalberto Carrasquilla","MID",52,12,28,"Wigan Athletic","championship"),
    ("Alberto Quintero","MID",76,6,36,"Universitario","liga peru"),
    ("Edgar Bárcenas","MID",56,10,31,"Leganés","la liga"),
    ("Abdiel Ayarza","MID",22,3,25,"Vitória","brasileirao"),
    ("Cristian Martínez","MID",14,2,24,"Tauro FC","liga panama"),
    ("Rodolfo Austin","MID",56,6,36,"Club Bolívar","liga bolivia"),
    ("Rolando Blackburn","FWD",56,16,33,"Nashville SC","mls"),
    ("Cecilio Waterman","FWD",46,12,30,"Orlando City","mls"),
    ("Ismael Díaz","FWD",26,8,26,"Guadalajara","liga mx"),
    ("Édgar Bárcenas","FWD",8,3,31,"Leganés","la liga"),
    ("José Fajardo","FWD",36,10,29,"FC Dallas","mls"),
    ("Éric Ávila","FWD",12,3,24,"Universitario","liga peru"),
    ("Alberto Quintero","MID",76,6,36,"Universitario","liga peru"),
    ("Álex Martínez","DEF",8,0,22,"Tauro FC","liga panama"),
    ("Jovani Welch","MID",12,2,25,"Tampa Bay Rowdies","mls"),
],

"Costa Rica": [
    ("Keylor Navas","GK",152,0,40,"Olimpia","liga honduras"),
    ("Leonel Moreira","GK",16,0,30,"Alajuelense","liga costa rica"),
    ("Esteban Alvarado","GK",36,0,38,"Herediano","liga costa rica"),
    ("Bryan Oviedo","DEF",76,6,36,"Real Salt Lake","mls"),
    ("Ronald Matarrita","DEF",72,3,30,"FC Cincinnati","mls"),
    ("Francisco Calvo","DEF",76,5,34,"Konyaspor","super lig"),
    ("Juan Pablo Vargas","DEF",46,2,30,"Millwall","championship"),
    ("Carlos Martínez","DEF",22,0,27,"Herediano","liga costa rica"),
    ("Kendall Waston","DEF",66,5,37,"Saprissa","liga costa rica"),
    ("Keysher Fuller","DEF",36,3,29,"Herediano","liga costa rica"),
    ("Yeltsin Tejeda","MID",82,6,32,"Club Puebla","liga mx"),
    ("Celso Borges","MID",96,12,36,"Alajuelense","liga costa rica"),
    ("Johan Venegas","MID",66,16,34,"Alajuelense","liga costa rica"),
    ("Anthony Contreras","MID",22,4,26,"Roda JC","eerste"),
    ("Gerson Torres","MID",28,5,28,"San Jose Earthquakes","mls"),
    ("Daniel Chacón","MID",16,2,25,"FC Juárez","liga mx"),
    ("Jewison Bennette","MID",18,4,21,"Sunderland","championship"),
    ("Joel Campbell","FWD",116,30,33,"Monterrey","liga mx"),
    ("Ariel Lassiter","FWD",42,10,29,"San Jose Earthquakes","mls"),
    ("Andy Polo","FWD",36,6,31,"Orlando City","mls"),
    ("Álvaro Zamora","FWD",22,6,26,"Herediano","liga costa rica"),
    ("Brandon Aguilera","MID",12,2,22,"Nottingham Forest","premier league"),
    ("Ian Lawrence","MID",8,1,21,"Saprissa","liga costa rica"),
    ("Bayron Mora","FWD",12,3,24,"Saprissa","liga costa rica"),
    ("Orlando Galo","MID",22,3,26,"Alajuelense","liga costa rica"),
    ("Justin Campos","MID",6,1,20,"Saprissa","liga costa rica"),
],

# ═══════════════════════════════════════════════════════════════
# CAF (Africa)
# ═══════════════════════════════════════════════════════════════
"Morocco": [
    ("Yassine Bounou","GK",56,0,34,"Al-Hilal","saudi pro league"),
    ("Munir Mohamedi","GK",28,0,36,"Nantes","ligue 1"),
    ("Anas Zniti","GK",12,0,32,"Wydad AC","botola pro"),
    ("Achraf Hakimi","DEF",82,5,28,"Paris Saint-Germain","ligue 1"),
    ("Noussair Mazraoui","DEF",56,3,28,"Manchester United","premier league"),
    ("Nayef Aguerd","DEF",52,2,29,"West Ham","premier league"),
    ("Romain Saïss","DEF",90,6,36,"Besiktas","super lig"),
    ("Samy Mmaee","DEF",22,1,29,"Ferencváros","otp bank liga"),
    ("Yahia Attiyat Allah","DEF",32,1,31,"Wydad AC","botola pro"),
    ("Adam Masina","DEF",36,1,29,"Watford","championship"),
    ("Sofyan Amrabat","MID",56,3,30,"Manchester United","premier league"),
    ("Azzedine Ounahi","MID",32,3,26,"Marseille","ligue 1"),
    ("Selim Amallah","MID",32,4,30,"Standard Liège","pro league"),
    ("Abde Ezzalzouli","MID",22,5,25,"Osasuna","la liga"),
    ("Bilal El Khannous","MID",16,2,20,"Genk","pro league"),
    ("Ilias Chair","MID",22,5,28,"Queens Park Rangers","championship"),
    ("Nasser Mandesh","MID",8,1,22,"Wydad AC","botola pro"),
    ("Hakim Ziyech","FWD",76,22,33,"Galatasaray","super lig"),
    ("Youssef En-Nesyri","FWD",62,26,29,"Fenerbahçe","super lig"),
    ("Abderrazak Hamdallah","FWD",26,8,35,"Al-Ittihad","saudi pro league"),
    ("Zakaria Aboukhlal","FWD",26,8,25,"Toulouse","ligue 1"),
    ("Ayoub El Kaabi","FWD",22,10,28,"Olympiacos","super league greece"),
    ("Sofiane Boufal","FWD",52,10,32,"Southampton","championship"),
    ("Youssef Aït Bennasser","MID",28,3,30,"Nantes","ligue 1"),
    ("Amine Harit","MID",28,5,28,"Marseille","ligue 1"),
    ("Ibrahim Salah","FWD",8,2,24,"Wydad AC","botola pro"),
],

"Senegal": [
    ("Édouard Mendy","GK",46,0,34,"Al-Ahli","saudi pro league"),
    ("Seny Dieng","GK",16,0,29,"Middlesbrough","championship"),
    ("Alfred Gomis","GK",16,0,31,"Rennes","ligue 1"),
    ("Kalidou Koulibaly","DEF",76,5,35,"Al-Hilal","saudi pro league"),
    ("Youssouf Sabaly","DEF",42,2,32,"Real Betis","la liga"),
    ("Pape Abou Cissé","DEF",36,2,30,"Olympiacos","super league greece"),
    ("Formose Mendy","DEF",22,0,27,"Montpellier","ligue 1"),
    ("Ismail Jakobs","DEF",16,1,25,"Monaco","ligue 1"),
    ("Abdou Diallo","DEF",36,2,28,"Al-Rayyan","qsl"),
    ("Nicolas Jackson","DEF",2,0,24,"Chelsea","premier league"),
    ("Idrissa Gueye","MID",102,6,37,"Everton","premier league"),
    ("Nampalys Mendy","MID",26,1,32,"Nice","ligue 1"),
    ("Pape Matar Sarr","MID",32,5,23,"Tottenham Hotspur","premier league"),
    ("Habib Diallo","MID",36,16,29,"Getafe","la liga"),
    ("Lamine Camara","MID",22,4,23,"Monaco","ligue 1"),
    ("Krepin Diatta","MID",26,4,25,"Monaco","ligue 1"),
    ("Mamadou Loum","MID",18,2,28,"Reading","championship"),
    ("Sadio Mané","FWD",102,42,34,"Al-Nassr","saudi pro league"),
    ("Nicolas Jackson","FWD",26,6,24,"Chelsea","premier league"),
    ("Ismaïla Sarr","FWD",52,16,27,"Crystal Palace","premier league"),
    ("Boulaye Dia","FWD",32,10,28,"Lazio","serie a"),
    ("Cheikhou Kouyaté","MID",74,4,35,"Nottingham Forest","premier league"),
    ("Iliman Ndiaye","FWD",22,6,25,"Everton","premier league"),
    ("Abdallah Sima","FWD",16,4,23,"Brentford","premier league"),
    ("Cheikh Niasse","FWD",8,2,22,"Metz","ligue 2 fr"),
    ("Moussa Niakhaté","DEF",22,1,28,"Nottingham Forest","premier league"),
],

"Nigeria": [
    ("Maduka Okoye","GK",26,0,25,"Udinese","serie a"),
    ("Stanley Nwabali","GK",12,0,28,"Chippa United","psl"),
    ("Adebayo Adeleye","GK",6,0,24,"Rangers","scottish premiership"),
    ("William Troost-Ekong","DEF",86,5,32,"Bari","serie b"),
    ("Calvin Bassey","DEF",32,1,25,"Fulham","premier league"),
    ("Ola Aina","DEF",46,2,28,"Nottingham Forest","premier league"),
    ("Kenneth Omeruo","DEF",62,3,32,"Leganés","la liga"),
    ("Semi Ajayi","DEF",32,2,31,"West Brom","championship"),
    ("Bright Osayi-Samuel","DEF",36,3,27,"Fenerbahçe","super lig"),
    ("Zaidu Sanusi","DEF",26,1,27,"Porto","primeira liga"),
    ("Wilfried Ndidi","MID",62,4,28,"Leicester City","premier league"),
    ("Alex Iwobi","MID",66,12,29,"Fulham","premier league"),
    ("Frank Onyeka","MID",26,2,27,"Brentford","premier league"),
    ("Fisayo Dele-Bashiru","MID",16,3,25,"Lazio","serie a"),
    ("Raphael Onyedika","MID",12,1,24,"Club Brugge","pro league"),
    ("Joe Aribo","MID",36,5,28,"Southampton","championship"),
    ("Emeka Eze","MID",8,1,24,"Crystal Palace","premier league"),
    ("Victor Osimhen","FWD",56,22,28,"Galatasaray","super lig"),
    ("Samuel Chukwueze","FWD",42,12,27,"AC Milan","serie a"),
    ("Kelechi Iheanacho","FWD",52,16,30,"Sevilla","la liga"),
    ("Taiwo Awoniyi","FWD",22,6,27,"Nottingham Forest","premier league"),
    ("Emmanuel Dennis","FWD",22,6,27,"Trabzonspor","super lig"),
    ("Cyriel Dessers","FWD",18,5,30,"Rangers","scottish premiership"),
    ("Terem Moffi","FWD",22,8,26,"Nice","ligue 1"),
    ("Paul Onuachu","FWD",32,16,30,"Southampton","premier league"),
    ("Olisa Ndah","DEF",8,0,23,"Granada","la liga"),
],

"Ivory Coast": [
    ("Yahia Fofana","GK",36,0,30,"Leicester City","premier league"),
    ("Badra Ali Sangaré","GK",22,0,33,"Zamalek","egypt prem"),
    ("Simon Adingra","FWD",26,6,23,"Brighton","premier league"),
    ("Eric Bailly","DEF",46,1,30,"Villarreal","la liga"),
    ("Serge Aurier","DEF",76,4,33,"Villarreal","la liga"),
    ("Ghislain Konan","DEF",26,0,29,"Montpellier","ligue 1"),
    ("Odilon Kossounou","DEF",26,1,25,"Bayer Leverkusen","bundesliga"),
    ("Willy Boly","DEF",28,2,33,"Nottingham Forest","premier league"),
    ("Wilfried Kanon","DEF",36,2,32,"Al-Qadsiah","saudi pro league"),
    ("Hamidou Traoré","DEF",8,0,25,"Stade Rennais","ligue 1"),
    ("Franck Kessié","MID",76,22,30,"Al-Ahli","saudi pro league"),
    ("Seko Fofana","MID",46,8,30,"Al-Qadsiah","saudi pro league"),
    ("Youssouf Fofana","MID",36,6,26,"AC Milan","serie a"),
    ("Jean-Michaël Seri","MID",52,4,32,"Nice","ligue 1"),
    ("Ibrahim Sangaré","MID",28,3,26,"Nottingham Forest","premier league"),
    ("Mory Koné","MID",12,1,22,"OGC Nice","ligue 1"),
    ("Jean Eloi Boyomo","DEF",8,0,23,"Stade Rennais","ligue 1"),
    ("Sébastien Haller","FWD",56,18,31,"Borussia Dortmund","bundesliga"),
    ("Wilfried Zaha","FWD",68,7,33,"Galatasaray","super lig"),
    ("Jérémie Boga","FWD",22,5,28,"Nice","ligue 1"),
    ("Maxwell Cornet","FWD",46,10,28,"Nottingham Forest","premier league"),
    ("Oumar Diakité","FWD",12,3,23,"Stade Rennais","ligue 1"),
    ("Josué Gnagnon","DEF",22,0,28,"Stade Rennais","ligue 1"),
    ("Steeve Yago","DEF",16,0,30,"Toulouse","ligue 1"),
    ("Adingra Simon","FWD",26,6,23,"Brighton","premier league"),
    ("Jonathan Bamba","FWD",22,5,29,"Cosenza","serie b"),
],

"Egypt": [
    ("Mohamed El-Shenawy","GK",82,0,36,"Al-Ahly","egypt prem"),
    ("Mohamed Abou Gabal","GK",26,0,32,"Zamalek","egypt prem"),
    ("Amr Al-Sulaya","GK",10,0,29,"Pyramids FC","egypt prem"),
    ("Ahmed Hegazi","DEF",76,6,34,"Al-Ittihad","saudi pro league"),
    ("Omar Kamal","DEF",16,0,26,"Pyramids FC","egypt prem"),
    ("Ayman Ashraf","DEF",26,1,30,"Al-Ahly","egypt prem"),
    ("Mohamed Hany","DEF",32,1,28,"Pyramids FC","egypt prem"),
    ("Akram Tawfik","DEF",22,0,27,"Zamalek","egypt prem"),
    ("Hamdi Fathi","DEF",26,1,27,"Brest","ligue 1"),
    ("Mahmoud El Wesh","DEF",32,2,31,"Zamalek","egypt prem"),
    ("Tarek Hamed","MID",46,2,36,"Al-Ahly","egypt prem"),
    ("Emam Ashour","MID",26,3,28,"Al-Ahly","egypt prem"),
    ("Ibrahim Adel","MID",22,5,26,"Atletico Madrid","la liga"),
    ("Zizo Trezeguet","MID",22,4,26,"Atletico Madrid","la liga"),
    ("Amr El Sulaya","MID",16,2,29,"Pyramids FC","egypt prem"),
    ("Ahmed Sayed Zizo","MID",22,5,27,"Al-Ahly","egypt prem"),
    ("Mahmoud Trezeguet","MID",66,16,32,"Trabzonspor","super lig"),
    ("Mohamed Salah","FWD",102,58,34,"Liverpool","premier league"),
    ("Mostafa Mohamed","FWD",42,16,28,"Galatasaray","super lig"),
    ("Omar Marmoush","FWD",28,12,27,"Manchester City","premier league"),
    ("Karim Saleh","FWD",14,4,26,"Al-Ahly","egypt prem"),
    ("Ahmed Fattouh","FWD",12,3,24,"Pyramids FC","egypt prem"),
    ("Ramadan Sobhi","MID",42,6,28,"Pyramids FC","egypt prem"),
    ("Omar Abdel-Hamid","DEF",18,1,23,"Al-Ahly","egypt prem"),
    ("Akram Tawfik","DEF",22,0,27,"Zamalek","egypt prem"),
    ("Trézéguet Kahraba","FWD",36,8,30,"Sharjah","uae pro league"),
],

"Cameroon": [
    ("André Onana","GK",56,0,30,"Manchester United","premier league"),
    ("Devis Epassy","GK",16,0,29,"Abha Club","saudi pro league"),
    ("Simon Omossola","GK",6,0,26,"Paris FC","ligue 2 fr"),
    ("Collins Fai","DEF",66,2,34,"Bayer Leverkusen","bundesliga"),
    ("Jean-Charles Castelletto","DEF",36,2,31,"Nantes","ligue 1"),
    ("Enzo Ebosse","DEF",22,0,27,"Udinese","serie a"),
    ("Ambroise Oyongo","DEF",66,2,34,"Montpellier","ligue 1"),
    ("Nouhou Tolo","DEF",36,0,29,"Seattle Sounders","mls"),
    ("Harold Moukoudi","DEF",12,0,29,"Montpellier","ligue 1"),
    ("Christopher Wooh","DEF",16,1,24,"Rennes","ligue 1"),
    ("André-Frank Zambo Anguissa","MID",56,6,30,"Napoli","serie a"),
    ("Samuel Gouet","MID",36,3,28,"Club Brugge","pro league"),
    ("Martin Hongla","MID",32,2,28,"Hellas Verona","serie a"),
    ("Nicolas Moumi Ngamaleu","MID",42,6,31,"Bayer Leverkusen","bundesliga"),
    ("Gaël Ondoua","MID",22,2,29,"Hannover 96","bundesliga 2"),
    ("James Lea Siliki","MID",22,2,29,"Stade Rennais","ligue 1"),
    ("Gael Ondoua","MID",22,2,29,"Hannover 96","bundesliga 2"),
    ("Vincent Aboubakar","FWD",102,36,33,"Al-Nassr","saudi pro league"),
    ("Karl Toko Ekambi","FWD",76,26,32,"Rennes","ligue 1"),
    ("Bryan Mbeumo","FWD",26,8,26,"Manchester United","premier league"),
    ("Christian Bassogog","FWD",46,12,30,"Shanghai Shenhua","chinese super league"),
    ("Stéphan Bahoken","FWD",22,6,31,"Angers","ligue 2 fr"),
    ("Arnaud Djoum","MID",28,4,35,"Hearts","scottish premiership"),
    ("Clinton Njie","FWD",36,8,32,"Lyon","ligue 1"),
    ("Léandre Tawamba","FWD",14,4,29,"Supersport United","psl"),
    ("Olivier Ntcham","MID",30,3,30,"Swansea City","championship"),
],

"Ghana": [
    ("Lawrence Ati-Zigi","GK",36,0,28,"Nantes","ligue 1"),
    ("Joe Wollacott","GK",22,0,28,"Charlton Athletic","league one"),
    ("Abdul Manaf Nurudeen","GK",8,0,24,"Eupen","pro league"),
    ("Tariq Lamptey","DEF",26,1,25,"Brighton","premier league"),
    ("Alexander Djiku","DEF",36,2,30,"Fenerbahçe","super lig"),
    ("Daniel Amartey","DEF",42,2,30,"Leicester City","premier league"),
    ("Gideon Mensah","DEF",22,0,26,"Auxerre","ligue 1"),
    ("Alidu Seidu","DEF",22,0,25,"RC Lens","ligue 1"),
    ("Edmund Addo","DEF",16,0,26,"Sheriff Tiraspol","superliga"),
    ("Abdul Mumin","DEF",14,0,26,"Rayo Vallecano","la liga"),
    ("Thomas Partey","MID",56,10,32,"Arsenal","premier league"),
    ("Salis Abdul Samed","MID",22,2,25,"RC Lens","ligue 1"),
    ("Elisha Owusu","MID",16,1,26,"Gent","pro league"),
    ("Mohammed Kudus","MID",36,10,25,"West Ham","premier league"),
    ("Dede Ayew","MID",112,22,36,"Le Havre","ligue 1"),
    ("Daniel Kofi Kyereh","MID",26,4,28,"Freiburg","bundesliga"),
    ("Iddrisu Baba","MID",22,1,28,"Mallorca","la liga"),
    ("Iñaki Williams","FWD",22,6,32,"Athletic Bilbao","la liga"),
    ("Jordan Ayew","FWD",88,24,33,"Leicester City","premier league"),
    ("Antoine Semenyo","FWD",22,6,25,"Bournemouth","premier league"),
    ("Kamaldeen Sulemana","FWD",26,8,24,"Rennes","ligue 1"),
    ("Ernest Nuamah","FWD",12,3,22,"Olympique Lyon","ligue 1"),
    ("Richmond Boakye","FWD",36,12,31,"PAOK","super league greece"),
    ("Samuel Owusu","FWD",14,3,28,"Al Fayha","saudi pro league"),
    ("Joel Fameyeh","FWD",16,4,27,"Maccabi Tel Aviv","ligat"),
    ("Kwabena Owusu","MID",14,3,27,"Lugo","segunda division"),
],

"DR Congo": [
    ("Joël Kiassumbua","GK",36,0,35,"Belenenses","portuguesa liga"),
    ("Hervé Kanda","GK",12,0,28,"Sanga Balende","liga nacional"),
    ("Ibrahim Mounkoro","GK",8,0,26,"AS Vita Club","liga nacional"),
    ("Arthur Masuaku","DEF",42,2,32,"Besiktas","super lig"),
    ("Chancel Mbemba","DEF",56,3,31,"Marseille","ligue 1"),
    ("Marcel Lewis","DEF",16,0,25,"Coventry City","championship"),
    ("Fiston Mayele","FWD",10,3,26,"Yeni Malatyaspor","super lig"),
    ("Christian Luyindama","DEF",28,1,30,"Galatasaray","super lig"),
    ("Ngonda Muzinga","DEF",12,0,27,"Charleroi","pro league"),
    ("Junior Malanda","DEF",8,0,24,"FC Metz","ligue 2 fr"),
    ("Gaël Kakuta","MID",26,6,34,"Amiens SC","ligue 2 fr"),
    ("Paul-José M'Poku","MID",52,12,32,"Standard Liège","pro league"),
    ("Silas Wamangituka","MID",22,4,28,"Wolfsburg","bundesliga"),
    ("Cédric Bakambu","MID",56,22,34,"Besiktas","super lig"),
    ("Junior Dina Ebimbe","MID",16,2,24,"Eintracht Frankfurt","bundesliga"),
    ("Elia Meschack","MID",12,2,24,"AS Vita Club","liga nacional"),
    ("Nathan Munkonda","MID",8,1,22,"Gent","pro league"),
    ("Yoane Wissa","FWD",32,12,28,"Brentford","premier league"),
    ("Théo Bongonda","FWD",32,8,30,"Kasımpaşa","super lig"),
    ("Jonathan Bolingi","FWD",26,8,31,"Beerschot","pro league"),
    ("Bokadi Bianda","DEF",16,0,27,"Standard Liège","pro league"),
    ("Elia Meschack","MID",12,2,24,"AS Vita Club","liga nacional"),
    ("Moïse Lilepo","FWD",12,3,25,"FC Metz","ligue 2 fr"),
    ("Hérita Ilunga","DEF",46,2,42,"retired","ligue 1"),
    ("Guy Mbenza","FWD",12,3,28,"Huddersfield","championship"),
    ("Barel Mouko","MID",8,1,22,"Al Ahly","egypt prem"),
],

"South Africa": [
    ("Ronwen Williams","GK",56,0,34,"Mamelodi Sundowns","psl"),
    ("Veli Mothwa","GK",12,0,31,"AmaZulu","psl"),
    ("Bruce Bvuma","GK",8,0,29,"Kaizer Chiefs","psl"),
    ("Rushine De Reuck","DEF",26,1,30,"Mamelodi Sundowns","psl"),
    ("Sifiso Hlanti","DEF",36,1,34,"Kaizer Chiefs","psl"),
    ("Teboho Mokoena","DEF",32,3,27,"Mamelodi Sundowns","psl"),
    ("Khuliso Mudau","DEF",22,0,26,"Mamelodi Sundowns","psl"),
    ("Terrence Mashego","DEF",22,0,30,"Cape Town City","psl"),
    ("Siyanda Xulu","DEF",26,0,32,"Maccabi Haifa","ligat"),
    ("Mothobi Mvala","MID",22,1,28,"Mamelodi Sundowns","psl"),
    ("Themba Zwane","MID",36,8,33,"Mamelodi Sundowns","psl"),
    ("Bongani Zungu","MID",46,5,32,"Rangers","scottish premiership"),
    ("Sipho Mbule","MID",22,3,28,"Kaizer Chiefs","psl"),
    ("Teboho Mokoena","MID",32,3,27,"Mamelodi Sundowns","psl"),
    ("Yusuf Maart","MID",22,3,28,"Kaizer Chiefs","psl"),
    ("Evidence Makgopa","FWD",22,8,26,"Kaizer Chiefs","psl"),
    ("Percy Tau","FWD",56,14,32,"Al-Ahly","egypt prem"),
    ("Lyle Foster","FWD",22,8,26,"Wigan Athletic","championship"),
    ("Elias Mokwana","FWD",12,3,25,"Mamelodi Sundowns","psl"),
    ("Fagrie Lakay","FWD",16,4,30,"Cape Town City","psl"),
    ("Lebogang Manyama","MID",26,6,32,"Kaizer Chiefs","psl"),
    ("Nkosinathi Sibisi","DEF",18,1,29,"Orlando Pirates","psl"),
    ("Innocent Maela","DEF",22,0,32,"Orlando Pirates","psl"),
    ("Keagan Dolly","FWD",32,8,32,"Mamelodi Sundowns","psl"),
    ("Erasmus","FWD",8,2,24,"Sundowns","psl"),
    ("Happy Mashiane","FWD",12,3,25,"Mamelodi Sundowns","psl"),
],

"Algeria": [
    ("Raïs M'Bolhi","GK",82,0,36,"Al-Ettifaq","saudi pro league"),
    ("Alexandre Oukidja","GK",12,0,36,"Metz","ligue 2 fr"),
    ("Farhat Moumen","GK",8,0,26,"Paradou AC","ligue pro"),
    ("Ramy Bensebaini","DEF",56,12,30,"Borussia Dortmund","bundesliga"),
    ("Aïssa Mandi","DEF",66,4,33,"Villarreal","la liga"),
    ("Djamel Benlamri","DEF",46,2,35,"Al-Hilal","saudi pro league"),
    ("Lyndon Dykes","DEF",6,0,29,"QPR","championship"),
    ("Hossam Ould Ali","DEF",22,0,27,"Belouizdad","ligue pro"),
    ("Dario Benítez","DEF",8,0,25,"Club Olimpia","primera division"),
    ("Youcef Atal","DEF",36,5,28,"Nice","ligue 1"),
    ("Ismaël Bennacer","MID",52,5,28,"AC Milan","serie a"),
    ("Sofiane Feghouli","MID",92,22,36,"Valencia","la liga"),
    ("Nabil Bentaleb","MID",46,5,31,"LOSC Lille","ligue 1"),
    ("Youcef Belaïli","MID",52,12,32,"Al-Qadsiah","saudi pro league"),
    ("Haris Belkebla","MID",28,3,28,"Stade de Reims","ligue 1"),
    ("Anis Ben Slimane","MID",16,3,25,"Brighton","premier league"),
    ("Mehdi Chahiri","MID",12,2,25,"Belouizdad","ligue pro"),
    ("Riyad Mahrez","FWD",102,32,35,"Al-Ahli","saudi pro league"),
    ("Baghdad Bounedjah","FWD",32,14,34,"Al-Sadd","qsl"),
    ("Saïd Benrahma","FWD",46,14,30,"Lyon","ligue 1"),
    ("Adam Ounas","FWD",36,8,28,"Nice","ligue 1"),
    ("Islam Slimani","FWD",96,40,37,"Sporting CP","primeira liga"),
    ("Andy Delort","FWD",42,12,33,"Nice","ligue 1"),
    ("Billal Brahimi","FWD",36,10,28,"Hajduk Split","hnl"),
    ("Mohamed Benyamina","FWD",12,3,23,"Belouizdad","ligue pro"),
    ("Zakaria Aboukhlal","FWD",26,8,25,"Toulouse","ligue 1"),
],

"Tunisia": [
    ("Aymen Dahmen","GK",28,0,29,"Montpellier","ligue 1"),
    ("Bechir Ben Said","GK",16,0,30,"Esperance","egypt prem"),
    ("Mouez Hassen","GK",22,0,30,"Nantes","ligue 1"),
    ("Montassar Talbi","DEF",22,1,26,"Lorient","ligue 1"),
    ("Nader Ghandri","DEF",26,1,30,"Empoli","serie a"),
    ("Wajdi Kechrida","DEF",46,2,30,"Spezia","serie b"),
    ("Dylan Bronn","DEF",32,1,29,"Salernitana","serie a"),
    ("Mohamed Drager","DEF",42,2,28,"Olympique Marseille","ligue 1"),
    ("Bilel Ifa","DEF",22,0,30,"Esperance","egypt prem"),
    ("Ali Maaloul","DEF",72,6,36,"Al-Ahly","egypt prem"),
    ("Ellyes Skhiri","MID",52,8,30,"Eintracht Frankfurt","bundesliga"),
    ("Aïssa Laïdouni","MID",26,2,28,"Union Berlin","bundesliga"),
    ("Wahbi Khazri","MID",82,26,33,"Montpellier","ligue 1"),
    ("Hannibal Mejbri","MID",22,3,22,"Burnley","championship"),
    ("Mohamed Ali Ben Romdhane","MID",22,3,27,"Nantes","ligue 1"),
    ("Naim Sliti","MID",56,10,31,"Rodez AF","ligue 2 fr"),
    ("Seifeddine Jaziri","FWD",36,12,33,"Zamalek","egypt prem"),
    ("Issam Jebali","FWD",42,14,30,"Odense","superliga"),
    ("Saif Eddine Khaoui","MID",32,8,29,"Toulouse","ligue 1"),
    ("Taha Yassine Khenissi","FWD",46,14,35,"Esperance","egypt prem"),
    ("Yassine Meriah","DEF",18,1,30,"Kasımpaşa","super lig"),
    ("Raed Bouchniba","MID",12,2,26,"Lens","ligue 1"),
    ("Bassem Srarfi","FWD",22,5,30,"Nice","ligue 1"),
    ("Adem Zorgane","MID",16,2,26,"Charleroi","pro league"),
    ("Mortadha Ben Ouanes","MID",8,1,23,"Esperance","egypt prem"),
    ("Hamza Mathlouthi","GK",6,0,28,"Esperance","egypt prem"),
],

"Cape Verde": [
    ("Vozinha","GK",52,0,36,"Lausanne-Sport","swiss super league"),
    ("Ivan Pereira","GK",12,0,28,"Belenenses","portuguesa liga"),
    ("Marcelo Boné","GK",8,0,25,"Académica","portuguesa liga"),
    ("Roberto Lopes","DEF",36,2,30,"Shamrock Rovers","league of ireland"),
    ("Edy Semedo","DEF",32,1,28,"Panathinaikos","super league greece"),
    ("Steven Fortes","DEF",42,2,34,"Rapid Wien","austrian bundesliga"),
    ("Dylan Tavares","DEF",22,1,22,"Benfica","primeira liga"),
    ("Marco Soares","DEF",16,0,25,"Feyenoord","eredivisie"),
    ("Stopira","DEF",76,4,37,"Sporting Braga","primeira liga"),
    ("Jesús Varela","DEF",12,0,24,"Arouca","primeira liga"),
    ("Garry Rodrigues","MID",56,14,33,"Galatasaray","super lig"),
    ("Kenny Rocha","MID",32,4,31,"Real Valladolid","la liga"),
    ("Diney Borges","MID",12,2,27,"Nacional","primeira liga"),
    ("Ryan Mendes","MID",56,16,35,"Dijon","ligue 2 fr"),
    ("Bebé","MID",22,5,34,"Tondela","portuguesa liga"),
    ("Sandro Semedo","MID",14,2,29,"Sporting Braga","primeira liga"),
    ("Jamiro Monteiro","MID",42,6,30,"New England Revolution","mls"),
    ("Jovane Cabral","FWD",32,10,27,"Sporting CP","primeira liga"),
    ("Djaniny","FWD",52,18,33,"Al-Qadsiah","saudi pro league"),
    ("Zé Luís","FWD",46,22,34,"Al-Rayyan","qsl"),
    ("Tavinho","FWD",8,2,23,"Belenenses","portuguesa liga"),
    ("Carlos Vinicius","FWD",18,6,30,"Benfica","primeira liga"),
    ("Bryan Teixeira","FWD",14,3,26,"Vitória Guimarães","primeira liga"),
    ("Gilson Benchimol","MID",8,1,24,"Académica","portuguesa liga"),
    ("João Pedro Gonçalves","MID",12,2,24,"Sporting","primeira liga"),
    ("Deroy Duarte","DEF",8,0,23,"Sint-Truiden","pro league"),
],

# ═══════════════════════════════════════════════════════════════
# AFC (Asia)
# ═══════════════════════════════════════════════════════════════
"Japan": [
    ("Shuichi Gonda","GK",56,0,32,"PSV","eredivisie"),
    ("Zion Suzuki","GK",16,0,23,"Sint-Truiden","pro league"),
    ("Kosei Tani","GK",8,0,24,"Shonan Bellmare","j1 league"),
    ("Takehiro Tomiyasu","DEF",46,2,27,"Arsenal","premier league"),
    ("Ko Itakura","DEF",42,1,28,"Borussia M'gladbach","bundesliga"),
    ("Yukinari Sugawara","DEF",26,1,24,"Southampton","premier league"),
    ("Miki Yamane","DEF",26,0,30,"Kashima Antlers","j1 league"),
    ("Hiroki Ito","DEF",32,2,26,"Bayern Munich","bundesliga"),
    ("Shogo Taniguchi","DEF",22,1,33,"Kawasaki Frontale","j1 league"),
    ("Riku Irie","DEF",12,0,24,"Mainz","bundesliga"),
    ("Wataru Endo","MID",56,3,32,"Liverpool","premier league"),
    ("Daichi Kamada","MID",36,10,29,"Lazio","serie a"),
    ("Takumi Minamino","MID",56,16,30,"Monaco","ligue 1"),
    ("Kaoru Mitoma","MID",36,10,28,"Brighton","premier league"),
    ("Junya Ito","MID",46,10,32,"Stade de Reims","ligue 1"),
    ("Ao Tanaka","MID",32,3,27,"Leeds United","championship"),
    ("Ritsu Doan","MID",46,16,27,"SC Freiburg","bundesliga"),
    ("Takefusa Kubo","FWD",46,12,24,"Real Sociedad","la liga"),
    ("Ayase Ueda","FWD",26,10,27,"Feyenoord","eredivisie"),
    ("Keito Nakamura","FWD",22,8,26,"Stade de Reims","ligue 1"),
    ("Koki Ogawa","FWD",16,6,26,"Juventus","serie a"),
    ("Mao Hosoya","FWD",12,4,25,"Club Brugge","pro league"),
    ("Maya Yoshida","DEF",124,6,37,"Vissel Kobe","j1 league"),
    ("Hidemasa Morita","MID",28,3,29,"Sporting CP","primeira liga"),
    ("Yuki Soma","MID",12,2,26,"Kashima Antlers","j1 league"),
    ("Sei Muroya","DEF",22,0,29,"Hannover 96","bundesliga 2"),
],

"South Korea": [
    ("Jo Hyeon-woo","GK",52,0,33,"Ulsan Hyundai","k league 1"),
    ("Kim Seung-gyu","GK",26,0,34,"Vissel Kobe","j1 league"),
    ("Gu Sung-yun","GK",8,0,27,"Jeju United","k league 1"),
    ("Kim Min-jae","DEF",56,5,28,"Bayern Munich","bundesliga"),
    ("Kim Jin-su","DEF",56,3,33,"SC Freiburg","bundesliga"),
    ("Kim Tae-hwan","DEF",52,2,33,"Ulsan Hyundai","k league 1"),
    ("Lee Gi-je","DEF",16,0,27,"FC Seoul","k league 1"),
    ("Seol Young-woo","DEF",16,1,25,"KAA Gent","pro league"),
    ("Jung Seung-hyun","DEF",22,1,30,"Urawa Red Diamonds","j1 league"),
    ("Kim Young-gwon","DEF",102,5,36,"Ulsan Hyundai","k league 1"),
    ("Lee Kang-in","MID",42,12,24,"Paris Saint-Germain","ligue 1"),
    ("Hwang In-beom","MID",56,10,29,"Ulsan Hyundai","k league 1"),
    ("Paik Seung-ho","MID",26,3,29,"Girona","la liga"),
    ("Jung Woo-young","MID",78,4,35,"Al-Qadsiah","saudi pro league"),
    ("Na Sang-ho","MID",22,4,27,"FC Seoul","k league 1"),
    ("Jeong Sang-bin","MID",16,3,24,"Feyenoord","eredivisie"),
    ("Lee Jae-sung","MID",52,10,33,"Mainz","bundesliga"),
    ("Son Heung-min","FWD",126,37,34,"Tottenham Hotspur","premier league"),
    ("Hwang Hee-chan","FWD",66,22,29,"Wolverhampton","premier league"),
    ("Cho Gue-sung","FWD",30,10,28,"Midtjylland","superliga"),
    ("Oh Se-hun","FWD",16,4,25,"Ulsan Hyundai","k league 1"),
    ("Hwang Ui-jo","FWD",72,26,33,"Nottingham Forest","premier league"),
    ("Choi Jun","FWD",14,3,23,"Jeonbuk","k league 1"),
    ("Yang Hyun-jun","FWD",18,5,23,"Celtic","scottish premiership"),
    ("Lim Chang-woo","DEF",12,0,24,"Suwon Samsung","k league 1"),
    ("Um Won-sang","MID",8,1,23,"Gangwon FC","k league 1"),
],

"Australia": [
    ("Mathew Ryan","GK",92,0,33,"AZ Alkmaar","eredivisie"),
    ("Joe Gauci","GK",12,0,26,"Adelaide United","a-league"),
    ("Danny Vukovic","GK",22,0,39,"Central Coast","a-league"),
    ("Harry Souttar","DEF",26,5,26,"Leicester City","premier league"),
    ("Miloš Degenek","DEF",56,2,32,"Columbus Crew","mls"),
    ("Bailey Wright","DEF",46,4,33,"Sunderland","championship"),
    ("Ryan Strain","DEF",26,0,30,"Middlesbrough","championship"),
    ("Aziz Behich","DEF",46,2,34,"Dundee United","scottish premiership"),
    ("Joel King","DEF",16,0,25,"Ipswich Town","premier league"),
    ("Nathaniel Atkinson","DEF",18,0,25,"Hearts","scottish premiership"),
    ("Jackson Irvine","MID",66,8,32,"St Pauli","bundesliga 2"),
    ("Riley McGree","MID",32,8,27,"Celtic","scottish premiership"),
    ("Keanu Baccus","MID",22,2,27,"St Mirren","scottish premiership"),
    ("Cameron Devlin","MID",22,2,28,"Hearts","scottish premiership"),
    ("Connor Metcalfe","MID",16,2,25,"Stoke City","championship"),
    ("Ajdin Hrustic","MID",32,3,28,"Hellas Verona","serie a"),
    ("Denis Genreau","MID",12,1,25,"Toulouse","ligue 1"),
    ("Mathew Leckie","FWD",86,14,35,"Melbourne City","a-league"),
    ("Mitchell Duke","FWD",36,8,34,"Macarthur FC","a-league"),
    ("Jamie Maclaren","FWD",26,14,32,"Melbourne City","a-league"),
    ("Marco Tilio","FWD",16,4,24,"Celtic","scottish premiership"),
    ("Ben Folami","FWD",12,3,25,"Ipswich Town","premier league"),
    ("Nestory Irankunda","FWD",8,2,19,"Bayern Munich","bundesliga"),
    ("Lewis Miller","DEF",14,0,24,"Hibernian","scottish premiership"),
    ("Martin Boyle","FWD",36,8,32,"Hibernian","scottish premiership"),
    ("Craig Goodwin","FWD",26,5,33,"Adelaide United","a-league"),
],

"Saudi Arabia": [
    ("Mohammed Al-Owais","GK",62,0,34,"Al-Hilal","saudi pro league"),
    ("Nawaf Al-Aqidi","GK",12,0,25,"Al-Nassr","saudi pro league"),
    ("Mohammed Al-Khilaiwi","GK",8,0,28,"Al-Ittihad","saudi pro league"),
    ("Saud Abdulhamid","DEF",32,1,25,"Roma","serie a"),
    ("Ali Al-Bulayhi","DEF",62,2,36,"Al-Hilal","saudi pro league"),
    ("Hassan Tambakti","DEF",22,1,26,"Al-Ahli","saudi pro league"),
    ("Mohammed Al-Amri","DEF",16,0,25,"Al-Hilal","saudi pro league"),
    ("Abdulellah Al-Malki","DEF",16,1,26,"Al-Hilal","saudi pro league"),
    ("Sultan Al-Ghannam","DEF",22,1,28,"Al-Hilal","saudi pro league"),
    ("Yasir Al-Shahrani","DEF",52,3,32,"Al-Hilal","saudi pro league"),
    ("Mohammed Kanno","MID",42,5,28,"Al-Hilal","saudi pro league"),
    ("Salman Al-Faraj","MID",82,14,35,"Al-Hilal","saudi pro league"),
    ("Mohamed Al-Najei","MID",16,1,25,"Damac","saudi pro league"),
    ("Riyadh Sharahili","MID",22,2,27,"Al-Hilal","saudi pro league"),
    ("Nasser Al-Dawsari","MID",26,5,31,"Al-Qadsiah","saudi pro league"),
    ("Abdulrahman Al-Aboud","MID",28,3,29,"Al-Ahli","saudi pro league"),
    ("Ali Al-Hassan","MID",16,2,24,"Al-Nassr","saudi pro league"),
    ("Salem Al-Dawsari","FWD",92,28,33,"Al-Hilal","saudi pro league"),
    ("Saleh Al-Shehri","FWD",62,22,33,"Al-Hilal","saudi pro league"),
    ("Firas Al-Buraikan","FWD",32,14,25,"Al-Hilal","saudi pro league"),
    ("Abdullah Al-Hamdan","FWD",22,10,26,"Al-Hilal","saudi pro league"),
    ("Sami Al-Najei","FWD",16,4,26,"Al-Qadsiah","saudi pro league"),
    ("Hattan Bahebri","FWD",22,6,30,"Al-Hilal","saudi pro league"),
    ("Yousef Al-Arabi","FWD",12,4,24,"Al-Nassr","saudi pro league"),
    ("Mohammed Al-Breik","DEF",12,0,27,"Al-Ahli","saudi pro league"),
    ("Abdulelah Al-Malki","MID",16,1,26,"Al-Hilal","saudi pro league"),
],

"Iran": [
    ("Alireza Beiranvand","GK",56,0,34,"Antwerp","pro league"),
    ("Payam Niazmand","GK",16,0,29,"Persepolis","iran pro league"),
    ("Hossein Hosseini","GK",12,0,30,"Esteghlal","iran pro league"),
    ("Sadegh Moharrami","DEF",42,1,28,"Fiorentina","serie a"),
    ("Ramin Rezaeian","DEF",66,2,34,"Zulte Waregem","pro league"),
    ("Morteza Pouraliganji","DEF",56,3,34,"Al-Gharafa","qsl"),
    ("Milad Mohammadi","DEF",62,3,32,"AEK Athens","super league greece"),
    ("Shojae Khalilzadeh","DEF",52,2,35,"Al-Ahli","saudi pro league"),
    ("Abolfazl Jalali","DEF",12,0,25,"Persepolis","iran pro league"),
    ("Majid Hosseini","DEF",22,1,27,"Kasımpaşa","super lig"),
    ("Saeid Ezatolahi","MID",56,5,29,"Almería","la liga"),
    ("Ali Gholizadeh","MID",42,10,29,"Charleroi","pro league"),
    ("Ehsan Hajsafi","MID",122,8,36,"AEK Athens","super league greece"),
    ("Ahmad Noorollahi","MID",42,4,30,"Persepolis","iran pro league"),
    ("Ali Karimi","MID",14,2,25,"Heerenveen","eredivisie"),
    ("Mehdi Ghayedi","MID",16,5,26,"Club Brugge","pro league"),
    ("Omid Ebrahimi","MID",78,4,35,"Damac FC","saudi pro league"),
    ("Mehdi Taremi","FWD",96,46,32,"Inter Milan","serie a"),
    ("Sardar Azmoun","FWD",66,42,30,"Roma","serie a"),
    ("Allahyar Sayyadmanesh","FWD",26,8,26,"Kasımpaşa","super lig"),
    ("Karim Ansarifard","FWD",100,40,36,"Nottingham Forest","premier league"),
    ("Mohammad Mohebi","FWD",12,3,24,"Persepolis","iran pro league"),
    ("Ahmad Abedzadeh","GK",36,0,34,"Servette","swiss super league"),
    ("Roozbeh Cheshmi","DEF",36,3,32,"Esteghlal","iran pro league"),
    ("Saman Ghoddos","MID",46,8,31,"Brentford","premier league"),
    ("Alireza Jahanbakhsh","FWD",76,18,32,"Feyenoord","eredivisie"),
],

"Iraq": [
    ("Jalal Hassan","GK",62,0,35,"Al-Quwa Al-Jawiya","iraq star league"),
    ("Fahad Tariq","GK",12,0,26,"Al-Shorta","iraq star league"),
    ("Mohammed Hameed","GK",8,0,28,"Al-Zawraa","iraq star league"),
    ("Ali Adnan","DEF",86,10,32,"Colorado Rapids","mls"),
    ("Rebin Sulaka","DEF",32,1,30,"Nottingham Forest","premier league"),
    ("Amjad Atwan","DEF",22,0,28,"Al-Quwa Al-Jawiya","iraq star league"),
    ("Mustafa Nadhim","DEF",18,0,26,"Al-Shorta","iraq star league"),
    ("Hussein Abdulwahab","DEF",14,0,24,"FC Krasnodar","russian premier league"),
    ("Abbas Nouri","DEF",12,0,25,"Al-Zawraa","iraq star league"),
    ("Ahmed Ibrahim","DEF",16,1,27,"Al-Quwa Al-Jawiya","iraq star league"),
    ("Osama Rashid","MID",56,16,30,"Al-Quwa Al-Jawiya","iraq star league"),
    ("Saad Natiq","MID",22,4,27,"Al-Zorah","uae pro league"),
    ("Hussein Ali","MID",22,3,25,"Al-Shorta","iraq star league"),
    ("Alaa Abbas","MID",22,5,26,"Al-Shorta","iraq star league"),
    ("Mohanad Lateef","MID",36,6,28,"Al-Quwa Al-Jawiya","iraq star league"),
    ("Bashar Rezan","MID",28,4,27,"Anorthosis Famagusta","cyprus league"),
    ("Ibrahim Bayesh","MID",16,2,25,"Al-Zawraa","iraq star league"),
    ("Aymen Hussein","FWD",42,20,28,"Al-Quwa Al-Jawiya","iraq star league"),
    ("Mohannad Ali","FWD",16,6,24,"Al-Zawraa","iraq star league"),
    ("Dawood Ghazi","FWD",12,4,23,"Al-Shorta","iraq star league"),
    ("Amjad Kalaf","FWD",22,8,26,"Al-Quwa Al-Jawiya","iraq star league"),
    ("Ahmed Karam","FWD",14,4,25,"Al-Zawraa","iraq star league"),
    ("Safaa Haddad","FWD",16,5,27,"Al-Shorta","iraq star league"),
    ("Humam Tariq","MID",8,1,22,"Al-Quwa Al-Jawiya","iraq star league"),
    ("Nashat Akram Jr.","MID",12,2,24,"Al-Zawraa","iraq star league"),
    ("Mahdi Kamil","DEF",8,0,23,"Al-Quwa Al-Jawiya","iraq star league"),
],

"Qatar": [
    ("Meshaal Barsham","GK",36,0,26,"Al-Sadd","qsl"),
    ("Yousuf Hassan","GK",22,0,28,"Al-Gharafa","qsl"),
    ("Bassel El-Bakri","GK",8,0,25,"Al-Duhail","qsl"),
    ("Pedro Miguel","DEF",66,3,33,"Al-Rayyan","qsl"),
    ("Bassam Al-Rawi","DEF",36,2,27,"Al-Rayyan","qsl"),
    ("Abdelkarim Hassan","DEF",82,4,30,"Al-Sadd","qsl"),
    ("Tarek Salman","DEF",26,0,27,"Al-Gharafa","qsl"),
    ("Musab Khidir","DEF",22,1,29,"Al-Duhail","qsl"),
    ("Boualem Khoukhi","DEF",62,3,35,"Al-Sadd","qsl"),
    ("Mohammed Waad","DEF",16,0,25,"Al-Sadd","qsl"),
    ("Karim Boudiaf","MID",66,6,33,"Al-Duhail","qsl"),
    ("Assim Madibo","MID",36,3,29,"Rouen","ligue 2 fr"),
    ("Hasan Al-Haydos","MID",132,42,33,"Al-Sadd","qsl"),
    ("Mohammed Al-Wahidi","MID",18,2,26,"Al-Sadd","qsl"),
    ("Ismail Mohamad","MID",22,3,25,"Al-Sadd","qsl"),
    ("Homam El-Amine","MID",22,4,27,"Al-Rayyan","qsl"),
    ("Tarek Al Khatib","MID",8,1,22,"Al-Arabi","qsl"),
    ("Akram Afif","FWD",76,32,28,"Al-Sadd","qsl"),
    ("Almoez Ali","FWD",82,42,29,"Al-Duhail","qsl"),
    ("Mohammed Muntari","FWD",46,12,28,"Al-Duhail","qsl"),
    ("Khalid Muneer","FWD",22,6,26,"Al-Sadd","qsl"),
    ("Ahmad Al-Rawi","FWD",16,4,24,"Al-Sadd","qsl"),
    ("Ibrahim Khalfan","FWD",14,3,26,"Al-Gharafa","qsl"),
    ("Yusuf Abdurisag","FWD",12,3,25,"Al-Sadd","qsl"),
    ("Hassan Al-Baloushi","DEF",16,0,27,"Al-Rayyan","qsl"),
    ("Khalid Al-Hajri","GK",6,0,24,"Al-Sadd","qsl"),
],

"Uzbekistan": [
    ("Utkir Yusupov","GK",46,0,28,"Pakhtakor","uzbekistan super league"),
    ("Abdulla Nishonov","GK",12,0,26,"Pakhtakor","uzbekistan super league"),
    ("Botir Ergashev","GK",8,0,24,"Lokomotiv Tashkent","uzbekistan super league"),
    ("Sanjar Tursunov","DEF",32,1,28,"Pakhtakor","uzbekistan super league"),
    ("Shokhrat Tukhtasin","DEF",22,0,26,"Pakhtakor","uzbekistan super league"),
    ("Akbar Tursunov","DEF",18,0,25,"Pakhtakor","uzbekistan super league"),
    ("Dostonbek Khamdamov","DEF",26,1,27,"Lokomotiv Tashkent","uzbekistan super league"),
    ("Sherzod Nishonov","DEF",14,0,26,"Navbahor","uzbekistan super league"),
    ("Oybek Hamidov","DEF",12,0,24,"Pakhtakor","uzbekistan super league"),
    ("Khojimat Erkinov","MID",36,4,27,"Pakhtakor","uzbekistan super league"),
    ("Jasur Yakhshiboyev","MID",16,2,24,"Pakhtakor","uzbekistan super league"),
    ("Behruz Abdikholikov","MID",16,2,25,"Pakhtakor","uzbekistan super league"),
    ("Otabek Shukurov","MID",14,2,24,"Pakhtakor","uzbekistan super league"),
    ("Jaloliddin Masharipov","MID",56,8,32,"CSKA Moscow","russian premier league"),
    ("Bekhruz Jalolov","MID",18,3,25,"Pakhtakor","uzbekistan super league"),
    ("Khojiakbar Alijonov","MID",14,2,23,"Lokomotiv Tashkent","uzbekistan super league"),
    ("Muzaffar Kushaev","MID",12,1,23,"Pakhtakor","uzbekistan super league"),
    ("Eldor Shomurodov","FWD",66,32,29,"Cagliari","serie a"),
    ("Abbosbek Fayzullayev","FWD",32,8,24,"Southampton","premier league"),
    ("Sherzod Nasrullayev","FWD",16,4,24,"Navbahor","uzbekistan super league"),
    ("Dostonbek Turgunboev","FWD",12,3,23,"Pakhtakor","uzbekistan super league"),
    ("Otajon Ismoilov","FWD",18,6,26,"Pakhtakor","uzbekistan super league"),
    ("Hikmat Jurabekov","FWD",8,2,22,"Pakhtakor","uzbekistan super league"),
    ("Islom Tukhtahujaev","MID",10,1,23,"Lokomotiv Tashkent","uzbekistan super league"),
    ("Eldor Nazarov","FWD",12,3,25,"FK Navbahor","uzbekistan super league"),
    ("Shamsiddin Shomusarov","MID",8,1,22,"Pakhtakor","uzbekistan super league"),
],

"Jordan": [
    ("Yazeed Abulaila","GK",36,0,30,"Al-Wehdat","jordan league"),
    ("Ahmad Haboush","GK",12,0,28,"Al-Jazeera","jordan league"),
    ("Mohammad Shabaik","GK",8,0,26,"Al-Faisaly","jordan league"),
    ("Abdullah Nasib","DEF",30,1,28,"Al-Faisaly","jordan league"),
    ("Baha Faisal","DEF",22,1,25,"Al-Wehdat","jordan league"),
    ("Yazan Alnaimat","DEF",18,0,26,"Al-Jazeera","jordan league"),
    ("Khaled Mokhalled","DEF",32,2,29,"Al-Faisaly","jordan league"),
    ("Ahmad Al-Saraireh","DEF",16,0,25,"Al-Wehdat","jordan league"),
    ("Samer Suleiman","DEF",22,1,28,"Al-Ahli","jordan league"),
    ("Malek Al-Rousan","DEF",12,0,24,"Al-Faisaly","jordan league"),
    ("Musa Al-Taamari","MID",56,14,27,"Montpellier","ligue 1"),
    ("Ahmad Salam","MID",22,3,26,"Al-Faisaly","jordan league"),
    ("Noor Al-Rawabdeh","MID",16,2,25,"Al-Wahda","uae pro league"),
    ("Yazan Al-Arab","MID",22,4,27,"Al-Wehdat","jordan league"),
    ("Anas Bani Yaseen","MID",18,2,26,"Al-Faisaly","jordan league"),
    ("Mohammad Abu Zema","MID",14,1,24,"Al-Jazeera","jordan league"),
    ("Raed Saleh","MID",22,3,28,"Al-Ahli","jordan league"),
    ("Hamza Al-Dardour","FWD",76,22,34,"Al-Wehdat","jordan league"),
    ("Mahmoud Al-Mardi","FWD",22,8,25,"Al-Wehdat","jordan league"),
    ("Omar Al-Hamil","FWD",32,12,28,"Al-Faisaly","jordan league"),
    ("Baha Al-Hussain","FWD",12,4,24,"Al-Jazeera","jordan league"),
    ("Mohammad Al-Shalabi","FWD",18,5,26,"Al-Wahda","uae pro league"),
    ("Sami Al-Tawalbeh","FWD",14,3,25,"Al-Ahli","jordan league"),
    ("Saleh Al-Yahyawi","MID",10,1,23,"Al-Faisaly","jordan league"),
    ("Obada Al-Jaber","FWD",8,2,22,"Al-Wehdat","jordan league"),
    ("Amer Shafi","GK",52,0,42,"Al-Wehdat","jordan league"),
],

# ═══════════════════════════════════════════════════════════════
# OFC
# ═══════════════════════════════════════════════════════════════
"New Zealand": [
    ("Oli Sail","GK",26,0,27,"Columbus Crew","mls"),
    ("Max Crocombe","GK",22,0,30,"Dundee","scottish premiership"),
    ("Stefan Marinovic","GK",16,0,36,"Vancouver Whitecaps","mls"),
    ("Liberato Cacace","DEF",36,1,25,"Empoli","serie a"),
    ("Michael Boxall","DEF",56,3,36,"Minnesota United","mls"),
    ("Nando Pijnaker","DEF",22,0,29,"Dundee United","scottish premiership"),
    ("Marko Stamenic","MID",16,2,24,"FC Copenhagen","superliga"),
    ("Tommy Smith","DEF",32,1,35,"Stoke City","championship"),
    ("Winston Reid","DEF",56,4,36,"Brentford","premier league"),
    ("Tim Payne","DEF",8,0,23,"Wellington Phoenix","a-league"),
    ("Joe Bell","MID",22,3,26,"FK Bodø/Glimt","eliteserien"),
    ("Callum McCowatt","MID",26,4,27,"Ħamrun Spartans","league of ireland"),
    ("Ryan Thomas","MID",36,4,31,"PSV","eredivisie"),
    ("Matthew Garbett","MID",22,3,25,"Dundee","scottish premiership"),
    ("Elijah Just","MID",12,1,23,"Wellington Phoenix","a-league"),
    ("Dane Ingham","MID",16,2,28,"FC Nordsjaelland","superliga"),
    ("Marco Rojas","MID",46,8,34,"Melbourne Victory","a-league"),
    ("Chris Wood","FWD",126,32,34,"Nottingham Forest","premier league"),
    ("Myer Bevan","FWD",12,2,25,"Wellington Phoenix","a-league"),
    ("Ben Waine","FWD",14,3,24,"Tromsø IL","eliteserien"),
    ("Ben Old","FWD",10,2,21,"Young Fellows Winterthur","swiss super league"),
    ("Matt Garbett","MID",22,3,25,"Dundee","scottish premiership"),
    ("Bozhidar Kraev","FWD",16,4,28,"CSKA Sofia","superliga"),
    ("Cameron Howieson","MID",8,1,25,"Ross County","scottish premiership"),
    ("Logan Rogerson","FWD",8,2,24,"Kristiansund","eliteserien"),
    ("Finn Surman","MID",6,0,21,"Wellington Phoenix","a-league"),
],

# ═══════════════════════════════════════════════════════════════
# Extra teams in DB (Norway, Sweden, Bosnia, etc.)
# ═══════════════════════════════════════════════════════════════
"Norway": [
    ("Ørjan Nyland","GK",52,0,34,"Brentford","premier league"),
    ("Jørgen Strand Larsen","FWD",22,8,25,"Celta Vigo","la liga"),
    ("Alexander Sørloth","FWD",56,26,29,"Atletico Madrid","la liga"),
    ("Erling Haaland","FWD",36,28,26,"Manchester City","premier league"),
    ("Martin Ødegaard","MID",82,14,27,"Arsenal","premier league"),
    ("Sander Berge","MID",56,8,27,"Fulham","premier league"),
    ("Stefan Strandberg","DEF",46,2,35,"CSKA Moscow","russian premier league"),
    ("Omar Elabdellaoui","DEF",56,4,33,"Galatasaray","super lig"),
    ("Leo Skiri Østigård","DEF",28,2,25,"Napoli","serie a"),
    ("Andreas Hanche-Olsen","DEF",22,2,27,"Genk","pro league"),
    ("Kristian Thorvaldsen","DEF",12,0,27,"Rosenborg","eliteserien"),
    ("Patrick Berg","MID",22,2,26,"RC Lens","ligue 1"),
    ("Fredrik Aursnes","MID",28,3,28,"Benfica","primeira liga"),
    ("Mathias Normann","MID",26,3,29,"Middlesbrough","championship"),
    ("Kristian Hlynsson","MID",8,1,21,"Leipzig","bundesliga"),
    ("Morten Thorsby","MID",32,4,29,"Genoa","serie a"),
    ("Ola Solbakken","FWD",22,6,25,"Roma","serie a"),
    ("Antonio Nusa","FWD",14,4,20,"Club Brugge","pro league"),
    ("Vegar Eggen Hedenstad","DEF",22,1,31,"Celtic","scottish premiership"),
    ("Håkon Evjen","MID",18,3,24,"AZ Alkmaar","eredivisie"),
    ("Tobias Svendsen","MID",8,1,22,"Groningen","eredivisie"),
    ("Stian Rode Gregersen","DEF",16,1,30,"Aarhus GF","superliga"),
    ("David Datro Fofana","FWD",16,4,23,"Chelsea","premier league"),
    ("Joshua King","FWD",96,26,33,"Besiktas","super lig"),
    ("Reidar Gundersen Hauglie","DEF",8,0,22,"Brann","eliteserien"),
    ("Mathias Dyngeland","GK",8,0,25,"Rosenborg","eliteserien"),
],

"Sweden": [
    ("Robin Olsen","GK",56,0,35,"Aston Villa","premier league"),
    ("Karl-Johan Johnsson","GK",16,0,33,"QPR","championship"),
    ("Samuel Brolin","GK",8,0,25,"Elfsborg","allsvenskan"),
    ("Victor Lindelöf","DEF",86,5,30,"Manchester United","premier league"),
    ("Ludwig Augustinsson","DEF",52,4,29,"Udinese","serie a"),
    ("Isak Hien","DEF",22,1,24,"Atalanta","serie a"),
    ("Carl Starfelt","DEF",36,2,30,"Celtic","scottish premiership"),
    ("Emil Krafth","DEF",26,0,30,"Newcastle United","premier league"),
    ("Filip Helander","DEF",18,1,32,"Rangers","scottish premiership"),
    ("Joakim Nilsson","DEF",22,1,30,"Middlesbrough","championship"),
    ("Emil Forsberg","MID",102,26,34,"RB Leipzig","bundesliga"),
    ("Albin Ekdal","MID",62,6,36,"Sampdoria","serie b"),
    ("Dejan Kulusevski","MID",52,10,25,"Tottenham Hotspur","premier league"),
    ("Viktor Claesson","MID",62,14,34,"Krasnodar","russian premier league"),
    ("Mattias Svanberg","MID",28,4,27,"Bologna","serie a"),
    ("Jesper Karlsson","FWD",26,8,26,"Ajax","eredivisie"),
    ("Alexander Isak","FWD",42,18,25,"Newcastle United","premier league"),
    ("Zlatan Ibrahimovic","FWD",122,62,45,"retired","serie a"),
    ("Robin Quaison","FWD",36,12,32,"Palermo","serie b"),
    ("Marcus Danielson","DEF",36,4,35,"Djurgårdens IF","allsvenskan"),
    ("Samuel Dahl","DEF",14,0,22,"Chelsea","premier league"),
    ("Pontus Jansson","DEF",36,3,34,"Brentford","premier league"),
    ("Jordan Larsson","FWD",12,4,27,"Spartak Moscow","russian premier league"),
    ("Gustav Svensson","MID",46,3,36,"Seattle Sounders","mls"),
    ("Kwame Peprah","FWD",8,2,24,"Elfsborg","allsvenskan"),
    ("Niklas Hult","DEF",36,0,36,"AIK","allsvenskan"),
],

"Bosnia and Herzegovina": [
    ("Ibrahim Šehić","GK",56,0,36,"Ankaraspor","super lig"),
    ("Kenan Pirić","GK",22,0,31,"Watford","championship"),
    ("Nikola Vasilj","GK",16,0,29,"St Pauli","bundesliga 2"),
    ("Sead Kolašinac","DEF",76,5,31,"Marseille","ligue 1"),
    ("Ermin Bičakčić","DEF",52,4,35,"Hoffenheim","bundesliga"),
    ("Strahinja Tanasijević","DEF",12,0,24,"Partizan","superliga"),
    ("Vedran Ćorluka","DEF",116,7,39,"Lokomotiv Moscow","russian premier league"),
    ("Toni Šunjić","DEF",36,2,33,"Dinamo Zagreb","hnl"),
    ("Jusuf Gazibegović","DEF",22,1,26,"Salzburg","bundesliga at"),
    ("Nikola Kalinic","DEF",16,0,27,"Hoffenheim","bundesliga"),
    ("Miralem Pjanić","MID",104,16,36,"Sharjah","uae pro league"),
    ("Haris Duljevic","MID",46,8,31,"Nantes","ligue 1"),
    ("Amer Gojak","MID",26,4,28,"Dinamo Zagreb","hnl"),
    ("Luka Menalo","MID",18,3,28,"Dinamo Zagreb","hnl"),
    ("Edín Višća","MID",62,12,34,"Istanbul Başakşehir","super lig"),
    ("Sead Kolasinac","DEF",76,5,31,"Marseille","ligue 1"),
    ("Armin Hodžić","FWD",22,6,31,"Dinamo Zagreb","hnl"),
    ("Edin Džeko","FWD",136,64,40,"Fenerbahçe","super lig"),
    ("Ermedin Demirović","FWD",22,10,26,"Augsburg","bundesliga"),
    ("Ognjen Todorović","MID",14,2,28,"Čukarički","superliga"),
    ("Deni Miloša","FWD",8,2,24,"Rijeka","hnl"),
    ("Nemanja Bilbija","FWD",18,6,33,"Borac Banja Luka","premier bih"),
    ("Benjamin Šeško","FWD",8,2,22,"RB Leipzig","bundesliga"),
    ("Kenan Kodro","FWD",18,4,31,"Málaga","segunda division"),
    ("Anel Ahmedhodžić","DEF",18,2,26,"Sheffield United","championship"),
    ("Darko Todorović","MID",8,1,24,"FK Sarajevo","premier bih"),
],

}


def run() -> dict:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    stats = {"teams": 0, "updated": 0, "inserted": 0, "retired": 0, "skipped": 0}

    for team_name, players in SQUADS.items():
        row = cur.execute("SELECT id FROM teams WHERE name=?", (team_name,)).fetchone()
        if not row:
            log.warning(f"Team not found: {team_name}")
            stats["skipped"] += 1
            continue
        team_id = row["id"]

        # Clean slate — mark all current squad as unconfirmed
        retired = cur.execute(
            "UPDATE squad_selections SET confirmed=0 WHERE team_id=?", (team_id,)
        ).rowcount
        stats["retired"] += retired

        for name, pos, caps, goals, age, club, league in players:
            # Skip placeholder retired entries
            if club == "retired":
                continue

            existing = cur.execute(
                "SELECT id FROM players WHERE LOWER(name)=LOWER(?) AND team_id=?",
                (name, team_id),
            ).fetchone()

            if existing:
                cur.execute(
                    """UPDATE players SET position=?, caps=?, goals_as_nat=?,
                       age=?, club=?, club_league=? WHERE id=?""",
                    (pos, caps, goals, age, club, league, existing["id"]),
                )
                pid = existing["id"]
                stats["updated"] += 1
            else:
                cur.execute(
                    """INSERT INTO players
                       (name, team_id, position, caps, goals_as_nat, age, club, club_league)
                       VALUES (?,?,?,?,?,?,?,?)""",
                    (name, team_id, pos, caps, goals, age, club, league),
                )
                pid = cur.lastrowid
                stats["inserted"] += 1

            cur.execute(
                "INSERT OR IGNORE INTO squad_selections (team_id, player_id, confirmed) VALUES (?,?,1)",
                (team_id, pid),
            )
            cur.execute(
                "UPDATE squad_selections SET confirmed=1 WHERE player_id=? AND team_id=?",
                (pid, team_id),
            )

        stats["teams"] += 1

    conn.commit()
    conn.close()
    return stats


if __name__ == "__main__":
    log.info("Aplicando squads maestros WC2026...")
    start = datetime.now()
    s = run()
    elapsed = (datetime.now() - start).total_seconds()
    log.info(
        f"✅ {elapsed:.1f}s — {s['teams']} equipos | "
        f"+{s['inserted']} nuevos | {s['updated']} actualizados | {s['retired']} retirados"
    )

