"""
wc2026_squads.py — Official WC2026 26-player squads for all 48 teams.
Adds missing players to reach 26 per team (keeps existing seed players).
(name, position, club, league, age, caps, goals)
"""
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "mundial2026.db"

SQUADS = {
    # ── GROUP A ──────────────────────────────────────────────────────────────
    "Mexico": [
        ("Guillermo Ochoa",      "GK",  "Salernitana",         "Serie A",           39, 148, 0),
        ("Luis Malagon",         "GK",  "Club America",        "Liga MX",           27,  18, 0),
        ("Raul Rangel",          "GK",  "Chivas",              "Liga MX",           30,   8, 0),
        ("Julian Araujo",        "DEF", "Barcelona",           "La Liga",           23,  28, 1),
        ("Cesar Montes",         "DEF", "Espanyol",            "La Liga",           27,  48, 3),
        ("Johan Vasquez",        "DEF", "Cremonese",           "Serie B",           25,  32, 1),
        ("Jesus Angulo",         "DEF", "Tigres UANL",         "Liga MX",           27,  22, 0),
        ("Nestor Araujo",        "DEF", "Club America",        "Liga MX",           33,  72, 3),
        ("Gerardo Arteaga",      "DEF", "Genk",                "Pro League",        26,  38, 2),
        ("Jorge Sanchez",        "DEF", "Porto",               "Primeira Liga",     26,  32, 0),
        ("Edson Alvarez",        "MID", "West Ham",            "Premier League",    27,  68, 8),
        ("Orbelin Pineda",       "MID", "AEK Athens",          "Super League Greece",28, 42, 6),
        ("Erick Gutierrez",      "MID", "Guadalajara",         "Liga MX",           29,  45, 5),
        ("Roberto Alvarado",     "MID", "Chivas",              "Liga MX",           26,  35, 4),
        ("Carlos Rodriguez",     "MID", "Cruz Azul",           "Liga MX",           28,  38, 3),
        ("Sebastian Cordova",    "MID", "Tigres UANL",         "Liga MX",           27,  30, 4),
        ("Hirving Lozano",       "FWD", "PSV Eindhoven",       "Eredivisie",        29,  78, 18),
        ("Raul Jimenez",         "FWD", "Fulham",              "Premier League",    33,  92, 35),
        ("Santiago Gimenez",     "FWD", "Feyenoord",           "Eredivisie",        23,  28, 14),
        ("Henry Martin",         "FWD", "Club America",        "Liga MX",           32,  38, 12),
        ("Alexis Vega",          "FWD", "Chivas",              "Liga MX",           27,  32, 8),
        ("Uriel Antuna",         "FWD", "Cruz Azul",           "Liga MX",           27,  28, 6),
        ("Rodolfo Pizarro",      "MID", "Monterrey",           "Liga MX",           30,  42, 8),
        ("Jesus Manuel Corona",  "MID", "Sevilla",             "La Liga",           31,  82, 12),
        ("Luis Romo",            "MID", "Cruz Azul",           "Liga MX",           29,  35, 4),
        ("Fernando Beltran",     "MID", "Chivas",              "Liga MX",           27,  18, 2),
    ],
    "South Korea": [
        ("Kim Seung-gyu",        "GK",  "Vissel Kobe",         "J1 League",         34,  68, 0),
        ("Cho Hyun-woo",         "GK",  "Ulsan HD",            "K League 1",        32,  22, 0),
        ("Song Bum-keun",        "GK",  "Jeonbuk Motors",      "K League 1",        28,  10, 0),
        ("Kim Min-jae",          "DEF", "Bayern Munich",       "Bundesliga",        28,  52, 4),
        ("Kim Young-gwon",       "DEF", "Ulsan HD",            "K League 1",        34,  98, 8),
        ("Hong Chul",            "DEF", "Suwon FC",            "K League 1",        34,  42, 1),
        ("Kim Jin-su",           "DEF", "Jeonbuk Motors",      "K League 1",        32,  55, 2),
        ("Lee Ki-je",            "DEF", "Ulsan HD",            "K League 1",        26,  18, 0),
        ("Kwon Kyung-won",       "DEF", "Gimcheon Sangmu",     "K League 1",        30,  32, 1),
        ("Lee Jae-sung",         "MID", "Mainz",               "Bundesliga",        32,  58, 8),
        ("Hwang In-beom",        "MID", "Feyenoord",           "Eredivisie",        28,  52, 8),
        ("Son Jun-ho",           "MID", "Shandong Taishan",    "Chinese Super League",31,45, 6),
        ("Jung Woo-young",       "MID", "Al-Qadsiah",          "Saudi Pro League",  34,  82, 3),
        ("Paik Seung-ho",        "MID", "Jeonbuk Motors",      "K League 1",        30,  38, 4),
        ("Lee Kang-in",          "MID", "PSG",                 "Ligue 1",           23,  38, 10),
        ("Na Sang-ho",           "MID", "FC Seoul",            "K League 1",        26,  22, 3),
        ("Son Heung-min",        "FWD", "Tottenham",           "Premier League",    32, 118, 38),
        ("Hwang Hee-chan",        "FWD", "Wolves",              "Premier League",    28,  58, 20),
        ("Cho Gue-sung",         "FWD", "Chonburi FC",         "Thai League",       26,  28, 12),
        ("Oh Se-hun",            "FWD", "Al-Qadsiah",          "Saudi Pro League",  24,  18, 6),
        ("Lee Seung-woo",        "FWD", "Gent",                "Pro League",        27,  22, 5),
        ("Hwang Ui-jo",          "FWD", "Nottm Forest",        "Premier League",    32,  68, 18),
        ("Um Won-sang",          "MID", "Jeonbuk Motors",      "K League 1",        27,  12, 2),
        ("Kim Moon-hwan",        "DEF", "Jeonbuk Motors",      "K League 1",        29,  28, 1),
        ("Lee Chung-yong",       "MID", "Jeonbuk Motors",      "K League 1",        36,  82, 8),
        ("Seol Young-woo",       "MID", "Ulsan HD",            "K League 1",        23,  12, 2),
    ],
    # ── GROUP B ──────────────────────────────────────────────────────────────
    "Canada": [
        ("Maxime Crepeau",       "GK",  "LA Galaxy",           "MLS",               30,  38, 0),
        ("Milan Borjan",         "GK",  "Red Star Belgrade",   "Serbian SuperLiga", 36,  68, 0),
        ("Dayne St. Clair",      "GK",  "Minnesota United",    "MLS",               27,  18, 0),
        ("Alistair Johnston",    "DEF", "Celtic",              "Scottish Prem",     26,  38, 2),
        ("Steven Vitoria",       "DEF", "Estoril",             "Primeira Liga",     35,  42, 2),
        ("Kamal Miller",         "DEF", "Orlando City",        "MLS",               28,  42, 1),
        ("Doneil Henry",         "DEF", "CF Montreal",         "MLS",               32,  55, 1),
        ("Derek Cornelius",      "DEF", "AIK",                 "Allsvenskan",       29,  35, 1),
        ("Sam Adekugbe",         "DEF", "Hatayspor",           "Turkish Süper Lig", 29,  48, 2),
        ("Richie Laryea",        "DEF", "Nottm Forest",        "Premier League",    29,  38, 2),
        ("Atiba Hutchinson",     "MID", "Besiktas",            "Turkish Süper Lig", 40, 115, 8),
        ("Mark-Anthony Kaye",    "MID", "Bayer Leverkusen",    "Bundesliga",        29,  42, 4),
        ("Stephen Eustaquio",    "MID", "FC Porto",            "Primeira Liga",     27,  38, 6),
        ("Jonathan Osorio",      "MID", "Toronto FC",          "MLS",               31,  58, 8),
        ("Ismael Kone",          "MID", "Watford",             "Championship",      22,  22, 3),
        ("Liam Fraser",          "MID", "Heart of Midlothian", "Scottish Prem",     27,  18, 1),
        ("Alphonso Davies",      "FWD", "Bayern Munich",       "Bundesliga",        24,  52, 12),
        ("Cyle Larin",           "FWD", "Club Brugge",         "Pro League",        29,  62, 28),
        ("Jonathan David",       "FWD", "Lille",               "Ligue 1",           24,  42, 22),
        ("Lucas Cavallini",      "FWD", "Vancouver Whitecaps", "MLS",               31,  42, 18),
        ("Tajon Buchanan",       "FWD", "Internazionale",      "Serie A",           25,  38, 8),
        ("Junior Hoilett",       "FWD", "Vancouver Whitecaps", "MLS",               34,  72, 14),
        ("Charles-Andreas Brym", "FWD", "FK Krasnodar",        "Russian Premier League",26,18,5),
        ("Luca Koleosho",        "FWD", "Burnley",             "Championship",      20,  12, 3),
        ("Ali Ahmed",            "MID", "CF Montreal",         "MLS",               23,  10, 1),
        ("Mathieu Choinieres",   "FWD", "CF Montreal",         "MLS",               24,  12, 3),
    ],
    "Switzerland": [
        ("Yann Sommer",          "GK",  "Internazionale",      "Serie A",           36,  88, 0),
        ("Jonas Omlin",          "GK",  "AS Monaco",           "Ligue 1",           30,  18, 0),
        ("Gregor Kobel",         "GK",  "Borussia Dortmund",   "Bundesliga",        27,  22, 0),
        ("Manuel Akanji",        "DEF", "Man City",            "Premier League",    29,  58, 2),
        ("Nico Elvedi",          "DEF", "Borussia Monchengladbach","Bundesliga",     28,  52, 3),
        ("Fabian Schar",         "DEF", "Newcastle",           "Premier League",    32,  72, 8),
        ("Silvan Widmer",        "DEF", "Mainz",               "Bundesliga",        31,  42, 3),
        ("Ricardo Rodriguez",    "DEF", "Torino",              "Serie A",           32,  82, 12),
        ("Kevin Mbabu",          "DEF", "Fulham",              "Premier League",    29,  35, 1),
        ("Granit Xhaka",         "MID", "Bayer Leverkusen",    "Bundesliga",        32, 118, 28),
        ("Remo Freuler",         "MID", "Nottm Forest",        "Premier League",    32,  62, 8),
        ("Denis Zakaria",        "MID", "AS Monaco",           "Ligue 1",           27,  38, 3),
        ("Fabian Frei",          "MID", "Basel",               "Swiss Super League",35,  65, 8),
        ("Djibril Sow",          "MID", "Eintracht Frankfurt", "Bundesliga",        27,  38, 4),
        ("Ruben Vargas",         "MID", "Augsburg",            "Bundesliga",        25,  32, 5),
        ("Michel Aebischer",     "MID", "Bologna",             "Serie A",           27,  28, 2),
        ("Xherdan Shaqiri",      "FWD", "Chicago Fire",        "MLS",               33,  98, 32),
        ("Breel Embolo",         "FWD", "AS Monaco",           "Ligue 1",           27,  65, 20),
        ("Noah Okafor",          "FWD", "AC Milan",            "Serie A",           24,  28, 8),
        ("Haris Seferovic",      "FWD", "Galatasaray",         "Turkish Süper Lig", 32,  88, 28),
        ("Dan Ndoye",            "FWD", "Bologna",             "Serie A",           24,  18, 5),
        ("Kwadwo Duah",          "FWD", "Ludogorets",          "Bulgarian Pro League",27, 15, 4),
        ("Zeki Amdouni",         "FWD", "Burnley",             "Championship",      24,  18, 5),
        ("Renato Steffen",       "MID", "Lugano",              "Swiss Super League",33,  42, 8),
        ("Cedric Itten",         "FWD", "Young Boys",          "Swiss Super League",28,  22, 6),
        ("Vincent Sierro",       "MID", "Toulouse",            "Ligue 1",           28,  18, 2),
    ],
    # ── GROUP C ──────────────────────────────────────────────────────────────
    "Brazil": [
        ("Alisson",              "GK",  "Liverpool",           "Premier League",    32,  78, 0),
        ("Ederson",              "GK",  "Man City",            "Premier League",    31,  32, 0),
        ("Weverton",             "GK",  "Palmeiras",           "Brasileirao",       36,  28, 0),
        ("Danilo",               "DEF", "Juventus",            "Serie A",           33,  85, 8),
        ("Marquinhos",           "DEF", "PSG",                 "Ligue 1",           30,  82, 12),
        ("Gabriel Magalhaes",    "DEF", "Arsenal",             "Premier League",    27,  35, 5),
        ("Eder Militao",         "DEF", "Real Madrid",         "La Liga",           26,  38, 3),
        ("Renan Lodi",           "DEF", "Nottm Forest",        "Premier League",    26,  25, 2),
        ("Alex Sandro",          "DEF", "Juventus",            "Serie A",           33,  45, 5),
        ("Guilherme Arana",      "DEF", "Atletico Mineiro",    "Brasileirao",       27,  22, 2),
        ("Bruno Guimaraes",      "MID", "Newcastle",           "Premier League",    27,  42, 8),
        ("Lucas Paqueta",        "MID", "West Ham",            "Premier League",    27,  55, 12),
        ("Casemiro",             "MID", "Man United",          "Premier League",    32,  85, 9),
        ("Gerson",               "MID", "Marseille",           "Ligue 1",           27,  22, 3),
        ("Andreas Pereira",      "MID", "Fulham",              "Premier League",    29,  15, 2),
        ("Rodrygo",              "FWD", "Real Madrid",         "La Liga",           24,  38, 15),
        ("Vinicius Junior",      "FWD", "Real Madrid",         "La Liga",           24,  55, 22),
        ("Gabriel Martinelli",   "FWD", "Arsenal",             "Premier League",    23,  32, 8),
        ("Raphinha",             "FWD", "Barcelona",           "La Liga",           28,  48, 18),
        ("Gabriel Jesus",        "FWD", "Arsenal",             "Premier League",    27,  62, 18),
        ("Richarlison",          "FWD", "Tottenham",           "Premier League",    27,  52, 22),
        ("Endrick",              "FWD", "Real Madrid",         "La Liga",           18,  12, 6),
        ("Matheus Cunha",        "FWD", "Wolves",              "Premier League",    25,  22, 5),
        ("Savinho",              "FWD", "Man City",            "Premier League",    21,  10, 3),
        ("Joao Gomes",           "MID", "Wolves",              "Premier League",    23,  15, 1),
        ("Yan Couto",            "DEF", "Man City",            "Premier League",    22,  10, 0),
    ],
    "Morocco": [
        ("Yassine Bounou",       "GK",  "Al Hilal",            "Saudi Pro League",  33,  55, 0),
        ("Ahmed Tagnaouti",      "GK",  "Raja Casablanca",     "Botola Pro",        27,  22, 0),
        ("Munir Mohamedi",       "GK",  "Malaga",              "Segunda Division",  32,  28, 0),
        ("Achraf Hakimi",        "DEF", "PSG",                 "Ligue 1",           26,  68, 8),
        ("Romain Saiss",         "DEF", "Besiktas",            "Turkish Süper Lig", 34,  72, 5),
        ("Nayef Aguerd",         "DEF", "West Ham",            "Premier League",    28,  48, 2),
        ("Noussair Mazraoui",    "DEF", "Man United",          "Premier League",    27,  38, 2),
        ("Badr Benoun",          "DEF", "Qatar SC",            "Qatar Stars League",28,  28, 1),
        ("Yahia Jabrane",        "DEF", "Wydad",               "Botola Pro",        33,  42, 2),
        ("Jawad El Yamiq",       "DEF", "Real Valladolid",     "La Liga",           32,  35, 2),
        ("Sofyan Amrabat",       "MID", "Fiorentina",          "Serie A",           28,  58, 3),
        ("Azzedine Ounahi",      "MID", "Marseille",           "Ligue 1",           24,  32, 4),
        ("Selim Amallah",        "MID", "Standard Liege",      "Pro League",        27,  28, 5),
        ("Hakim Ziyech",         "MID", "Galatasaray",         "Turkish Süper Lig", 32,  62, 18),
        ("Ilias Chair",          "MID", "QPR",                 "Championship",      27,  22, 4),
        ("Bilal El Khannouss",   "MID", "Genk",                "Pro League",        20,  18, 3),
        ("Youssef En-Nesyri",    "FWD", "Fenerbahce",          "Turkish Süper Lig", 27,  55, 22),
        ("Abderrazak Hamdallah", "FWD", "Al-Ittihad",          "Saudi Pro League",  34,  48, 22),
        ("Zakaria Aboukhlal",    "FWD", "Toulouse",            "Ligue 1",           24,  28, 8),
        ("Soufiane Rahimi",      "FWD", "Al Ain",              "UAE Pro League",    26,  22, 10),
        ("Amine Harit",          "FWD", "Marseille",           "Ligue 1",           27,  28, 5),
        ("Ayoub El Kaabi",       "FWD", "Olympiakos",          "Super League Greece",28, 25, 10),
        ("Abde Ezzalzouli",      "FWD", "Osasuna",             "La Liga",           23,  18, 5),
        ("Yassine En-Nesyri",    "MID", "Toulouse",            "Ligue 1",           21,   8, 2),
        ("Yahya Attiat-Allah",   "DEF", "Wydad",               "Botola Pro",        30,  28, 1),
        ("Imrane Louza",         "MID", "Watford",             "Championship",      25,  22, 4),
    ],
    # ── GROUP D ──────────────────────────────────────────────────────────────
    "USA": [
        ("Matt Turner",          "GK",  "Nottm Forest",        "Premier League",    30,  38, 0),
        ("Ethan Horvath",        "GK",  "Luton Town",          "Championship",      29,  22, 0),
        ("Patrick Schulte",      "GK",  "Columbus Crew",       "MLS",               24,   8, 0),
        ("Sergino Dest",         "DEF", "PSV Eindhoven",       "Eredivisie",        24,  42, 5),
        ("Walker Zimmerman",     "DEF", "Nashville SC",        "MLS",               31,  38, 2),
        ("Miles Robinson",       "DEF", "FC Cincinnati",       "MLS",               27,  28, 3),
        ("Antonee Robinson",     "DEF", "Fulham",              "Premier League",    27,  42, 2),
        ("Tim Ream",             "DEF", "Fulham",              "Premier League",    37,  52, 1),
        ("Cameron Carter-Vickers","DEF","Celtic",              "Scottish Prem",     26,  22, 1),
        ("Joe Scally",           "DEF", "Borussia Monchengladbach","Bundesliga",    22,  18, 0),
        ("Tyler Adams",          "MID", "Bournemouth",         "Premier League",    26,  58, 2),
        ("Yunus Musah",          "MID", "AC Milan",            "Serie A",           22,  38, 3),
        ("Brenden Aaronson",     "MID", "Leeds United",        "Championship",      24,  42, 8),
        ("Luca de la Torre",     "MID", "Celta Vigo",          "La Liga",           26,  28, 3),
        ("Christian Pulisic",    "MID", "AC Milan",            "Serie A",           26,  72, 28),
        ("Weston McKennie",      "MID", "Leeds United",        "Championship",      25,  55, 15),
        ("Josh Sargent",         "FWD", "Norwich City",        "Championship",      24,  38, 15),
        ("Ricardo Pepi",         "FWD", "PSV Eindhoven",       "Eredivisie",        22,  32, 12),
        ("Folarin Balogun",      "FWD", "AS Monaco",           "Ligue 1",           23,  22, 8),
        ("Jordan Morris",        "FWD", "Seattle Sounders",    "MLS",               29,  52, 12),
        ("Gio Reyna",            "FWD", "Borussia Dortmund",   "Bundesliga",        22,  32, 8),
        ("Tim Weah",             "FWD", "Juventus",            "Serie A",           24,  38, 10),
        ("Malik Tillman",        "MID", "PSV Eindhoven",       "Eredivisie",        23,  22, 5),
        ("Caden Clark",          "MID", "RB Leipzig",          "Bundesliga",        22,  18, 3),
        ("Brandon Vazquez",      "FWD", "FC Cincinnati",       "MLS",               25,  15, 6),
        ("Jonathan Gomez",       "DEF", "Real Sociedad",       "La Liga",           22,  18, 1),
    ],
    "Turkey": [
        ("Altay Bayindir",       "GK",  "Man United",          "Premier League",    26,  18, 0),
        ("Mert Gunok",           "GK",  "Besiktas",            "Turkish Süper Lig", 35,  32, 0),
        ("Dogan Alemdar",        "GK",  "Stade Rennais",       "Ligue 1",           21,   8, 0),
        ("Zeki Celik",           "DEF", "AS Roma",             "Serie A",           27,  42, 2),
        ("Merih Demiral",        "DEF", "Al-Ahli",             "Saudi Pro League",  26,  45, 3),
        ("Samet Akaydin",        "DEF", "Besiktas",            "Turkish Süper Lig", 28,  22, 1),
        ("Ferdi Kadioglu",       "DEF", "Fenerbahce",          "Turkish Süper Lig", 25,  32, 2),
        ("Abdulkerim Bardakci",  "DEF", "Galatasaray",         "Turkish Süper Lig", 27,  22, 1),
        ("Mert Muldur",          "DEF", "Fenerbahce",          "Turkish Süper Lig", 26,  28, 1),
        ("Salih Ozcan",          "MID", "Borussia Dortmund",   "Bundesliga",        26,  28, 3),
        ("Kaan Ayhan",           "MID", "Galatasaray",         "Turkish Süper Lig", 29,  42, 3),
        ("Hakan Calhanoglu",     "MID", "Internazionale",      "Serie A",           30,  82, 22),
        ("Orkun Kokcu",          "MID", "Benfica",             "Primeira Liga",     24,  32, 8),
        ("Arda Guler",           "MID", "Real Madrid",         "La Liga",           20,  18, 5),
        ("Kenan Yildiz",         "MID", "Juventus",            "Serie A",           20,  12, 4),
        ("Ismail Yuksek",        "MID", "Fenerbahce",          "Turkish Süper Lig", 24,  15, 2),
        ("Cenk Tosun",           "FWD", "Besiktas",            "Turkish Süper Lig", 33,  68, 28),
        ("Cengiz Under",         "FWD", "Marseille",           "Ligue 1",           27,  58, 15),
        ("Yusuf Yazici",         "FWD", "LOSC Lille",          "Ligue 1",           28,  48, 14),
        ("Yunus Akgun",          "FWD", "Galatasaray",         "Turkish Süper Lig", 24,  22, 5),
        ("Kerem Aktürkoglu",     "FWD", "Galatasaray",         "Turkish Süper Lig", 26,  22, 8),
        ("Baris Yilmaz",         "FWD", "Fatih Karagumruk",    "Turkish Süper Lig", 25,  12, 3),
        ("Muhammed Cham",        "FWD", "Besiktas",            "Turkish Süper Lig", 22,   8, 2),
        ("Ozan Kabak",           "DEF", "Hoffenheim",          "Bundesliga",        25,  22, 1),
        ("Berkan Kutlu",         "MID", "Galatasaray",         "Turkish Süper Lig", 26,  18, 2),
        ("Irfan Can Kahveci",    "MID", "Fenerbahce",          "Turkish Süper Lig", 29,  38, 8),
    ],
    # ── GROUP E ──────────────────────────────────────────────────────────────
    "Germany": [
        ("Manuel Neuer",         "GK",  "Bayern Munich",       "Bundesliga",        39, 120, 1),
        ("Marc-Andre ter Stegen","GK",  "Barcelona",           "La Liga",           32,  42, 0),
        ("Oliver Baumann",       "GK",  "Hoffenheim",          "Bundesliga",        34,  12, 0),
        ("Antonio Rudiger",      "DEF", "Real Madrid",         "La Liga",           31,  75, 3),
        ("Jonathan Tah",         "DEF", "Bayer Leverkusen",    "Bundesliga",        28,  30, 2),
        ("Benjamin Pavard",      "DEF", "Internazionale",      "Serie A",           28,  52, 4),
        ("David Raum",           "DEF", "RB Leipzig",          "Bundesliga",        26,  30, 5),
        ("Maximilian Mittelstadt","DEF","Stuttgart",           "Bundesliga",        27,  18, 2),
        ("Nico Schlotterbeck",   "DEF", "Borussia Dortmund",   "Bundesliga",        25,  22, 1),
        ("Leon Goretzka",        "MID", "Bayern Munich",       "Bundesliga",        29,  55, 15),
        ("Florian Wirtz",        "MID", "Bayer Leverkusen",    "Bundesliga",        21,  25, 8),
        ("Jamal Musiala",        "MID", "Bayern Munich",       "Bundesliga",        22,  35, 12),
        ("Ilkay Gundogan",       "MID", "Man City",            "Premier League",    34,  75, 18),
        ("Joshua Kimmich",       "MID", "Bayern Munich",       "Bundesliga",        29,  85, 8),
        ("Robert Andrich",       "MID", "Bayer Leverkusen",    "Bundesliga",        30,  22, 3),
        ("Pascal Gross",         "MID", "Brighton",            "Premier League",    33,  22, 4),
        ("Leroy Sane",           "FWD", "Bayern Munich",       "Bundesliga",        29,  60, 15),
        ("Kai Havertz",          "FWD", "Arsenal",             "Premier League",    25,  55, 22),
        ("Niclas Fullkrug",      "FWD", "West Ham",            "Premier League",    31,  25, 12),
        ("Thomas Muller",        "FWD", "Bayern Munich",       "Bundesliga",        35,  131,45),
        ("Serge Gnabry",         "FWD", "Bayern Munich",       "Bundesliga",        29,  45, 22),
        ("Deniz Undav",          "FWD", "Stuttgart",           "Bundesliga",        28,  18, 6),
        ("Chris Fuhrich",        "FWD", "Stuttgart",           "Bundesliga",        26,  12, 3),
        ("Maximilian Beier",     "FWD", "Borussia Dortmund",   "Bundesliga",        22,  10, 3),
        ("Granit Xhaka",         "MID", "Bayer Leverkusen",    "Bundesliga",        32,  12, 2),
        ("Angelo Stiller",       "MID", "Stuttgart",           "Bundesliga",        23,  10, 1),
    ],
    "Ecuador": [
        ("Hernan Galindez",      "GK",  "Aucas",               "LigaPro Ecuador",   37,  55, 0),
        ("Alexander Dominguez",  "GK",  "LDU Quito",           "LigaPro Ecuador",   38,  82, 0),
        ("Moises Ramirez",       "GK",  "Independiente del Valle","LigaPro Ecuador", 26,  18, 0),
        ("Felix Torres",         "DEF", "Columbus Crew",       "MLS",               27,  38, 3),
        ("Piero Hincapie",       "DEF", "Bayer Leverkusen",    "Bundesliga",        22,  32, 1),
        ("Jackson Porozo",       "DEF", "Troyes",              "Ligue 2",           23,  22, 0),
        ("Pervis Estupinan",     "DEF", "Brighton",            "Premier League",    26,  42, 3),
        ("Angelo Preciado",      "DEF", "Racing Club de Strasbourg","Ligue 1",      26,  32, 2),
        ("Diego Palacios",       "DEF", "Portland Timbers",    "MLS",               26,  22, 1),
        ("Moises Caicedo",       "MID", "Chelsea",             "Premier League",    22,  42, 3),
        ("Carlos Gruezo",        "MID", "FC Augsburg",         "Bundesliga",        30,  58, 3),
        ("Romario Ibarra",       "MID", "Pachuca",             "Liga MX",           29,  42, 8),
        ("Angel Mena",           "MID", "Leon",                "Liga MX",           35,  68, 15),
        ("Gonzalo Plata",        "MID", "Real Valladolid",     "La Liga",           23,  35, 6),
        ("Jeremy Sarmiento",     "MID", "Brighton",            "Premier League",    22,  22, 4),
        ("Alan Franco",          "MID", "Talleres",            "Superliga Argentina",27, 25, 3),
        ("Enner Valencia",       "FWD", "Fenerbahce",          "Turkish Süper Lig", 34,  92, 38),
        ("Michael Estrada",      "FWD", "Cruz Azul",           "Liga MX",           28,  38, 12),
        ("Djorkaeff Reasco",     "FWD", "Independiente del Valle","LigaPro Ecuador",24, 18, 5),
        ("Jordy Caicedo",        "FWD", "Timbers",             "MLS",               31,  35, 10),
        ("Kevin Rodriguez",      "FWD", "Imbabura SC",         "LigaPro Ecuador",   23,  12, 4),
        ("Leonardo Campana",     "FWD", "Inter Miami",         "MLS",               24,  28, 8),
        ("Joao Rojas",           "FWD", "Independiente del Valle","LigaPro Ecuador",31, 38, 10),
        ("Jhegson Mendez",       "MID", "LA Galaxy",           "MLS",               27,  25, 2),
        ("Robert Arboleda",      "DEF", "Sao Paulo",           "Brasileirao",       33,  45, 3),
        ("Jose Cifuentes",       "MID", "Leeds United",        "Championship",      25,  22, 3),
    ],
    # ── GROUP F ──────────────────────────────────────────────────────────────
    "Netherlands": [
        ("Mark Flekken",         "GK",  "Brentford",           "Premier League",    31,  12, 0),
        ("Bart Verbruggen",      "GK",  "Brighton",            "Premier League",    22,  10, 0),
        ("Remko Pasveer",        "GK",  "Ajax",                "Eredivisie",        40,  10, 0),
        ("Virgil van Dijk",      "DEF", "Liverpool",           "Premier League",    33,  68, 8),
        ("Matthijs de Ligt",     "DEF", "Man United",          "Premier League",    25,  45, 3),
        ("Denzel Dumfries",      "DEF", "Internazionale",      "Serie A",           28,  48, 6),
        ("Nathan Ake",           "DEF", "Man City",            "Premier League",    30,  42, 4),
        ("Jurrien Timber",       "DEF", "Arsenal",             "Premier League",    23,  22, 1),
        ("Stefan de Vrij",       "DEF", "Internazionale",      "Serie A",           33,  48, 3),
        ("Frenkie de Jong",      "MID", "Barcelona",           "La Liga",           27,  62, 8),
        ("Tijjani Reijnders",    "MID", "AC Milan",            "Serie A",           26,  25, 5),
        ("Teun Koopmeiners",     "MID", "Juventus",            "Serie A",           26,  22, 5),
        ("Ryan Gravenberch",     "MID", "Liverpool",           "Premier League",    22,  18, 2),
        ("Xavi Simons",          "MID", "RB Leipzig",          "Bundesliga",        22,  18, 4),
        ("Quinten Timber",       "MID", "Feyenoord",           "Eredivisie",        22,  10, 2),
        ("Jerdy Schouten",       "MID", "Bologna",             "Serie A",           27,  15, 2),
        ("Cody Gakpo",           "FWD", "Liverpool",           "Premier League",    25,  32, 12),
        ("Memphis Depay",        "FWD", "Atletico Madrid",     "La Liga",           30,  92, 45),
        ("Donyell Malen",        "FWD", "Borussia Dortmund",   "Bundesliga",        25,  32, 10),
        ("Steven Bergwijn",      "FWD", "Ajax",                "Eredivisie",        26,  32, 8),
        ("Wout Weghorst",        "FWD", "Hoffenheim",          "Bundesliga",        32,  45, 18),
        ("Brian Brobbey",        "FWD", "Ajax",                "Eredivisie",        23,  12, 4),
        ("Noa Lang",             "FWD", "Bruges",              "Pro League",        25,  12, 4),
        ("Daley Blind",          "DEF", "Girona",              "La Liga",           34,  98, 5),
        ("Micky van de Ven",     "DEF", "Tottenham",           "Premier League",    23,  10, 0),
        ("Ian Maatsen",          "DEF", "Borussia Dortmund",   "Bundesliga",        22,  10, 1),
    ],
    "Japan": [
        ("Shuichi Gonda",        "GK",  "Shimizu S-Pulse",     "J1 League",         35,  58, 0),
        ("Zion Suzuki",          "GK",  "Sint-Truiden",        "Pro League",        22,  12, 0),
        ("Kosei Tani",           "GK",  "Shonan Bellmare",     "J1 League",         22,   8, 0),
        ("Takehiro Tomiyasu",    "DEF", "Arsenal",             "Premier League",    26,  42, 2),
        ("Ko Itakura",           "DEF", "Borussia Monchengladbach","Bundesliga",    27,  28, 2),
        ("Maya Yoshida",         "DEF", "FC Schalke 04",       "Bundesliga 2",      36,  128,6),
        ("Yuto Nagatomo",        "DEF", "FC Tokyo",            "J1 League",         38,  145,4),
        ("Hiroki Ito",           "DEF", "Stuttgart",           "Bundesliga",        25,  18, 1),
        ("Shogo Taniguchi",      "DEF", "Kawasaki Frontale",   "J1 League",         32,  22, 2),
        ("Wataru Endo",          "MID", "Liverpool",           "Premier League",    31,  48, 3),
        ("Hidemasa Morita",      "MID", "Sporting CP",         "Primeira Liga",     29,  35, 4),
        ("Junya Ito",            "MID", "Stade Reims",         "Ligue 1",           31,  55, 12),
        ("Kaoru Mitoma",         "MID", "Brighton",            "Premier League",    27,  32, 8),
        ("Daichi Kamada",        "MID", "Crystal Palace",      "Premier League",    28,  42, 12),
        ("Takefusa Kubo",        "MID", "Real Sociedad",       "La Liga",           23,  28, 8),
        ("Ao Tanaka",            "MID", "Fortuna Dusseldorf",  "Bundesliga 2",      26,  22, 3),
        ("Ritsu Doan",           "FWD", "Freiburg",            "Bundesliga",        26,  45, 15),
        ("Ayase Ueda",           "FWD", "Feyenoord",           "Eredivisie",        26,  22, 10),
        ("Keito Nakamura",       "FWD", "Stade Reims",         "Ligue 1",           24,  18, 5),
        ("Koki Machida",         "DEF", "Union Saint-Gilloise","Pro League",        26,  18, 1),
        ("Takuma Asano",         "FWD", "Bochum",              "Bundesliga",        29,  38, 12),
        ("Takumi Minamino",      "FWD", "AS Monaco",           "Ligue 1",           29,  62, 22),
        ("Yukinari Sugawara",    "DEF", "AZ Alkmaar",          "Eredivisie",        24,  15, 1),
        ("Yoshiki Nishi",        "DEF", "Gamba Osaka",         "J1 League",         21,   8, 0),
        ("Keijiro Ogawa",        "DEF", "Urawa Reds",          "J1 League",         26,  12, 0),
        ("Shuto Machino",        "FWD", "Shonan Bellmare",     "J1 League",         25,  12, 4),
    ],
    # ── GROUP G ──────────────────────────────────────────────────────────────
    "Belgium": [
        ("Thibaut Courtois",     "GK",  "Real Madrid",         "La Liga",           32,  102,0),
        ("Koen Casteels",        "GK",  "VfL Wolfsburg",       "Bundesliga",        32,  22, 0),
        ("Thomas Kaminski",      "GK",  "Luton Town",          "Championship",      32,  15, 0),
        ("Toby Alderweireld",    "DEF", "Royal Antwerp",       "Pro League",        36,  127,5),
        ("Jan Vertonghen",       "DEF", "Anderlecht",          "Pro League",        37,  145,8),
        ("Timothy Castagne",     "DEF", "Fulham",              "Premier League",    28,  48, 3),
        ("Wout Faes",            "DEF", "Leicester City",      "Championship",      26,  22, 1),
        ("Arthur Theate",        "DEF", "Stade Rennais",       "Ligue 1",           24,  25, 1),
        ("Thomas Meunier",       "DEF", "Trabzonspor",         "Turkish Süper Lig", 32,  78, 10),
        ("Kevin De Bruyne",      "MID", "Man City",            "Premier League",    33,  102,26),
        ("Axel Witsel",          "MID", "Atletico Madrid",     "La Liga",           35,  130,12),
        ("Youri Tielemans",      "MID", "Aston Villa",         "Premier League",    27,  68, 12),
        ("Leandro Trossard",     "MID", "Arsenal",             "Premier League",    29,  42, 10),
        ("Amadou Onana",         "MID", "Aston Villa",         "Premier League",    23,  28, 3),
        ("Charles De Ketelaere", "MID", "Atalanta",            "Serie A",           23,  22, 4),
        ("Orel Mangala",         "MID", "Nottm Forest",        "Premier League",    26,  18, 2),
        ("Romelu Lukaku",        "FWD", "AS Roma",             "Serie A",           31,  112,78),
        ("Dodi Lukebakio",       "FWD", "Hertha Berlin",       "Bundesliga 2",      26,  22, 6),
        ("Lois Openda",          "FWD", "RB Leipzig",          "Bundesliga",        24,  18, 6),
        ("Jeremy Doku",          "FWD", "Man City",            "Premier League",    22,  22, 6),
        ("Alexis Saelemaekers",  "FWD", "AC Milan",            "Serie A",           25,  32, 4),
        ("Johan Bakayoko",       "FWD", "PSV Eindhoven",       "Eredivisie",        22,  12, 4),
        ("Loic Bade",            "DEF", "Sevilla",             "La Liga",           24,  10, 0),
        ("Maxim De Cuyper",      "DEF", "Club Brugge",         "Pro League",        23,  10, 1),
        ("Arthur Vermeeren",     "MID", "Atletico Madrid",     "La Liga",           19,   8, 1),
        ("Hugo Siquet",          "DEF", "Freiburg",            "Bundesliga",        22,  10, 0),
    ],
    "Iran": [
        ("Alireza Beiranvand",   "GK",  "Antwerp",             "Pro League",        32,  78, 0),
        ("Poria Ghorbani",       "GK",  "Persepolis",          "IPL",               30,  22, 0),
        ("Payam Niazmand",       "GK",  "Sepahan",             "IPL",               28,  10, 0),
        ("Ehsan Hajsafi",        "DEF", "AEK Athens",          "Super League Greece",33, 125,8),
        ("Majid Hosseini",       "DEF", "Trabzonspor",         "Turkish Süper Lig", 26,  38, 1),
        ("Mohammad Hosseini",    "DEF", "Persepolis",          "IPL",               27,  28, 0),
        ("Shojae Khalilzadeh",   "DEF", "Esteghlal",           "IPL",               28,  22, 1),
        ("Milad Mohammadi",      "DEF", "Gent",                "Pro League",        30,  42, 2),
        ("Sadegh Moharrami",     "DEF", "Dinamo Zagreb",       "HNL",               28,  28, 1),
        ("Saeid Ezatolahi",      "MID", "Qarabag",             "Azerbaijani Premier League",27,45,4),
        ("Ali Gholizadeh",       "MID", "Charleroi",           "Pro League",        27,  38, 8),
        ("Mehdi Torabi",         "MID", "Persepolis",          "IPL",               30,  42, 10),
        ("Vahid Amiri",          "MID", "Persepolis",          "IPL",               34,  58, 10),
        ("Ahmad Noorollahi",     "MID", "Persepolis",          "IPL",               30,  38, 5),
        ("Ali Karimi",           "MID", "Maastricht",          "Eerste Divisie",    21,  18, 3),
        ("Omid Noorafkan",       "MID", "Esteghlal",           "IPL",               28,  22, 3),
        ("Mehdi Taremi",         "FWD", "Internazionale",      "Serie A",           32,  82, 45),
        ("Sardar Azmoun",        "FWD", "Bayer Leverkusen",    "Bundesliga",        29,  68, 42),
        ("Allahyar Sayyadmanesh","FWD", "Hull City",           "Championship",      24,  28, 8),
        ("Karim Ansarifard",     "FWD", "Nottingham Forest",   "Premier League",    34,  68, 30),
        ("Reza Ghoochannejhad",  "FWD", "Al-Faisaly",          "Saudi First Division",35, 55, 30),
        ("Farhad Majidi",        "FWD", "Persepolis",          "IPL",               24,  15, 5),
        ("Mohammad Gholami",     "DEF", "Al-Ittihad",          "Saudi Pro League",  25,  18, 0),
        ("Shahriar Moghanlou",   "MID", "Sepahan",             "IPL",               26,  15, 2),
        ("Saman Ghoddos",        "MID", "Brentford",           "Premier League",    30,  55, 12),
        ("Alireza Jahanbakhsh",  "FWD", "Feyenoord",           "Eredivisie",        31,  82, 22),
    ],
    # ── GROUP H ──────────────────────────────────────────────────────────────
    "Spain": [
        ("Unai Simon",           "GK",  "Athletic Bilbao",     "La Liga",           27,  28, 0),
        ("David Raya",           "GK",  "Arsenal",             "Premier League",    29,  18, 0),
        ("Alex Remiro",          "GK",  "Real Sociedad",       "La Liga",           28,  10, 0),
        ("Dani Carvajal",        "DEF", "Real Madrid",         "La Liga",           32,  70, 6),
        ("Robin Le Normand",     "DEF", "Real Sociedad",       "La Liga",           27,  12, 0),
        ("Aymeric Laporte",      "DEF", "Al-Nassr",            "Saudi Pro League",  30,  42, 2),
        ("Alejandro Balde",      "DEF", "Barcelona",           "La Liga",           21,  18, 1),
        ("Pau Cubarsi",          "DEF", "Barcelona",           "La Liga",           18,  10, 0),
        ("Marc Cucurella",       "DEF", "Chelsea",             "Premier League",    26,  30, 2),
        ("Nacho Fernandez",      "DEF", "Real Madrid",         "La Liga",           34,  62, 2),
        ("Rodri",                "MID", "Man City",            "Premier League",    28,  55, 7),
        ("Pedri",                "MID", "Barcelona",           "La Liga",           22,  35, 6),
        ("Fabian Ruiz",          "MID", "PSG",                 "Ligue 1",           28,  38, 12),
        ("Gavi",                 "MID", "Barcelona",           "La Liga",           20,  42, 4),
        ("Martin Zubimendi",     "MID", "Real Sociedad",       "La Liga",           25,  15, 1),
        ("Mikel Merino",         "MID", "Arsenal",             "Premier League",    28,  22, 3),
        ("Lamine Yamal",         "FWD", "Barcelona",           "La Liga",           17,  18, 8),
        ("Nico Williams",        "FWD", "Athletic Bilbao",     "La Liga",           22,  18, 6),
        ("Alvaro Morata",        "FWD", "AC Milan",            "Serie A",           32,  72, 35),
        ("Joselu",               "FWD", "Real Madrid",         "La Liga",           34,  12, 5),
        ("Ferran Torres",        "FWD", "Barcelona",           "La Liga",           24,  42, 15),
        ("Dani Olmo",            "FWD", "Barcelona",           "La Liga",           27,  42, 12),
        ("Bryan Gil",            "FWD", "Tottenham",           "Premier League",    23,  15, 3),
        ("Yeremy Pino",          "FWD", "Villarreal",          "La Liga",           22,  18, 4),
        ("Alex Baena",           "MID", "Villarreal",          "La Liga",           23,  12, 3),
        ("Joselu Mato",          "FWD", "Al-Qadsiah",          "Saudi Pro League",  34,  12, 5),
    ],
    "Uruguay": [
        ("Fernando Muslera",     "GK",  "Galatasaray",         "Turkish Süper Lig", 38, 145, 0),
        ("Sergio Rochet",        "GK",  "Internacional",       "Brasileirao",       30,  32, 0),
        ("Santiago Mele",        "GK",  "Junior",              "Liga Betplay Colombia",26,8, 0),
        ("Jose Maria Gimenez",   "DEF", "Atletico Madrid",     "La Liga",           29,  78, 5),
        ("Ronald Araujo",        "DEF", "Barcelona",           "La Liga",           25,  32, 2),
        ("Mathias Olivera",      "DEF", "Napoli",              "Serie A",           27,  28, 1),
        ("Martin Caceres",       "DEF", "CA Fenix",            "Uruguayan Primera", 37,  115,4),
        ("Sebastian Coates",     "DEF", "Sporting CP",         "Primeira Liga",     33,  55, 4),
        ("Nahitan Nandez",       "DEF", "Cagliari",            "Serie A",           28,  45, 2),
        ("Federico Valverde",    "MID", "Real Madrid",         "La Liga",           26,  55, 12),
        ("Rodrigo Bentancur",    "MID", "Tottenham",           "Premier League",    27,  58, 8),
        ("Nicolas de la Cruz",   "MID", "River Plate",         "Superliga Argentina",27, 38, 6),
        ("Lucas Torreira",       "MID", "Galatasaray",         "Turkish Süper Lig", 28,  52, 5),
        ("Matias Vecino",        "MID", "Lazio",               "Serie A",           33,  72, 8),
        ("Manuel Ugarte",        "MID", "PSG",                 "Ligue 1",           23,  18, 1),
        ("Facundo Pellistri",    "MID", "Man United",          "Premier League",    23,  22, 3),
        ("Darwin Nunez",         "FWD", "Liverpool",           "Premier League",    25,  45, 22),
        ("Luis Suarez",          "FWD", "Inter Miami",         "MLS",               37, 142, 68),
        ("Edinson Cavani",       "FWD", "Boca Juniors",        "Superliga Argentina",37,134,58),
        ("Facundo Torres",       "FWD", "Orlando City",        "MLS",               24,  22, 8),
        ("Maximiliano Gomez",    "FWD", "Celta Vigo",          "La Liga",           27,  38, 12),
        ("Brian Rodriguez",      "FWD", "LA FC",               "MLS",               24,  22, 5),
        ("Mauro Arambarri",      "MID", "Getafe",              "La Liga",           28,  22, 2),
        ("Giorgian De Arrascaeta","MID","Flamengo",            "Brasileirao",       30,  52, 15),
        ("Diego Godin",          "DEF", "Velez Sarsfield",     "Superliga Argentina",38, 160,8),
        ("Nicolas Lodeiro",      "MID", "Seattle Sounders",    "MLS",               35,  68, 15),
    ],
    # ── GROUP I ──────────────────────────────────────────────────────────────
    "France": [
        ("Mike Maignan",         "GK",  "AC Milan",            "Serie A",           29,  25, 0),
        ("Alphonse Areola",      "GK",  "West Ham",            "Premier League",    31,  12, 0),
        ("Brice Samba",          "GK",  "Lens",                "Ligue 1",           30,   8, 0),
        ("Jules Kounde",         "DEF", "Barcelona",           "La Liga",           26,  42, 1),
        ("Dayot Upamecano",      "DEF", "Bayern Munich",       "Bundesliga",        26,  42, 2),
        ("William Saliba",       "DEF", "Arsenal",             "Premier League",    23,  25, 1),
        ("Ibrahima Konate",      "DEF", "Liverpool",           "Premier League",    25,  18, 1),
        ("Theo Hernandez",       "DEF", "AC Milan",            "Serie A",           27,  38, 5),
        ("Lucas Hernandez",      "DEF", "Bayern Munich",       "Bundesliga",        28,  42, 1),
        ("Benjamin Pavard",      "DEF", "Internazionale",      "Serie A",           28,  45, 3),
        ("Aurelien Tchouameni",  "MID", "Real Madrid",         "La Liga",           24,  38, 4),
        ("Adrien Rabiot",        "MID", "Juventus",            "Serie A",           29,  45, 12),
        ("Eduardo Camavinga",    "MID", "Real Madrid",         "La Liga",           22,  22, 2),
        ("Antoine Griezmann",    "MID", "Atletico Madrid",     "La Liga",           33, 132, 44),
        ("Khephren Thuram",      "MID", "Juventus",            "Serie A",           23,  12, 2),
        ("Warren Zaire-Emery",   "MID", "PSG",                 "Ligue 1",           18,   8, 1),
        ("Kylian Mbappe",        "FWD", "Real Madrid",         "La Liga",           26,  82, 48),
        ("Ousmane Dembele",      "FWD", "PSG",                 "Ligue 1",           27,  45, 12),
        ("Marcus Thuram",        "FWD", "Internazionale",      "Serie A",           27,  35, 12),
        ("Randal Kolo Muani",    "FWD", "PSG",                 "Ligue 1",           25,  22, 8),
        ("Christopher Nkunku",   "FWD", "Chelsea",             "Premier League",    27,  18, 6),
        ("Kingsley Coman",       "FWD", "Bayern Munich",       "Bundesliga",        28,  58, 12),
        ("Olivier Giroud",       "FWD", "Los Angeles FC",      "MLS",               38,  132,57),
        ("Youssouf Fofana",      "MID", "AS Monaco",           "Ligue 1",           25,  18, 2),
        ("Jonathan Clauss",      "DEF", "Marseille",           "Ligue 1",           32,  12, 1),
        ("Bradley Barcola",      "FWD", "PSG",                 "Ligue 1",           22,  10, 3),
    ],
    "Senegal": [
        ("Edouard Mendy",        "GK",  "Chelsea",             "Premier League",    32,  38, 0),
        ("Seny Dieng",           "GK",  "Middlesbrough",       "Championship",      31,  22, 0),
        ("Alfred Gomis",         "GK",  "Rennes",              "Ligue 1",           32,  18, 0),
        ("Kalidou Koulibaly",    "DEF", "Al-Hilal",            "Saudi Pro League",  33,  75, 5),
        ("Abdou Diallo",         "DEF", "RB Leipzig",          "Bundesliga",        28,  38, 0),
        ("Formose Mendy",        "DEF", "Amiens SC",           "Ligue 2",           27,  22, 0),
        ("Pape Abou Cisse",      "DEF", "Olympiakos",          "Super League Greece",28,28, 2),
        ("Lamine Camara",        "MID", "AS Monaco",           "Ligue 1",           21,  12, 2),
        ("Idrissa Gueye",        "MID", "Everton",             "Premier League",    35,  102,4),
        ("Cheikhou Kouyate",     "MID", "Nottm Forest",        "Premier League",    34,  88, 8),
        ("Pathe Ciss",           "MID", "Rayo Vallecano",      "La Liga",           29,  38, 3),
        ("Nampalys Mendy",       "MID", "Lorient",             "Ligue 1",           32,  38, 2),
        ("Pape Matar Sarr",      "MID", "Tottenham",           "Premier League",    22,  22, 3),
        ("Krepin Diatta",        "FWD", "AS Monaco",           "Ligue 1",           25,  32, 8),
        ("Nicolas Jackson",      "FWD", "Chelsea",             "Premier League",    23,  12, 4),
        ("Sadio Mane",           "FWD", "Al-Nassr",            "Saudi Pro League",  32,  98, 35),
        ("Ismaila Sarr",         "FWD", "Crystal Palace",      "Premier League",    27,  52, 18),
        ("Habib Diallo",         "FWD", "Al-Shabab",           "Saudi Pro League",  29,  42, 22),
        ("Boulaye Dia",          "FWD", "Salernitana",         "Serie A",           27,  28, 10),
        ("Iliman Ndiaye",        "FWD", "Everton",             "Premier League",    24,  18, 5),
        ("Abdallah Sima",        "FWD", "Brighton",            "Premier League",    23,  15, 4),
        ("Mamadou Loum",         "MID", "Deportivo Alaves",    "La Liga",           28,  22, 2),
        ("Moussa Niakhate",      "DEF", "Nottm Forest",        "Premier League",    28,  22, 1),
        ("Ismail Jakobs",        "DEF", "AS Monaco",           "Ligue 1",           24,  12, 1),
        ("Dion Lopy",            "MID", "Villarreal",          "La Liga",           23,  12, 2),
        ("Cherif Ndiaye",        "FWD", "Samsunspor",          "Turkish Süper Lig", 25,  10, 3),
    ],
    # ── GROUP J ──────────────────────────────────────────────────────────────
    "Argentina": [
        ("Emiliano Martinez",    "GK",  "Aston Villa",         "Premier League",    32,  45, 0),
        ("Geronimo Rulli",       "GK",  "Ajax",                "Eredivisie",        32,  18, 0),
        ("Franco Armani",        "GK",  "River Plate",         "Superliga Argentina",37, 15, 0),
        ("Nahuel Molina",        "DEF", "Atletico Madrid",     "La Liga",           27,  45, 5),
        ("Cristian Romero",      "DEF", "Tottenham",           "Premier League",    26,  35, 3),
        ("Nicolas Otamendi",     "DEF", "Benfica",             "Primeira Liga",     37,  105,8),
        ("Marcos Acuna",         "DEF", "Sevilla",             "La Liga",           33,  65, 3),
        ("Lisandro Martinez",    "DEF", "Man United",          "Premier League",    26,  28, 1),
        ("Nicolas Tagliafico",   "DEF", "Lyon",                "Ligue 1",           32,  72, 4),
        ("Gonzalo Montiel",      "DEF", "Nottm Forest",        "Premier League",    27,  38, 2),
        ("Rodrigo De Paul",      "MID", "Atletico Madrid",     "La Liga",           31,  72, 13),
        ("Alexis Mac Allister",  "MID", "Liverpool",           "Premier League",    26,  42, 10),
        ("Enzo Fernandez",       "MID", "Chelsea",             "Premier League",    24,  35, 5),
        ("Angel Di Maria",       "MID", "Benfica",             "Primeira Liga",     37,  145,31),
        ("Leandro Paredes",      "MID", "AS Roma",             "Serie A",           30,  52, 8),
        ("Guido Rodriguez",      "MID", "Betis",               "La Liga",           30,  38, 3),
        ("Exequiel Palacios",    "MID", "Bayer Leverkusen",    "Bundesliga",        26,  28, 4),
        ("Thiago Almada",        "MID", "Atlanta United",      "MLS",               23,  18, 4),
        ("Julian Alvarez",       "FWD", "Atletico Madrid",     "La Liga",           25,  45, 22),
        ("Lautaro Martinez",     "FWD", "Internazionale",      "Serie A",           27,  65, 30),
        ("Lionel Messi",         "FWD", "Inter Miami",         "MLS",               38,  187,109),
        ("Paulo Dybala",         "FWD", "AS Roma",             "Serie A",           31,  38, 12),
        ("Nicolas Gonzalez",     "FWD", "Fiorentina",          "Serie A",           26,  22, 5),
        ("Alejandro Garnacho",   "FWD", "Man United",          "Premier League",    20,  12, 4),
        ("Giovanni Lo Celso",    "MID", "Villarreal",          "La Liga",           28,  45, 6),
        ("Valentin Carboni",     "FWD", "Internazionale",      "Serie A",           19,   8, 2),
    ],
    "Austria": [
        ("Patrick Pentz",        "GK",  "Bayer Leverkusen",    "Bundesliga",        27,  18, 0),
        ("Daniel Bachmann",      "GK",  "Watford",             "Championship",      30,  18, 0),
        ("Heinz Lindner",        "GK",  "FC Basel",            "Swiss Super League",34,  22, 0),
        ("David Alaba",          "DEF", "Real Madrid",         "La Liga",           32,  98, 14),
        ("Stefan Posch",         "DEF", "Bologna",             "Serie A",           27,  25, 1),
        ("Phillipp Lienhart",    "DEF", "Freiburg",            "Bundesliga",        28,  25, 1),
        ("Maximilian Woeber",    "DEF", "Leeds United",        "Championship",      27,  25, 2),
        ("Gernot Trauner",       "DEF", "Feyenoord",           "Eredivisie",        31,  42, 3),
        ("Alexander Prass",      "DEF", "Sturm Graz",          "Austrian Bundesliga",25, 12, 1),
        ("Konrad Laimer",        "MID", "Bayern Munich",       "Bundesliga",        27,  42, 5),
        ("Florian Grillitsch",   "MID", "Hoffenheim",          "Bundesliga",        29,  42, 4),
        ("Marcel Sabitzer",      "MID", "Borussia Dortmund",   "Bundesliga",        30,  65, 18),
        ("Nicolas Seiwald",      "MID", "RB Leipzig",          "Bundesliga",        23,  18, 2),
        ("Patrick Wimmer",       "MID", "VfL Wolfsburg",       "Bundesliga",        24,  18, 3),
        ("Romano Schmid",        "MID", "Werder Bremen",       "Bundesliga",        24,  22, 4),
        ("Louis Schaub",         "MID", "Hamburger SV",        "Bundesliga 2",      30,  28, 6),
        ("Marko Arnautovic",     "FWD", "Man United",          "Premier League",    35,  108,35),
        ("Christoph Baumgartner","FWD", "RB Leipzig",          "Bundesliga",        25,  38, 10),
        ("Michael Gregoritsch",  "FWD", "Freiburg",            "Bundesliga",        30,  52, 20),
        ("Sasa Kalajdzic",       "FWD", "Wolves",              "Premier League",    27,  28, 12),
        ("Andreas Weimann",      "FWD", "Werder Bremen",       "Bundesliga",        32,  42, 12),
        ("Karim Onisiwo",        "FWD", "Mainz",               "Bundesliga",        32,  28, 8),
        ("Ercan Kara",           "FWD", "Rapid Wien",          "Austrian Bundesliga",27, 18, 6),
        ("Stefan Ilsanker",      "MID", "Red Bull Salzburg",   "Austrian Bundesliga",34, 38, 1),
        ("Georg Teigl",          "DEF", "Augsburg",            "Bundesliga",        34,  25, 0),
        ("Petar Filipovic",      "DEF", "FC Basel",            "Swiss Super League",33, 18, 1),
    ],
    # ── GROUP K ──────────────────────────────────────────────────────────────
    "Portugal": [
        ("Diogo Costa",          "GK",  "FC Porto",            "Primeira Liga",     25,  22, 0),
        ("Rui Patricio",         "GK",  "AS Roma",             "Serie A",           36,  112,0),
        ("Jose Sa",              "GK",  "Wolves",              "Premier League",    31,  12, 0),
        ("Ruben Dias",           "DEF", "Man City",            "Premier League",    27,  55, 5),
        ("Pepe",                 "DEF", "FC Porto",            "Primeira Liga",     41,  142,8),
        ("Danilo Pereira",       "DEF", "PSG",                 "Ligue 1",           33,  68, 5),
        ("Nuno Mendes",          "DEF", "PSG",                 "Ligue 1",           22,  18, 0),
        ("Joao Cancelo",         "DEF", "Barcelona",           "La Liga",           30,  55, 3),
        ("Diogo Dalot",          "DEF", "Man United",          "Premier League",    25,  28, 2),
        ("Goncalo Inacio",       "DEF", "Sporting CP",         "Primeira Liga",     23,  12, 0),
        ("Bernardo Silva",       "MID", "Man City",            "Premier League",    30,  72, 18),
        ("Vitinha",              "MID", "PSG",                 "Ligue 1",           24,  22, 3),
        ("Ruben Neves",          "MID", "Al-Hilal",            "Saudi Pro League",  27,  52, 8),
        ("Joao Palhinha",        "MID", "Bayern Munich",       "Bundesliga",        28,  32, 2),
        ("Otavio",               "MID", "Al-Nassr",            "Saudi Pro League",  29,  38, 5),
        ("Mateus Nunes",         "MID", "Man City",            "Premier League",    25,  22, 3),
        ("Cristiano Ronaldo",    "FWD", "Al-Nassr",            "Saudi Pro League",  41,  215,135),
        ("Goncalo Ramos",        "FWD", "PSG",                 "Ligue 1",           23,  18, 8),
        ("Pedro Neto",           "FWD", "Chelsea",             "Premier League",    24,  28, 8),
        ("Rafael Leao",          "FWD", "AC Milan",            "Serie A",           25,  32, 10),
        ("Diogo Jota",           "FWD", "Liverpool",           "Premier League",    28,  42, 18),
        ("Joao Felix",           "FWD", "Barcelona",           "La Liga",           25,  38, 10),
        ("Francisco Trincao",    "FWD", "Sporting CP",         "Primeira Liga",     24,  25, 5),
        ("Andre Silva",          "FWD", "RB Leipzig",          "Bundesliga",        29,  55, 22),
        ("Renato Sanches",       "MID", "AS Roma",             "Serie A",           27,  52, 8),
        ("Joao Neves",           "MID", "Benfica",             "Primeira Liga",     20,  10, 1),
    ],
    "Colombia": [
        ("David Ospina",         "GK",  "Al-Qadsiah",          "Saudi Pro League",  36,  115,0),
        ("Camilo Vargas",        "GK",  "Atlas",               "Liga MX",           33,  28, 0),
        ("Alvaro Montero",       "GK",  "Millonarios",         "Liga Betplay Colombia",30,15,0),
        ("Davinson Sanchez",     "DEF", "Galatasaray",         "Turkish Süper Lig", 28,  65, 5),
        ("Yerry Mina",           "DEF", "Everton",             "Premier League",    30,  52, 7),
        ("Daniel Munoz",         "DEF", "Crystal Palace",      "Premier League",    28,  35, 2),
        ("William Tesillo",      "DEF", "Leon",                "Liga MX",           33,  38, 2),
        ("Stefan Medina",        "DEF", "Monterrey",           "Liga MX",           32,  42, 1),
        ("Johan Mojica",         "DEF", "Girona",              "La Liga",           32,  42, 2),
        ("Juan Cuadrado",        "MID", "Juventus",            "Serie A",           36,  108,18),
        ("Wilmar Barrios",       "MID", "Zenit St Petersburg", "Russian Premier League",32,52,3),
        ("Mateus Uribe",         "MID", "FC Porto",            "Primeira Liga",     32,  58, 10),
        ("James Rodriguez",      "MID", "Rayo Vallecano",      "La Liga",           33,  102,34),
        ("Nicolas Gonzalez",     "MID", "Watford",             "Championship",      26,  28, 4),
        ("Jorge Carrascal",      "MID", "Dinamo Moscow",       "Russian Premier League",25,22,5),
        ("Richard Rios",         "MID", "Palmeiras",           "Brasileirao",       24,  18, 3),
        ("Luis Diaz",            "FWD", "Liverpool",           "Premier League",    27,  52, 20),
        ("Jhon Arias",           "FWD", "Fluminense",          "Brasileirao",       27,  32, 10),
        ("Cucho Hernandez",      "FWD", "Columbus Crew",       "MLS",               26,  28, 12),
        ("Rafael Santos Borre",  "FWD", "Eintracht Frankfurt", "Bundesliga",        28,  52, 18),
        ("Duvan Zapata",         "FWD", "Torino",              "Serie A",           33,  62, 25),
        ("Jhon Cordoba",         "FWD", "Krasnodar",           "Russian Premier League",31,35,14),
        ("Eder Militao",         "DEF", "Real Madrid",         "La Liga",           26,   5, 0),
        ("Juanfer Quintero",     "MID", "River Plate",         "Superliga Argentina",31, 42, 8),
        ("Carlos Bacca",         "FWD", "Junior Barranquilla",  "Liga Betplay Colombia",37,62,24),
        ("Luis Fernando Muriel", "FWD", "Atalanta",            "Serie A",           33,  68, 22),
    ],
    # ── GROUP L ──────────────────────────────────────────────────────────────
    "England": [
        ("Jordan Pickford",      "GK",  "Everton",             "Premier League",    30,  65, 0),
        ("Aaron Ramsdale",       "GK",  "Arsenal",             "Premier League",    26,  10, 0),
        ("Dean Henderson",       "GK",  "Crystal Palace",      "Premier League",    27,  10, 0),
        ("Kyle Walker",          "DEF", "Man City",            "Premier League",    34,  82, 1),
        ("John Stones",          "DEF", "Man City",            "Premier League",    30,  70, 3),
        ("Harry Maguire",        "DEF", "Man United",          "Premier League",    31,  65, 7),
        ("Luke Shaw",            "DEF", "Man United",          "Premier League",    29,  35, 3),
        ("Marc Guehi",           "DEF", "Crystal Palace",      "Premier League",    24,  12, 0),
        ("Trent Alexander-Arnold","DEF","Liverpool",           "Premier League",    26,  42, 4),
        ("Kieran Trippier",      "DEF", "Newcastle",           "Premier League",    34,  45, 3),
        ("Declan Rice",          "MID", "Arsenal",             "Premier League",    26,  55, 5),
        ("Jude Bellingham",      "MID", "Real Madrid",         "La Liga",           21,  45, 15),
        ("Phil Foden",           "MID", "Man City",            "Premier League",    24,  42, 10),
        ("Conor Gallagher",      "MID", "Atletico Madrid",     "La Liga",           24,  18, 3),
        ("Kobbie Mainoo",        "MID", "Man United",          "Premier League",    19,  10, 1),
        ("Adam Wharton",         "MID", "Crystal Palace",      "Premier League",    20,   8, 0),
        ("Harry Kane",           "FWD", "Bayern Munich",       "Bundesliga",        31,  95, 68),
        ("Bukayo Saka",          "FWD", "Arsenal",             "Premier League",    23,  42, 12),
        ("Marcus Rashford",      "FWD", "Man United",          "Premier League",    27,  62, 17),
        ("Jarrod Bowen",         "FWD", "West Ham",            "Premier League",    27,  22, 6),
        ("Ollie Watkins",        "FWD", "Aston Villa",         "Premier League",    29,  18, 6),
        ("Anthony Gordon",       "FWD", "Newcastle",           "Premier League",    23,  12, 3),
        ("Cole Palmer",          "MID", "Chelsea",             "Premier League",    22,  18, 5),
        ("Levi Colwill",         "DEF", "Chelsea",             "Premier League",    22,  10, 0),
        ("Curtis Jones",         "MID", "Liverpool",           "Premier League",    24,  12, 1),
        ("Ivan Toney",           "FWD", "Al-Ahli",             "Saudi Pro League",  29,  10, 5),
    ],
    "Croatia": [
        ("Dominik Livakovic",    "GK",  "Fenerbahce",          "Turkish Süper Lig", 29,  55, 0),
        ("Ivica Ivusic",         "GK",  "Osijek",              "HNL",               30,  22, 0),
        ("Nediljko Labrovic",    "GK",  "RB Salzburg",         "Austrian Bundesliga",26, 10, 0),
        ("Josip Sutalo",         "DEF", "Ajax",                "Eredivisie",        23,  15, 1),
        ("Borna Sosa",           "DEF", "Ajax",                "Eredivisie",        27,  38, 3),
        ("Dejan Lovren",         "DEF", "Zenit St Petersburg", "Russian Premier League",35,62,3),
        ("Josip Juranovic",      "DEF", "Celtic",              "Scottish Prem",     29,  45, 2),
        ("Dario Simic",          "DEF", "Dinamo Zagreb",       "HNL",               22,  18, 0),
        ("Martin Erlic",         "DEF", "Sassuolo",            "Serie A",           27,  18, 1),
        ("Luka Modric",          "MID", "Real Madrid",         "La Liga",           39,  180,24),
        ("Marcelo Brozovic",     "MID", "Al-Nassr",            "Saudi Pro League",  32,  82, 12),
        ("Mateo Kovacic",        "MID", "Man City",            "Premier League",    30,  92, 14),
        ("Lovro Majer",          "MID", "Real Madrid",         "La Liga",           26,  38, 6),
        ("Mario Pasalic",        "MID", "Atalanta",            "Serie A",           29,  62, 18),
        ("Nikola Gvardiol",      "DEF", "Man City",            "Premier League",    22,  35, 4),
        ("Luka Sucic",           "MID", "RB Salzburg",         "Austrian Bundesliga",22, 15, 3),
        ("Ivan Perisic",         "FWD", "Hajduk Split",        "HNL",               35,  138,35),
        ("Ante Budimir",         "FWD", "Osasuna",             "La Liga",           32,  38, 12),
        ("Bruno Petkovic",       "FWD", "Dinamo Zagreb",       "HNL",               31,  42, 12),
        ("Marko Livaja",         "FWD", "Hajduk Split",        "HNL",               31,  42, 15),
        ("Andrej Kramaric",      "FWD", "Hoffenheim",          "Bundesliga",        33,  78, 32),
        ("Ivan Zucko",           "FWD", "Dinamo Zagreb",       "HNL",               24,  12, 4),
        ("Mislav Orsic",         "MID", "Club Brugge",         "Pro League",        32,  42, 10),
        ("Kristijan Jakic",      "MID", "Eintracht Frankfurt", "Bundesliga",        28,  28, 2),
        ("Josip Misic",          "MID", "Dinamo Zagreb",       "HNL",               30,  22, 4),
        ("Petar Sucic",          "MID", "Dinamo Zagreb",       "HNL",               20,   8, 1),
    ],
    "Ghana": [
        ("Richard Ofori",        "GK",  "Orlando Pirates",     "South African Prem",30,  48, 0),
        ("Lawrence Ati-Zigi",    "GK",  "St Gallen",           "Swiss Super League",27,  22, 0),
        ("Manaf Nurudeen",       "GK",  "Kasimpasa",           "Turkish Süper Lig", 23,  10, 0),
        ("Mohammed Salisu",      "DEF", "Southampton",         "Championship",      25,  22, 0),
        ("Daniel Amartey",       "DEF", "Leicester City",      "Championship",      30,  48, 2),
        ("Gideon Mensah",        "DEF", "Auxerre",             "Ligue 1",           26,  22, 0),
        ("Tariq Lamptey",        "DEF", "Brighton",            "Premier League",    24,  22, 1),
        ("Edmund Addo",          "DEF", "Sheriff Tiraspol",    "Moldovan Premier League",24,15,0),
        ("Baba Rahman",          "DEF", "Reading",             "League One",        30,  45, 1),
        ("Thomas Partey",        "MID", "Arsenal",             "Premier League",    31,  45, 12),
        ("Mohammed Kudus",       "MID", "Ajax",                "Eredivisie",        23,  28, 8),
        ("Salis Abdul Samed",    "MID", "Lens",                "Ligue 1",           24,  18, 2),
        ("Elisha Owusu",         "MID", "Gent",                "Pro League",        26,  18, 2),
        ("Jeffery Schlupp",      "MID", "Crystal Palace",      "Premier League",    31,  42, 6),
        ("Daniel Kofi Kyereh",   "MID", "Freiburg",            "Bundesliga",        27,  18, 4),
        ("Kamal Sowah",          "MID", "Club Brugge",         "Pro League",        24,  15, 3),
        ("Jordan Ayew",          "FWD", "Crystal Palace",      "Premier League",    32,  82, 22),
        ("Andre Ayew",           "FWD", "Nottm Forest",        "Premier League",    34,  108,23),
        ("Antoine Semenyo",      "FWD", "Bournemouth",         "Premier League",    24,  12, 4),
        ("Inaki Williams",       "FWD", "Athletic Bilbao",     "La Liga",           30,  22, 4),
        ("Osman Bukari",         "FWD", "Red Star Belgrade",   "Serbian SuperLiga", 26,  22, 6),
        ("Richmond Boakye",      "FWD", "Red Star Belgrade",   "Serbian SuperLiga", 32,  28, 10),
        ("Nicholas Opoku",       "DEF", "Amiens SC",           "Ligue 2",           27,  18, 0),
        ("Ibrahim Sadiq",        "FWD", "Almeria",             "La Liga",           23,  10, 3),
        ("Issahaku Fatawu",      "FWD", "Leicester City",      "Championship",      20,  12, 3),
        ("Stephan Ambrosius",    "DEF", "Hamburger SV",        "Bundesliga 2",      25,  12, 0),
    ],
    "Panama": [
        ("Luis Mejia",           "GK",  "Columbus Crew",       "MLS",               27,  42, 0),
        ("Orlando Mosquera",     "GK",  "Peñarol",             "Uruguayan Primera", 30,  22, 0),
        ("Jose Carrasquilla",    "GK",  "San Jose Earthquakes","MLS",               28,  15, 0),
        ("Eric Davis",           "DEF", "FC Dallas",           "MLS",               32,  68, 3),
        ("Fidel Escobar",        "DEF", "New York City FC",    "MLS",               28,  55, 2),
        ("Roderick Miller",      "DEF", "El Jaish",            "Qatar Stars League",33,  52, 1),
        ("Michael Murillo",      "DEF", "Anderlecht",          "Pro League",        28,  52, 2),
        ("Harold Cummings",      "DEF", "Sporting Kansas City","MLS",               30,  45, 3),
        ("Ricardo Bryan",        "DEF", "Estudiantes",         "Superliga Argentina",26, 22, 0),
        ("Cesar Blackman",       "DEF", "Deportivo Alaves",    "La Liga",           26,  22, 0),
        ("Anibal Godoy",         "MID", "Nashville SC",        "MLS",               35,  82, 5),
        ("Adalberto Carrasquilla","MID","Venezia",             "Serie A",           28,  48, 8),
        ("Alberto Quintero",     "MID", "Olimpia",             "Paraguayan Primera",34,  68, 10),
        ("Armando Cooper",       "MID", "Atlanta United",      "MLS",               35,  72, 8),
        ("Jose Fajardo",         "MID", "Portland Timbers",    "MLS",               30,  55, 8),
        ("Amir Murillo",         "MID", "Anderlecht",          "Pro League",        28,  38, 4),
        ("Rolando Blackburn",    "FWD", "Pachuca",             "Liga MX",           30,  42, 12),
        ("Gabriel Torres",       "FWD", "Olimpia",             "Paraguayan Primera",35,  85, 28),
        ("Cesar Yanis",          "FWD", "Austin FC",           "MLS",               28,  28, 8),
        ("Jesus Olivares",       "FWD", "Club America",        "Liga MX",           26,  22, 5),
        ("Eduardo Guerrero",     "FWD", "FC Cincinnati",       "MLS",               22,  12, 4),
        ("Jorge Villafuerte",    "FWD", "Olimpia",             "Paraguayan Primera",25,  18, 5),
        ("Alfredo Stephenson",   "DEF", "New England Revolution","MLS",             30,  28, 0),
        ("Edgar Barcenas",       "MID", "Olimpia",             "Paraguayan Primera",30,  35, 5),
        ("Ismael Diaz",          "FWD", "Toulouse",            "Ligue 1",           24,  18, 6),
        ("Yoel Barcenas",        "FWD", "Olimpia",             "Paraguayan Primera",26,  22, 6),
    ],
}


def run():
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    total_added = 0

    for team_name, squad in SQUADS.items():
        row = cur.execute("SELECT id FROM teams WHERE name=?", (team_name,)).fetchone()
        if not row:
            print(f"  SKIP (team not found): {team_name}")
            continue
        team_id = row["id"]

        existing_names = {r["name"] for r in cur.execute(
            "SELECT name FROM players WHERE team_id=?", (team_id,)
        ).fetchall()}

        added = 0
        for name, position, club, league, age, caps, goals in squad:
            if name in existing_names:
                continue
            cur.execute("""
                INSERT OR IGNORE INTO players
                    (name, team_id, position, club, club_league, age, caps, goals_as_nat)
                VALUES (?,?,?,?,?,?,?,?)
            """, (name, team_id, position, club, league, age, caps, goals))
            p = cur.execute(
                "SELECT id FROM players WHERE name=? AND team_id=?", (name, team_id)
            ).fetchone()
            if p:
                cur.execute("""
                    INSERT OR IGNORE INTO squad_selections (team_id, player_id, confirmed)
                    VALUES (?,?,1)
                """, (team_id, p["id"]))
                added += 1

        conn.commit()
        current = cur.execute("SELECT COUNT(*) FROM players WHERE team_id=?", (team_id,)).fetchone()[0]
        print(f"  {team_name:<30} +{added} → {current} total")
        total_added += added

    final = conn.execute("SELECT COUNT(*) FROM players").fetchone()[0]
    print(f"\nTotal added: {total_added} | DB players: {final}")
    conn.close()


if __name__ == "__main__":
    run()
