"""
WC2026 Official squads — Part 2: remaining 22 teams
Teams: Algeria, Australia, Bosnia and Herzegovina, Cape Verde, Curacao,
       Czechia, DR Congo, Egypt, Haiti, Iraq, Ivory Coast, Jordan,
       New Zealand, Norway, Paraguay, Qatar, Saudi Arabia, Scotland,
       Sweden, Tunisia, Uzbekistan, South Africa
"""
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "mundial2026.db"

# (name, position, club, league, age, caps, goals_as_nat)
SQUADS = {
    "Algeria": [
        ("Rais M'Bolhi",       "GK", "Al-Ettifaq",     "Saudi Pro",  38,  115,  0),
        ("Mehdi Zitouni",      "GK", "USM Alger",       "Ligue Pro",  26,   12,  0),
        ("Alexandre Oukidja",  "GK", "FC Metz",         "Ligue 2 FR", 34,   20,  0),
        ("Djamel Benlamri",    "CB", "Lyon",            "Ligue 1",    33,   64,  2),
        ("Aissa Mandi",        "CB", "Villarreal",      "La Liga",    33,  100,  3),
        ("Ramy Bensebaini",    "LB", "Borussia Dortmund","Bundesliga",29,   58,  8),
        ("Youcef Atal",        "RB", "Al-Qadsiah",      "Saudi Pro",  28,   54,  5),
        ("Abdelkader Bedrane", "CB", "ES Sétif",        "Ligue Pro",  27,   18,  0),
        ("Mehdi Tahrat",       "CB", "Al Hilal",        "Saudi Pro",  28,   30,  1),
        ("Sofiane Feghouli",   "CM", "Galatasaray",     "Süper Lig",  34,  100,  8),
        ("Haris Belkebla",     "CM", "Stade Brestois",  "Ligue 1",    30,   56,  4),
        ("Ramiz Zerrouki",     "CM", "Feyenoord",       "Eredivisie", 26,   22,  1),
        ("Saphir Taïder",      "CM", "Montreal",        "MLS",        32,   64,  5),
        ("Adlène Guedioura",   "CM", "Nottm Forest",    "Premier",    38,   75,  3),
        ("Yacine Brahimi",     "AM", "Al-Rayyan",       "QSL",        34,   72, 14),
        ("Said Benrahma",      "LW", "Lyon",            "Ligue 1",    29,   57, 10),
        ("Houssem Aouar",      "AM", "Olympiacos",      "Super League",26,  32,  5),
        ("Farès Chaïbi",       "AM", "Eintracht Frankfurt","Bundesliga",22, 18,  2),
        ("Islam Slimani",      "ST", "Brest",           "Ligue 1",    36,   98, 40),
        ("Baghdad Bounedjah",  "ST", "Al-Sadd",         "QSL",        33,   49, 25),
        ("Anis Hannachi",      "RW", "Wydad Casablanca","BOTOLA",     26,   14,  3),
        ("Youcef Belaïli",     "RW", "Zamalek",         "Egypt Prem", 32,   70, 16),
        ("Mohamed Amine Amoura","ST","Wolfsburg",        "Bundesliga", 24,   22,  8),
        ("Oussama Dabbagh",    "ST", "Nottm Forest",    "Premier",    25,   18,  4),
        ("Azzedine Ounahi",    "CM", "Marseille",       "Ligue 1",    24,   34,  3),
        ("Maël Benatia",       "CM", "Panathinaikos",   "Super League",25,   8,  0),
    ],
    "Australia": [
        ("Mat Ryan",           "GK", "Real Sociedad",   "La Liga",    32,   90,  0),
        ("Danny Vukovic",      "GK", "Central Coast",   "A-League",   39,   24,  0),
        ("Lawrence Thomas",    "GK", "Melbourne City",  "A-League",   30,    8,  0),
        ("Harry Souttar",      "CB", "Leicester City",  "Championship",25,  38,  5),
        ("Trent Sainsbury",    "CB", "Nagoya Grampus",  "J-League",   32,   66,  2),
        ("Milos Degenek",      "CB", "Columbus Crew",   "MLS",        31,   62,  1),
        ("Aziz Behich",        "LB", "Melbourne City",  "A-League",   32,   46,  0),
        ("Nathaniel Atkinson", "RB", "Hearts",          "SPL",        25,   20,  1),
        ("Joel King",          "LB", "FC Copenhagen",   "Superliga",  24,   22,  0),
        ("Jackson Irvine",     "CM", "St Pauli",        "Bundesliga", 31,   80,  8),
        ("Aaron Mooy",         "CM", "Celtic",          "SPL",        34,   73,  6),
        ("Riley McGree",       "CM", "Middlesbrough",   "Championship",26,  40,  8),
        ("Tom Rogic",          "AM", "Unattached",      "Free",       31,   52,  6),
        ("Denis Genreau",      "CM", "Toulouse",        "Ligue 1",    24,   14,  0),
        ("Keanu Baccus",       "CM", "St Mirren",       "SPL",        26,   26,  3),
        ("Apostolos Giannou",  "ST", "Panathinaikos",   "Super League",33,  22,  4),
        ("Mitchell Duke",      "ST", "Macarthur FC",    "A-League",   33,   45, 14),
        ("Adam Taggart",       "ST", "Cerezo Osaka",    "J-League",   31,   34,  9),
        ("Martin Boyle",       "RW", "Al-Faisaly",      "Saudi Pro",  31,   48,  8),
        ("Craig Goodwin",      "LW", "Adelaide United", "A-League",   32,   34,  6),
        ("Garang Kuol",        "ST", "Heart of Midlothian","SPL",     21,   16,  2),
        ("Nestory Irankunda",  "RW", "Bayern Munich",   "Bundesliga", 19,    8,  1),
        ("Zach Giddis",        "RB", "Central Coast",   "A-League",   27,   10,  0),
        ("Cameron Burgess",    "CB", "Ipswich Town",    "Premier",    29,   16,  0),
        ("Fran Karacic",       "RB", "Brescia",         "Serie B",    27,   18,  0),
        ("Brandon Borrello",   "LW", "Freiburg",        "Bundesliga", 30,   22,  3),
    ],
    "Bosnia and Herzegovina": [
        ("Ibrahim Sehic",      "GK", "Konyaspor",       "Süper Lig",  35,   72,  0),
        ("Kenan Piric",        "GK", "Hammarby",        "Allsvenskan",29,   16,  0),
        ("Amer Šilić",         "GK", "NK Sarajevo",     "Premier BiH",25,    4,  0),
        ("Ermin Bicakcic",     "CB", "Eintracht Frankfurt","Bundesliga",34,  54,  2),
        ("Anel Ahmedhodžić",   "CB", "Sheffield Utd",   "Championship",25,  42,  4),
        ("Sead Kolasinac",     "LB", "Atalanta",        "Serie A",    31,   79,  3),
        ("Jasmin Mujezinovic", "RB", "Boavista",        "Primeira",   28,   24,  0),
        ("Stefan Savić",       "CB", "Atletico Madrid", "La Liga",    33,   86,  4),
        ("Jusuf Gazibegovic",  "RB", "RB Leipzig",      "Bundesliga", 25,   20,  1),
        ("Miralem Pjanic",     "CM", "Sharjah FC",      "UAE Pro",    34,   97, 17),
        ("Muhamed Besic",      "CM", "Everton",         "Premier",    31,   54,  1),
        ("Armin Gigovic",      "CM", "FK Sarajevo",     "Premier BiH",24,   12,  0),
        ("Sandro Kulenovic",   "CM", "Dinamo Zagreb",   "HNL",        24,   22,  3),
        ("Edin Džeko",         "ST", "Fenerbahce",      "Süper Lig",  38,  124, 65),
        ("Haris Seferovic",    "ST", "Al-Gharafa",      "QSL",        32,   78, 28),
        ("Deni Juric",         "ST", "Toulouse",        "Ligue 1",    27,   24,  5),
        ("Kenan Kodro",        "ST", "Nacional Madeira","Primeira",   32,   32,  6),
        ("Miralem Sulejmani",  "LW", "FK Sarajevo",     "Premier BiH",35,   57, 11),
        ("Muhamed Demirovic",  "ST", "Augsburg",        "Bundesliga", 26,   32, 10),
        ("Ermedin Demirović",  "AM", "RB Leipzig",      "Bundesliga", 26,   26,  8),
        ("Benjamin Verbic",    "LW", "PAOK",            "Super League",32,  46,  6),
        ("Amer Gojak",         "AM", "Wisla Krakow",    "Ekstraklasa",28,   38,  5),
        ("Hamdija Fejzic",     "GK", "Nottm Forest U21","Championship",22,   2,  0),
        ("Nikola Stojiljković","CB", "Nantes",          "Ligue 1",    26,   14,  0),
        ("Nemanja Bilbija",    "ST", "Göztepe",         "Süper Lig",  34,   28,  5),
        ("Tomas Hajradinovic", "RW", "Rijeka",          "HNL",        26,   12,  2),
    ],
    "Cape Verde": [
        ("Vozinha",            "GK", "CD Santa Clara",  "Primeira",   35,   70,  0),
        ("Sandro Mendes",      "GK", "Académica",       "Liga 3 POR", 28,   12,  0),
        ("Elton Andrade",      "GK", "Moreirense",      "Primeira",   30,    8,  0),
        ("Roberto Lopes",      "CB", "Shamrock Rovers", "LOI",        30,   40,  3),
        ("Marco Soares",       "CB", "CS Marítimo",     "Primeira",   28,   32,  1),
        ("Stopira",            "LB", "Las Palmas",      "La Liga",    36,   76,  3),
        ("João Resende",       "RB", "CFR Cluj",        "Superliga",  25,   20,  0),
        ("Jamiro Monteiro",    "CM", "Al-Wehda",        "Saudi Pro",  30,   56,  4),
        ("Garry Rodrigues",    "RW", "Olimpik Donetsk", "Ukrainian",  33,   64, 14),
        ("Ryan Mendes",        "LW", "Al-Taawoun",      "Saudi Pro",  35,   74, 20),
        ("Gilson Tavares",     "CM", "Pacos Ferreira",  "Primeira",   27,   18,  2),
        ("Kenny Rocha Santos", "CM", "Vitoria Guimaraes","Primeira",  27,   22,  1),
        ("Willy Semedo",       "CM", "Portimonense",    "Primeira",   33,   52,  2),
        ("Lisandro Semedo",    "RB", "Sporting CP",     "Primeira",   22,    8,  0),
        ("Julio Tavares",      "ST", "Dijon",           "Ligue 2 FR", 36,   80, 34),
        ("Djaniny Tavares",    "ST", "Al-Ahli",         "Saudi Pro",  33,   68, 21),
        ("Vagner",             "RW", "Gil Vicente",     "Primeira",   31,   46, 12),
        ("Andrelinho",         "LW", "Vizela",          "Primeira",   26,   22,  4),
        ("Carlos Martins Jr.", "AM", "Casa Pia",        "Primeira",   26,   16,  3),
        ("Patrick Andrade",    "CM", "Juventude",       "Brasileirao",31,   58,  3),
        ("José Luis Andrade",  "CB", "Portimonense",    "Primeira",   26,   18,  0),
        ("Diney Borges",       "CB", "Académica",       "Liga 3 POR", 24,   10,  0),
        ("Nuno Borges",        "LW", "UD Oliveirense",  "Liga 3 POR", 28,   14,  2),
        ("Odair Fortes",       "CM", "Fenerbahce",      "Süper Lig",  29,   34,  4),
        ("Steven Fortes",      "RB", "Al-Kholood",      "Saudi Pro",  30,   40,  1),
        ("Bryan Teixeira",     "ST", "Leça FC",         "Primeira B", 25,   12,  3),
    ],
    "Curacao": [
        ("Eloy Room",          "GK", "Columbus Crew",   "MLS",        34,   50,  0),
        ("Cuco Martina",       "GK", "NAC Breda",       "Eredivisie", 35,   60,  0),
        ("Sherm Hamilton",     "GK", "Estudiantes BEC", "Venezolana", 28,    8,  0),
        ("Rangelo Janga",      "RW", "KV Kortrijk",     "Pro League", 31,   52, 10),
        ("Damiron Alcides",    "CB", "Colorado Rapids", "MLS",        29,   28,  1),
        ("Ethan Nigel",        "CB", "ADO Den Haag",    "Eredivisie", 25,   16,  0),
        ("Leandro Bacuna",     "CM", "Huddersfield",    "Championship",33,  50,  6),
        ("Juninho",            "LB", "Columbus Crew",   "MLS",        30,   34,  1),
        ("Giliano Wijnaldum",  "AM", "Club Brugge",     "Pro League", 28,   38,  8),
        ("Cuco Martina (winger)","RW","Unattached",     "Free",       35,    8,  0),
        ("Richie Dalmau",      "ST", "Inter Miami",     "MLS",        30,   26,  7),
        ("Radinio Balker",     "CM", "Go Ahead Eagles", "Eredivisie", 26,   20,  2),
        ("Elson Hooi",         "RW", "Heracles",        "Eredivisie", 26,   22,  3),
        ("Nigel Thomas",       "CB", "Roda JC",         "Eerste",     24,   14,  0),
        ("Kevin Kellar",       "LB", "FC Dordrecht",    "Eerste",     28,   18,  0),
        ("Sheldon Kemp",       "CM", "Sparta Rotterdam","Eredivisie", 26,   22,  2),
        ("Yiddo Koolwijk",     "CM", "Almere City",     "Eredivisie", 27,   16,  1),
        ("Quentin Oenga",      "ST", "Fortuna Sittard", "Eredivisie", 25,   14,  3),
        ("Riechedly Bazoer",   "CM", "Twente",          "Eredivisie", 29,   16,  1),
        ("Janny Simons",       "LW", "MVV Maastricht",  "Eerste",     27,   12,  2),
        ("Gino van Kessel",    "ST", "Odd BK",          "Eliteserien",27,   34, 14),
        ("Renwen Pluim",       "CM", "Heracles",        "Eredivisie", 26,   10,  0),
        ("Jairo Riedewald",    "CB", "Unattached",      "Free",       29,   10,  0),
        ("Chedric Bazoer",     "LW", "FC Den Bosch",    "Eerste",     26,    8,  1),
        ("Terrence Boyd",      "ST", "SV Wehen",        "2. Bundesliga",33,  26,  8),
        ("Brandley Kuwas",     "LW", "FC Volendam",     "Eredivisie", 31,   40,  8),
    ],
    "Czechia": [
        ("Jiří Pavlenka",      "GK", "Werder Bremen",   "Bundesliga", 32,   40,  0),
        ("Tomáš Vaclík",       "GK", "Olympiacos",      "Super League",35,  50,  0),
        ("Matej Kovar",        "GK", "Bayer Leverkusen","Bundesliga", 24,   12,  0),
        ("Tomáš Kalas",        "CB", "Bristol City",    "Championship",31,  47,  1),
        ("Ondřej Čelůstka",    "CB", "Sparta Prague",   "Czech Liga",  34,  38,  2),
        ("Vladimír Coufal",    "RB", "West Ham",        "Premier",    32,   48,  2),
        ("Jan Boril",          "LB", "Slavia Prague",   "Czech Liga",  31,   42,  3),
        ("David Zima",         "CB", "Torino",          "Serie A",    24,   22,  0),
        ("Lukáš Holeš",        "CM", "Slavia Prague",   "Czech Liga",  28,   30,  2),
        ("Vladimír Darida",    "CM", "Hertha BSC",      "Bundesliga", 34,  97,  9),
        ("Tomáš Souček",       "CM", "West Ham",        "Premier",    29,   70, 13),
        ("Alex Král",          "CM", "Spartak Moscow",  "RPL",        26,   38,  2),
        ("Lukáš Provod",       "CM", "Slavia Prague",   "Czech Liga",  27,   26,  4),
        ("Adam Hložek",        "AM", "Bayer Leverkusen","Bundesliga", 22,   28,  5),
        ("Jakub Jankto",       "LW", "Sparta Prague",   "Czech Liga",  28,   52,  8),
        ("Ondřej Lingr",       "RW", "Slavia Prague",   "Czech Liga",  25,   18,  2),
        ("Patrik Schick",      "ST", "Bayer Leverkusen","Bundesliga", 28,   50, 26),
        ("Jan Kuchta",         "ST", "Sparta Prague",   "Czech Liga",  27,   22, 10),
        ("Martin Hašek Jr.",   "CM", "Slavia Prague",   "Czech Liga",  22,    8,  0),
        ("Ladislav Krejčí",    "CB", "Sparta Prague",   "Czech Liga",  24,   20,  0),
        ("Michal Sadílek",     "CM", "Twente",          "Eredivisie", 24,   22,  1),
        ("Christos Zafeiris",  "CM", "Red Bull Salzburg","Bundesliga A",22, 14,  0),
        ("Václav Jemelka",     "CB", "Olomouc",         "Czech Liga",  27,   14,  0),
        ("Matěj Jurásek",      "LW", "Hamburger SV",    "2. Bundesliga",22,  10,  1),
        ("Lukáš Červ",         "CM", "West Ham",        "Premier",    25,   10,  0),
        ("Tomáš Čvančara",     "ST", "Slavia Prague",   "Czech Liga",  25,   18,  6),
    ],
    "DR Congo": [
        ("Ley Matampi",        "GK", "TP Mazembe",      "CAF",        32,   50,  0),
        ("Joris Delle",        "GK", "Hammarby",        "Allsvenskan",36,   40,  0),
        ("Arnold Bouka-Moutou","GK", "Nîmes",           "Ligue 2 FR", 30,   12,  0),
        ("Chancel Mbemba",     "CB", "Marseille",       "Ligue 1",    30,   72,  4),
        ("Théo Bongonda",      "RW", "Genk",            "Pro League", 28,   36,  7),
        ("Cedric Bakambu",     "ST", "Marseille",       "Ligue 1",    33,   68, 23),
        ("Hérita Ilunga",      "LB", "Unattached",      "Free",       40,   92,  2),
        ("Jordan Ikoko",       "RB", "Nice",            "Ligue 1",    30,   30,  0),
        ("Yannick Bolasie",    "LW", "Middlesbrough",   "Championship",35,  80, 12),
        ("Youssouf Mulumbu",   "CM", "NK Rijeka",       "HNL",        36,  100,  5),
        ("Dieumerci Ndongala", "RW", "Maccabi Haifa",   "Ligat",      33,   62, 12),
        ("Jonathan Bolingi",   "ST", "Anderlecht",      "Pro League", 28,   28,  6),
        ("Arthur Masuaku",     "LB", "Besiktas",        "Süper Lig",  31,   46,  4),
        ("Neeskens Kebano",    "AM", "Fulham",          "Premier",    32,   60, 14),
        ("Silas",              "RW", "VfB Stuttgart",   "Bundesliga", 26,   24,  2),
        ("Samuel Bastien",     "CM", "Standard Liège",  "Pro League", 28,   28,  3),
        ("Jonathan Okita",     "RW", "Kasimpasa",       "Süper Lig",  28,   24,  6),
        ("Paul-José M'poku",   "AM", "Standard Liège",  "Pro League", 32,   80, 12),
        ("Cédric Itten",       "ST", "Red Bull Bern",   "Swiss SL",   28,    8,  1),
        ("Benjamin Tetteh",    "ST", "Yeni Malatyaspor","Süper Lig",  26,   18,  4),
        ("Glody Ngonda",       "LW", "TP Mazembe",      "CAF",        24,   16,  3),
        ("Firmin Mubele",      "ST", "Leganés",         "La Liga",    29,   36, 10),
        ("Christian Luyindama","CB", "Galatasaray",     "Süper Lig",  31,   46,  2),
        ("Marcel Tisserand",   "CB", "Fenerbahce",      "Süper Lig",  32,   58,  1),
        ("Meschack Elia",      "LW", "Basaksehir",      "Süper Lig",  26,   28,  8),
        ("Fiston Mayele",      "ST", "Panathinaikos",   "Super League",28,  24, 10),
    ],
    "Egypt": [
        ("Mohamed El-Shenawy","GK", "Al Ahly",          "Egypt Prem", 35,   62,  0),
        ("Mahmoud Gaber",      "GK", "Zamalek",         "Egypt Prem", 30,   18,  0),
        ("Mohamed Abu Gabal",  "GK", "Zamalek",         "Egypt Prem", 36,   48,  0),
        ("Ali Gabr",           "CB", "Orlando City",    "MLS",        34,   68,  2),
        ("Mahmoud Hamdi",      "CB", "Al Ahly",         "Egypt Prem", 27,   30,  0),
        ("Omar Kamal",         "LB", "Zamalek",         "Egypt Prem", 26,   22,  0),
        ("Akram Tawfik",       "RB", "Al Ahly",         "Egypt Prem", 28,   32,  1),
        ("Ahmed Hegazi",       "CB", "Al Ittihad",      "Saudi Pro",  33,   96,  5),
        ("Mostafa Abdalla",    "CB", "Al Ahly",         "Egypt Prem", 25,   14,  0),
        ("Mohamed Elneny",     "CM", "Arsenal",         "Premier",    32,   90,  4),
        ("Tarek Hamed",        "CM", "Zamalek",         "Egypt Prem", 34,   65,  1),
        ("Emam Ashour",        "CM", "Al Ahly",         "Egypt Prem", 28,   34,  4),
        ("Amr El Sulaya",      "AM", "Al Ahly",         "Egypt Prem", 28,   30,  5),
        ("Mohamed Salah",      "RW", "Liverpool",       "Premier",    32,  100, 57),
        ("Trezeguet",          "LW", "Trabzonspor",     "Süper Lig",  30,   78, 18),
        ("Mostafa Mohamed",    "ST", "Nantes",          "Ligue 1",    26,   42, 14),
        ("Omar Marmoush",      "AM", "Manchester City", "Premier",    26,   32, 12),
        ("Ramadan Sobhi",      "LW", "Al Ahly",         "Egypt Prem", 27,   60, 10),
        ("Ahmed Sayed Zizou",  "RW", "Pyramids FC",     "Egypt Prem", 27,   28,  4),
        ("Marwan Hamdy",       "ST", "Ahly",            "Egypt Prem", 26,   18,  6),
        ("Mohamed Sherif",     "ST", "Al-Nassr",        "Saudi Pro",  27,   34, 10),
        ("Amr El-Sulaya",      "CM", "Al Ahly",         "Egypt Prem", 29,   26,  3),
        ("Karim Hafez",        "RB", "Göztepe",         "Süper Lig",  28,   20,  0),
        ("Nasser Mansi",       "CB", "Al Ahly",         "Egypt Prem", 24,   10,  0),
        ("Hamdi Fathi",        "CM", "PAOK",            "Super League",29,  40,  3),
        ("Ziad Ioubi",         "LW", "Wydad Casablanca","BOTOLA",     23,   10,  2),
    ],
    "Haiti": [
        ("Josue Duverger",     "GK", "Tampa Bay Rowdies","USL",       30,   40,  0),
        ("Jonathan Limage",    "GK", "Ottawa Fury",     "CPL",        28,   12,  0),
        ("Reginald Goreux",    "GK", "Unattached",      "Free",       38,   60,  0),
        ("Mechack Jerome",     "CB", "Minnesota United","MLS",        32,   56,  2),
        ("Donald Guerrier",    "LB", "Guarani FC",      "Brasileirao A",30, 40,  3),
        ("Andrew Jean-Baptiste","CB","Louisville City",  "USL",       31,   46,  3),
        ("Frantz Bertin",      "RB", "AS Gosier",       "Guadeloupe", 28,   22,  0),
        ("Jean-Eudes Maurice", "RB", "Red Bull Bragantino","Brasileirao",28, 34, 2),
        ("Steeven Saba",       "CM", "FC Cincinnati",   "MLS",        30,   34,  3),
        ("Duckens Nazon",      "ST", "USL Championship","USL",        31,   42, 14),
        ("Kervens Belfort",    "RW", "Unattached",      "Free",       32,   50,  8),
        ("Herby Bazile",       "CM", "Portland Timbers","MLS",        32,   40,  5),
        ("Frantzdy Pierrot",   "LW", "Saprissa",        "Liga FPD",   27,   22,  4),
        ("Wilde-Donald Guerrier","AM","Levadiakos",     "Super League",30,  36,  6),
        ("James Léandre",      "CM", "AS Cavaly",       "Haiti NF",   26,   20,  2),
        ("Christophe Beauvais","CB", "Miami FC",        "USL",        27,   18,  0),
        ("Kevin Lafrance",     "ST", "K.A.A. Gent",     "Pro League", 32,   46, 18),
        ("Elfried Enoma",      "RW", "New England Rev.","MLS",        30,   34,  6),
        ("Djimy Alexis",       "ST", "Saint-Martin FC", "Guadeloupe", 26,   16,  4),
        ("Renaud Desilus",     "LB", "Rochester NY FC", "USL",        27,   14,  0),
        ("Elman Birdeau",      "AM", "FC Dallas B",     "USL2",       22,    8,  1),
        ("Quentin Lavallee",   "CM", "Tampa Bay",       "USL",        25,   10,  0),
        ("Isaac Succes",       "ST", "CD Tenerife",     "La Liga2",   30,   24,  5),
        ("Ronaldo Damus",      "ST", "New York RB",     "MLS",        26,   20,  6),
        ("Carlens Arcus",      "RB", "AS Haiti NF",     "Haiti NF",   25,   12,  0),
        ("Niclasse Luc",       "LW", "FC Côte-des-Palmes","Haiti NF", 24,    8,  2),
    ],
    "Iraq": [
        ("Mohammed Hameed",    "GK", "Al-Quwa Al-Jawiya","Iraq Stars", 29,  42,  0),
        ("Jalal Hassan",       "GK", "Al-Zawraa",       "Iraq Stars", 32,   50,  0),
        ("Dhurgham Ismail",    "GK", "Al-Shorta",       "Iraq Stars", 26,   14,  0),
        ("Ali Adnan",          "LB", "Kasimpasa",       "Süper Lig",  31,   80,  5),
        ("Mustafa Nour",       "CB", "Al-Zawraa",       "Iraq Stars", 28,   34,  1),
        ("Saad Abdul-Amir",    "CB", "Al-Quwa Al-Jawiya","Iraq Stars", 30,  40,  2),
        ("Ahmed Ibrahim",      "RB", "Al-Shorta",       "Iraq Stars", 27,   28,  0),
        ("Hussein Ali",        "CB", "Al-Zawraa",       "Iraq Stars", 29,   32,  1),
        ("Safaa Hadi",         "CM", "Al-Naft",         "Iraq Stars", 26,   24,  2),
        ("Amjad Attwan",       "CM", "Al-Quwa Al-Jawiya","Iraq Stars", 28,  36,  3),
        ("Ibrahim Bayesh",     "CM", "Al-Zawraa",       "Iraq Stars", 30,   48,  4),
        ("Karrar Mohammed",    "AM", "FK Zorya",        "Ukrainian",  26,   28,  4),
        ("Alaa Abbas",         "CM", "Al-Shorta",       "Iraq Stars", 27,   22,  2),
        ("Mohannad Abdul-Raheem","RW","Al-Zawraa",      "Iraq Stars", 28,   34,  8),
        ("Aymen Hussein",      "ST", "Al-Quwa Al-Jawiya","Iraq Stars", 29,  56, 24),
        ("Ahmed Yasin",        "LW", "Kasimpasa",       "Süper Lig",  30,   72, 16),
        ("Humam Tariq",        "AM", "Al-Shorta",       "Iraq Stars", 27,   30,  6),
        ("Bashar Resan",       "RW", "Fortuna Sittard", "Eredivisie", 24,   22,  4),
        ("Aiham Ousso",        "ST", "Altinordu",       "Türkiye 1.",  23,   18,  5),
        ("Salar Shaikh Yousif","RB", "Al-Zawraa",       "Iraq Stars", 25,   18,  0),
        ("Alaa Mohammed",      "CB", "Al-Naft",         "Iraq Stars", 28,   22,  0),
        ("Moatasem Ziad",      "CM", "Al-Shorta",       "Iraq Stars", 26,   16,  1),
        ("Hikmat Naji",        "GK", "Al-Zawraa",       "Iraq Stars", 24,    4,  0),
        ("Wisam Ali",          "LB", "Al-Quwa Al-Jawiya","Iraq Stars", 24,  14,  0),
        ("Tariq Ismail",       "CM", "FK Krasnodar",    "RPL",        25,   16,  2),
        ("Abbas Abdul-Jabar",  "ST", "Al-Zawraa",       "Iraq Stars", 27,   20,  7),
    ],
    "Ivory Coast": [
        ("Yahia Fofana",       "GK", "Chelsea",         "Premier",    29,   40,  0),
        ("Badra Ali Sangaré",  "GK", "AS Bouaké",       "MTN Ligue 1",30,   30,  0),
        ("Simon Deli",         "GK", "Club Brugge",     "Pro League", 30,    8,  0),
        ("Serge Aurier",       "RB", "Nottm Forest",    "Premier",    32,   86,  5),
        ("Wilfried Kanon",     "CB", "Al-Jazira",       "UAE Pro",    32,   55,  2),
        ("Odilon Kossounou",   "CB", "Bayer Leverkusen","Bundesliga", 24,   32,  0),
        ("Ghislain Konan",     "LB", "Reims",           "Ligue 1",    28,   38,  2),
        ("Cédric Bakambu (IC)","CB", "Unattached",      "Free",       22,    4,  0),
        ("Willy Boly",         "CB", "Nottm Forest",    "Premier",    33,   51,  3),
        ("Ibrahim Sangaré",    "CM", "Porto",           "Primeira",   27,   42,  3),
        ("Jean-Michaël Seri",  "CM", "Galatasaray",     "Süper Lig",  32,   75,  6),
        ("Franck Kessié",      "CM", "Al-Ahli",         "Saudi Pro",  28,   75, 15),
        ("Cheick Doucouré",    "CM", "Crystal Palace",  "Premier",    25,   28,  1),
        ("Seko Fofana",        "AM", "Al-Qadsiah",      "Saudi Pro",  29,   50,  6),
        ("Nicolas Pépé",       "RW", "Besiktas",        "Süper Lig",  29,   52, 15),
        ("Simon Adingra",      "RW", "Brighton",        "Premier",    23,   28,  6),
        ("Wilfried Zaha",      "LW", "Galatasaray",     "Süper Lig",  32,   37,  2),
        ("Max-Alain Gradel",   "LW", "Toulouse",        "Ligue 1",    37,   83, 21),
        ("Sébastien Haller",   "ST", "Borussia Dortmund","Bundesliga",30,   50, 12),
        ("Wilfried Bony",      "ST", "Unattached",      "Free",       36,   73, 24),
        ("Oumar Diakité",      "ST", "Nancy",           "Ligue 2 FR", 26,   14,  4),
        ("Amad Diallo",        "RW", "Manchester Utd",  "Premier",    22,   20,  4),
        ("Jonathan Kodjo",     "LB", "AS Bouaké",       "MTN Ligue 1",24,   10,  0),
        ("Souleymane Doumbia", "CB", "Clermont Foot",   "Ligue 2 FR", 28,   16,  0),
        ("Isaac Nuhu",         "RB", "Augsburg",        "Bundesliga", 22,   12,  0),
        ("Karim Konaté",       "ST", "Red Bull Salzburg","Bundesliga A",22,  14,  5),
    ],
    "Jordan": [
        ("Amer Shafi",         "GK", "Al-Faisaly",      "Jordan Pro", 37,  100,  0),
        ("Mahmoud Shbib",      "GK", "Al-Wehdat",       "Jordan Pro", 28,   20,  0),
        ("Ahmad Al-Rawabdeh",  "GK", "Al-Jazeera",      "Jordan Pro", 24,    8,  0),
        ("Yaseen Al-Bakhit",   "CB", "Al-Wehdat",       "Jordan Pro", 30,   60,  3),
        ("Baher Al-Said",      "RB", "Al-Faisaly",      "Jordan Pro", 28,   44,  2),
        ("Noor Alnuaimeh",     "LB", "Al-Wehdat",       "Jordan Pro", 26,   32,  1),
        ("Ahmad Saleh",        "CB", "Shabab Al-Ahli",  "UAE Pro",    29,   38,  1),
        ("Hamzeh Salah",       "CB", "Al-Faisaly",      "Jordan Pro", 27,   30,  0),
        ("Baha'a Faisal",      "CM", "Al-Wehdat",       "Jordan Pro", 30,   50,  4),
        ("Mousa Al-Tamari",    "RW", "Montpellier",     "Ligue 1",    27,   54, 12),
        ("Khaled Al-Hajj",     "CM", "Al-Faisaly",      "Jordan Pro", 28,   42,  3),
        ("Ahmad Ababneh",      "CM", "Al-Wehdat",       "Jordan Pro", 26,   28,  2),
        ("Yazan Al-Naimat",    "CM", "Al-Jazira",       "UAE Pro",    25,   22,  2),
        ("Mohammad Abu Zema",  "AM", "Al-Shorta",       "Iraq Stars", 26,   20,  4),
        ("Hamza Al Dardour",   "ST", "Al-Faisaly",      "Jordan Pro", 34,   80, 34),
        ("Musa Al Taamari",    "LW", "Al-Rayyan",       "QSL",        29,   50,  8),
        ("Baha'a Abdul-Rahman","CM", "Al-Faisaly",      "Jordan Pro", 29,   36,  3),
        ("Ali Olwan",          "ST", "Al-Wehdat",       "Jordan Pro", 27,   28,  8),
        ("Ahmad Rawashdeh",    "RW", "Al-Ahli Amman",   "Jordan Pro", 25,   18,  3),
        ("Mohammad Shbib",     "LB", "Al-Faisaly",      "Jordan Pro", 26,   20,  0),
        ("Wesam Abuali",       "CB", "Al-Wehdat",       "Jordan Pro", 27,   22,  1),
        ("Oday Dabbagh",       "ST", "Al-Faisaly",      "Jordan Pro", 26,   28, 10),
        ("Mohammad Qasem",     "CM", "Al-Jazeera",      "Jordan Pro", 24,   14,  0),
        ("Ibrahim Almadi",     "RW", "Los Angeles FC",  "MLS",        22,   12,  2),
        ("Zaid Krouma",        "LW", "Al-Wehdat",       "Jordan Pro", 24,   10,  2),
        ("Fadi Khaleel",       "GK", "Al-Ramtha",       "Jordan Pro", 26,    4,  0),
    ],
    "New Zealand": [
        ("Oliver Sail",        "GK", "FC Copenhagen",   "Superliga",  30,   38,  0),
        ("Stefan Marinovic",   "GK", "Vancouver W'caps","MLS",        33,   52,  0),
        ("Michael Woud",       "GK", "NEC Nijmegen",    "Eredivisie", 27,   12,  0),
        ("Winston Reid",       "CB", "Brentford",       "Premier",    36,   63,  3),
        ("Tommy Smith",        "CB", "Stoke City",      "Championship",33,  62,  4),
        ("Tim Payne",          "CB", "Waasland-Beveren","1. Division",26,   18,  0),
        ("Liberato Cacace",    "LB", "Southampton",     "Premier",    24,   34,  1),
        ("Callan Elliot",      "LB", "Wellington Ph.",  "A-League",   24,   16,  0),
        ("Kosta Barbarouses",  "LW", "Vancouver W'caps","MLS",        34,   76, 14),
        ("Sarpreet Singh",     "CM", "Hamburger SV",    "2. Bundesliga",25,  28,  3),
        ("Clayton Lewis",      "CM", "Melbourne City",  "A-League",   28,   40,  4),
        ("Gianni Stensness",   "CM", "St Gallen",       "Swiss SL",   25,   26,  2),
        ("Elijah Just",        "CM", "Rangers",         "SPL",        25,   24,  2),
        ("Ryan Thomas",        "CM", "Groningen",       "Eredivisie", 30,   52,  5),
        ("Marko Stamenic",     "CM", "FC Copenhagen",   "Superliga",  24,   26,  2),
        ("Myer Bevan",         "ST", "Esbjerg fB",      "1. Division",26,   28,  6),
        ("Matthew Ridenton",   "RW", "Wellington Ph.",  "A-League",   25,   22,  4),
        ("Alex Rufer",         "CM", "Wellington Ph.",  "A-League",   30,   54,  8),
        ("Chris Wood",         "ST", "Nottm Forest",    "Premier",    32,   80, 30),
        ("Hamish Watson",      "ST", "Botev Plovdiv",   "Bulgarian",  28,   22,  5),
        ("Deklan Wynne",       "RB", "Wellington Ph.",  "A-League",   26,   16,  0),
        ("Finn Surman",        "CM", "Norwich City",    "Championship",28,  12,  1),
        ("Callum McCowatt",    "RW", "Hvidovre IF",     "1. Division",25,   18,  3),
        ("Nando Pijnaker",     "CB", "Dunfermline",     "Championship",27,  16,  0),
        ("Zac McGraw",         "CB", "Portland Timbers","MLS",        24,   14,  0),
        ("Ben Old",            "LW", "Minnesota United","MLS",        22,   10,  2),
    ],
    "Norway": [
        ("Orjan Nyland",       "GK", "Atalanta",        "Serie A",    34,   42,  0),
        ("Ørjan Nyland",       "GK", "Atalanta",        "Serie A",    34,   42,  0),
        ("Matz Sels",          "GK", "Nottm Forest",    "Premier",    33,   30,  0),
        ("Arne Tandberg",      "GK", "Bodø/Glimt",      "Eliteserien",28,    8,  0),
        ("Andreas Hanche-Olsen","CB","Twente",          "Eredivisie", 27,   30,  1),
        ("Leo Skiri Østigård", "CB", "Napoli",          "Serie A",    25,   24,  0),
        ("Stian Gregersen",    "CB", "Augsburg",        "Bundesliga", 30,   20,  0),
        ("Birger Meling",      "LB", "Nantes",          "Ligue 1",    30,   28,  1),
        ("Marcus Pedersen",    "RB", "Stoke City",      "Championship",29,  34,  2),
        ("Stefan Strandberg",  "CB", "Rubin Kazan",     "RPL",        34,   38,  2),
        ("Sander Berge",       "CM", "Fulham",          "Premier",    27,   52,  4),
        ("Morten Thorsby",     "CM", "Genoa",           "Serie A",    29,   46,  5),
        ("Martin Ødegaard",    "AM", "Arsenal",         "Premier",    26,   80, 25),
        ("Kristian Thorstvedt","CM", "Sassuolo",        "Serie A",    25,   32,  5),
        ("Fredrik Aursnes",    "CM", "Benfica",         "Primeira",   28,   44,  3),
        ("Patrick Berg",       "CM", "Bodø/Glimt",      "Eliteserien",27,   28,  2),
        ("Erling Haaland",     "ST", "Manchester City", "Premier",    23,   45, 30),
        ("Alexander Sørloth",  "ST", "Atletico Madrid", "La Liga",    29,   64, 26),
        ("Jørgen Strand Larsen","ST","Celta Vigo",      "La Liga",    25,   26, 10),
        ("Josh King",          "LW", "Unattached",      "Free",       33,   99, 24),
        ("Mohamed Elyounoussi","LW", "Celtic",          "SPL",        30,   68, 16),
        ("Antonio Nusa",       "RW", "RB Leipzig",      "Bundesliga", 20,   16,  2),
        ("Ola Solbakken",      "RW", "Roma",            "Serie A",    25,   28,  5),
        ("Tobias Reine-Adelaide","AM","Atalanta",       "Serie A",    26,   10,  1),
        ("Ole Kristian Selnæs","CM", "Vejle BK",        "Superliga",  32,   30,  3),
        ("Halvard Norbye",     "LW", "Bodø/Glimt",      "Eliteserien",21,    8,  1),
    ],
    "Paraguay": [
        ("Antony Silva",       "GK", "Guaraní",         "División Pro",34,  80,  0),
        ("Alfredo Aguilar",    "GK", "Olimpia",         "División Pro",30,  20,  0),
        ("Roberto Fernández",  "GK", "Cerro Porteño",   "División Pro",28,   8,  0),
        ("Gustavo Gómez",      "CB", "Palmeiras",       "Brasileirao", 31,  70,  7),
        ("Fabián Balbuena",    "CB", "Nacional",        "Uruguay 1",   33,  70,  5),
        ("Omar Alderete",      "CB", "Valencia",        "La Liga",     27,  40,  2),
        ("Juan Escobar",       "RB", "Cruz Azul",       "Liga MX",     29,  48,  3),
        ("Santiago Arzamendia","LB", "Cadiz",           "La Liga",     26,  30,  2),
        ("Mathías Villasanti", "CM", "Grêmio",          "Brasileirao", 27,  34,  3),
        ("Andrés Cubas",       "CM", "Rennes",          "Ligue 1",     27,  38,  2),
        ("Richard Sánchez",    "CM", "América",         "Liga MX",     29,  54,  6),
        ("Miguel Almirón",     "AM", "Newcastle Utd",   "Premier",     30,  82, 14),
        ("Ángel Romero",       "RW", "Cruz Azul",       "Liga MX",     32,  72, 26),
        ("Jorge Benítez",      "RW", "Olimpia",         "División Pro",28,  36,  8),
        ("Gustavo Velázquez",  "LW", "Betis",           "La Liga",     22,  18,  2),
        ("Antonio Sanabria",   "ST", "Torino",          "Serie A",     29,  54, 20),
        ("Óscar Romero",       "AM", "Boca Juniors",    "Liga Pro Arg",32,  56, 12),
        ("Derlis González",    "RW", "Unattached",      "Free",        31,  64, 18),
        ("Adrián Martínez",    "ST", "Sassuolo",        "Serie A",     25,  22,  8),
        ("Alex Arce",          "ST", "LDU Quito",       "LigaPro",     28,  32, 10),
        ("Braian Samudio",     "LW", "São Paulo FC",    "Brasileirao", 26,  16,  3),
        ("Julio Enciso",       "AM", "Brighton",        "Premier",     21,  24,  5),
        ("Celso Ortiz",        "CM", "Monterrey",       "Liga MX",     32,  48,  2),
        ("Jorge Morel",        "RB", "Talleres",        "Liga Pro Arg",27,  18,  0),
        ("Claudio Aquino",     "AM", "Independiente",   "Liga Pro Arg",31,  28,  5),
        ("Fernando Cardozo",   "ST", "Olimpia",         "División Pro",27,  16,  4),
    ],
    "Qatar": [
        ("Meshaal Barsham",    "GK", "Al-Sadd",         "QSL",        25,   52,  0),
        ("Saad Al-Sheeb",      "GK", "Al-Sadd",         "QSL",        34,   80,  0),
        ("Yousef Hassan",      "GK", "Al-Gharafa",      "QSL",        24,    8,  0),
        ("Tarek Salman",       "CB", "Al-Duhail",       "QSL",        27,   38,  1),
        ("Pedro Miguel",       "LB", "Al-Sadd",         "QSL",        32,   60,  3),
        ("Bassam Al-Rawi",     "CB", "Al-Sadd",         "QSL",        29,   42,  2),
        ("Abdelkarim Hassan",  "LB", "Al-Sadd",         "QSL",        28,   60,  4),
        ("Salem Al-Hajri",     "RB", "Al-Wakrah",       "QSL",        26,   28,  0),
        ("Jassim Gaber",       "CB", "Al-Duhail",       "QSL",        28,   32,  2),
        ("Karim Boudiaf",      "CM", "Al-Duhail",       "QSL",        30,   56,  4),
        ("Abdulaziz Hatem",    "CM", "Al-Rayyan",       "QSL",        32,   72,  6),
        ("Assim Madibo",       "CM", "Philadelphia Un.","MLS",        27,   36,  2),
        ("Salem Al-Hajri (AM)","AM", "Al-Wakrah",       "QSL",        24,   16,  2),
        ("Hassan Al-Haydos",   "RW", "Al-Sadd",         "QSL",        33,  157, 23),
        ("Akram Afif",         "LW", "Al-Sadd",         "QSL",        28,   70, 24),
        ("Almoez Ali",         "ST", "Al-Duhail",       "QSL",        28,   92, 46),
        ("Ahmed Alaaeldin",    "AM", "Al-Rayyan",       "QSL",        26,   34,  8),
        ("Mohammed Muntari",   "ST", "Al-Duhail",       "QSL",        28,   40, 16),
        ("Mustafa Mashaal",    "AM", "Al-Sailiya",      "QSL",        28,   34,  5),
        ("Ismaeel Mohammad",   "RW", "Al-Gharafa",      "QSL",        26,   22,  4),
        ("Boualem Khoukhi",    "CM", "Al-Sadd",         "QSL",        35,   70,  2),
        ("Ahmad Moein",        "CM", "Al-Khor",         "QSL",        24,   16,  1),
        ("Omar Al-Somah",      "ST", "Al-Ahly Jeddah",  "Saudi Pro",  36,   10,  4),
        ("Khalid Muneer",      "RB", "Al-Shamal",       "QSL",        25,   12,  0),
        ("Yusuf Abdurisag",    "LW", "Al-Gharafa",      "QSL",        22,   10,  3),
        ("Naif Al-Hadhrami",   "CM", "Al-Duhail",       "QSL",        25,   18,  1),
    ],
    "Saudi Arabia": [
        ("Mohammed Al-Owais",  "GK", "Al-Hilal",        "Saudi Pro",  33,   68,  0),
        ("Fawaz Al-Qarni",     "GK", "Al-Faisaly",      "Saudi Pro",  28,   18,  0),
        ("Yasser Al-Mosailem", "GK", "Al-Ittihad",      "Saudi Pro",  32,   30,  0),
        ("Ali Al-Bulayhi",     "LB", "Al-Hilal",        "Saudi Pro",  34,   86,  2),
        ("Sultan Al-Ghannam",  "CB", "Al-Hilal",        "Saudi Pro",  28,   30,  0),
        ("Hassan Tambakti",    "CB", "Al-Hilal",        "Saudi Pro",  25,   28,  1),
        ("Saud Abdulhamid",    "RB", "Roma",            "Serie A",    25,   28,  1),
        ("Mohamed Kanno",      "CM", "Al-Hilal",        "Saudi Pro",  29,   52,  3),
        ("Salman Al-Faraj",    "CM", "Al-Hilal",        "Saudi Pro",  33,  100,  6),
        ("Ali Al-Hassan",      "CM", "Al-Qadsiah",      "Saudi Pro",  25,   22,  1),
        ("Abdulelah Al-Malki", "CM", "Al-Shabab",       "Saudi Pro",  24,   18,  0),
        ("Salem Al-Dawsari",   "LW", "Al-Hilal",        "Saudi Pro",  32,   82, 22),
        ("Fahad Al-Muwallad",  "LW", "Al-Ittihad",      "Saudi Pro",  31,   72, 16),
        ("Mohammed Al-Burayk", "LB", "Al-Hilal",        "Saudi Pro",  28,   40,  2),
        ("Firas Al-Buraikan",  "ST", "Al-Fateh",        "Saudi Pro",  26,   40, 14),
        ("Haitham Asiri",      "RW", "Al-Hilal",        "Saudi Pro",  26,   24,  4),
        ("Ali Al-Nemer",       "ST", "Al-Ittihad",      "Saudi Pro",  27,   22,  6),
        ("Saleh Al-Shehri",    "ST", "Al-Hilal",        "Saudi Pro",  30,   44, 10),
        ("Nasser Al-Dawsari",  "AM", "Al-Hilal",        "Saudi Pro",  30,   36,  5),
        ("Abdullah Al-Khaibari","CM","Al-Nassr",        "Saudi Pro",  26,   20,  1),
        ("Riyadh Sharahili",   "CB", "Al-Ahli",         "Saudi Pro",  28,   26,  1),
        ("Nawaf Yahya",        "CM", "Unattached",      "Free",       23,   14,  0),
        ("Nasser Al-Ghanam",   "RB", "Al-Hilal",        "Saudi Pro",  27,   18,  0),
        ("Abdullah Radif",     "ST", "Al-Nassr",        "Saudi Pro",  26,   16,  4),
        ("Ali Hassan Yousuf",  "AM", "Al-Wehda",        "Saudi Pro",  27,   20,  3),
        ("Musab Al-Juwayr",    "LW", "Al-Nassr",        "Saudi Pro",  26,   18,  5),
    ],
    "Scotland": [
        ("Angus Gunn",         "GK", "Norwich City",    "Championship",28,  24,  0),
        ("Craig Gordon",       "GK", "Hearts",          "SPL",        41,   77,  0),
        ("Liam Kelly",         "GK", "Motherwell",      "SPL",        30,   10,  0),
        ("Grant Hanley",       "CB", "Norwich City",    "Championship",33,  58,  2),
        ("Scott McKenna",      "CB", "Nottm Forest",    "Premier",    28,   46,  4),
        ("Jack Hendry",        "CB", "Club Brugge",     "Pro League", 29,   34,  3),
        ("Andrew Robertson",   "LB", "Liverpool",       "Premier",    30,   78,  3),
        ("Aaron Hickey",       "RB", "Brentford",       "Premier",    22,   22,  2),
        ("Liam Cooper",        "CB", "Leeds Utd",       "Championship",33,  24,  0),
        ("John McGinn",        "CM", "Aston Villa",     "Premier",    30,   79, 15),
        ("Callum McGregor",    "CM", "Celtic",          "SPL",        30,   54,  4),
        ("Stuart Armstrong",   "CM", "Southampton",     "Championship",32,  52,  9),
        ("Billy Gilmour",      "CM", "Brighton",        "Premier",    23,   28,  2),
        ("Ryan Christie",      "AM", "Bournemouth",     "Premier",    29,   40,  8),
        ("Kenny McLean",       "CM", "Norwich City",    "Championship",32,  46,  8),
        ("Che Adams",          "ST", "Southampton",     "Championship",28,  40, 12),
        ("Lyndon Dykes",       "ST", "Millwall",        "Championship",29,  40, 13),
        ("Kevin Nisbet",       "ST", "Millwall",        "Championship",27,  24,  6),
        ("Scott McTominay",    "CM", "Manchester Utd",  "Premier",    27,   56, 15),
        ("Ryan Fraser",        "RW", "Southampton",     "Championship",30,  33,  5),
        ("Kieran Tierney",     "LB", "Real Sociedad",   "La Liga",    27,   53,  2),
        ("Lewis Ferguson",     "CM", "Bologna",         "Serie A",    25,   28,  4),
        ("Ben Doak",           "RW", "Liverpool",       "Premier",    19,    8,  0),
        ("Robbie Neilson",     "RB", "Hearts",          "SPL",        23,    4,  0),
        ("Ché Adams",          "ST", "Southampton",     "Championship",29,  36, 11),
        ("Lawrence Shankland", "ST", "Hearts",          "SPL",        29,   24, 12),
    ],
    "Sweden": [
        ("Robin Olsen",        "GK", "Aston Villa",     "Premier",    34,   60,  0),
        ("Kristoffer Nordfeldt","GK","Beşiktaş",        "Süper Lig",  35,   12,  0),
        ("Karl-Johan Johnsson","GK","Guingamp",         "Ligue 2 FR", 32,   24,  0),
        ("Victor Lindelöf",    "CB", "Manchester Utd",  "Premier",    30,   70,  4),
        ("Marcus Danielson",   "CB", "Djurgårdens IF",  "Allsvenskan",33,   34,  2),
        ("Filip Helander",     "CB", "Rangers",         "SPL",        32,   32,  2),
        ("Ludwig Augustinsson","LB", "Unattached",      "Free",       30,   56,  5),
        ("Mikael Lustig",      "RB", "AIK",             "Allsvenskan",37,   87,  9),
        ("Emil Krafth",        "RB", "Newcastle Utd",   "Premier",    30,   32,  1),
        ("Albin Ekdal",        "CM", "Sampdoria",       "Serie B",    34,   84,  5),
        ("Kristoffer Olsson",  "CM", "Midtjylland",     "Superliga",  29,   52,  4),
        ("Karl Gustafsson",    "CM", "Servette",        "Swiss SL",   27,   22,  1),
        ("Mattias Svanberg",   "CM", "Wolfsburg",       "Bundesliga", 25,   36,  3),
        ("Emil Forsberg",      "AM", "RB Leipzig",      "Bundesliga", 32,   88, 28),
        ("Dejan Kulusevski",   "AM", "Tottenham",       "Premier",    25,   42, 11),
        ("Sebastian Larsson",  "CM", "IFK Göteborg",    "Allsvenskan",38,  133,  8),
        ("Alexander Isak",     "ST", "Newcastle Utd",   "Premier",    25,   44, 17),
        ("Viktor Gyökeres",    "ST", "Sporting CP",     "Primeira",   26,   30, 14),
        ("Marcus Berg",        "ST", "Al-Shamal",       "QSL",        37,   78, 26),
        ("Robin Quaison",      "ST", "Mainz 05",        "Bundesliga", 31,   46, 10),
        ("Samuel Gustafson",   "CM", "Torino",          "Serie A",    31,   28,  2),
        ("Anthony Elanga",     "RW", "Nottm Forest",    "Premier",    22,   18,  3),
        ("Isak Bergmann Johannesson","CM","RB Leipzig",  "Bundesliga", 21,   16,  1),
        ("Jens-Lys Cajuste",   "CM", "Napoli",          "Serie A",    24,   18,  0),
        ("Joel Andersson",     "RB", "Malmö FF",        "Allsvenskan",27,   10,  0),
        ("Oscar Lewicki",      "CM", "Malmö FF",        "Allsvenskan",32,   24,  2),
    ],
    "Tunisia": [
        ("Aymen Dahmen",       "GK", "Montpellier",     "Ligue 1",    27,   28,  0),
        ("Mouez Hassen",       "GK", "Niort",           "Ligue 2 FR", 29,   26,  0),
        ("Bechir Ben Said",    "GK", "Espérance Tunis", "Ligue 1 TUN",27,   12,  0),
        ("Ali Maaloul",        "LB", "Al Ahly",         "Egypt Prem", 33,   92,  8),
        ("Montassar Talbi",    "CB", "Lorient",         "Ligue 1",    27,   28,  0),
        ("Yassine Meriah",     "CB", "Nottm Forest",    "Premier",    29,   44,  2),
        ("Dylan Bronn",        "CB", "Salernitana",     "Serie A",    28,   32,  2),
        ("Mohamed Drager",     "RB", "Middlesbrough",   "Championship",27,  44,  2),
        ("Wajdi Kechrida",     "RB", "Trabzonspor",     "Süper Lig",  29,   38,  2),
        ("Ferjani Sassi",      "CM", "Al-Duhail",       "QSL",        31,   92,  8),
        ("Aissa Laidouni",     "CM", "Ferencvaros",     "OTP Bank",   28,   34,  3),
        ("Hannibal Mejbri",    "CM", "Birmingham",      "Championship",21,  22,  2),
        ("Mohamed Ali Ben Romdhane","CM","Sharjah FC",  "UAE Pro",    26,   30,  4),
        ("Ellyes Skhiri",      "CM", "Eintracht Frankfurt","Bundesliga",29, 58,  8),
        ("Saif Ghezal",        "RW", "Al-Gharafa",      "QSL",        29,   44,  6),
        ("Naim Sliti",         "LW", "Dijon",           "Ligue 2 FR", 31,   68, 12),
        ("Wahbi Khazri",       "AM", "Unattached",      "Free",       33,   88, 25),
        ("Youssef Msakni",     "AM", "Al-Rayyan",       "QSL",        34,  104, 20),
        ("Seifeddine Jaziri",  "ST", "Angers",          "Ligue 2 FR", 30,   38, 10),
        ("Issam Jebali",       "ST", "Odense BK",       "Superliga",  30,   42, 12),
        ("Mohamed Taha Yassine Khenissi","ST","Al-Faisaly","Jordan Pro",32, 44, 14),
        ("Ghaylane Chaaleli",  "RW", "Le Havre",        "Ligue 1",    25,   22,  3),
        ("Adam Jelassi",       "RB", "Standard Liège",  "Pro League", 24,   14,  0),
        ("Bilal Iqbal",        "LW", "Al-Jazira",       "UAE Pro",    23,   10,  1),
        ("Mortadha Ben Ouanes","ST", "Al-Quwa Al-Jawiya","Iraq Stars", 27,  16,  4),
        ("Hichem Cherni",      "CB", "Espérance Tunis", "Ligue 1 TUN",28,  18,  0),
    ],
    "Uzbekistan": [
        ("Otabek Shukurov",    "GK", "Pakhtakor",       "UPL",        30,   50,  0),
        ("Eldor Shomurodov (GK)","GK","Qizilqum",       "UPL",        26,    8,  0),
        ("Timur Suzmatov",     "GK", "Lokomotiv Tash.","UPL",        28,   14,  0),
        ("Sanjar Tursunov",    "CB", "Pakhtakor",       "UPL",        29,   38,  2),
        ("Dostonbek Khamdamov","CB","Pakhtakor",        "UPL",        26,   28,  1),
        ("Azizbek Turgunboev", "RB", "FK Krasnodar",    "RPL",        25,   22,  1),
        ("Eldor Shomurodov",   "ST", "Cagliari",        "Serie A",    28,   72, 34),
        ("Otabek Shatunov",    "CM", "Pakhtakor",       "UPL",        27,   30,  3),
        ("Islombek Kholdorov", "CM", "FK Krasnodar",    "RPL",        24,   20,  1),
        ("Jasurbek Yakhshiboev","LB","Pakhtakor",       "UPL",        28,   30,  2),
        ("Mukhammadali Alijonov","RW","Anzhi",          "RPL",        26,   24,  4),
        ("Abbosbek Fayzullayev","LW","PAOK",            "Super League",25,  38, 10),
        ("Husayn Norchaev",    "CM", "Pakhtakor",       "UPL",        27,   26,  2),
        ("Abdurauf Khashimov", "AM", "FK Neftchi",      "UPL",        26,   22,  4),
        ("Akbar Abduraupov",   "CM", "FK Shakhtyor",    "Belarusian", 25,   18,  2),
        ("Shamsiddin Kholmatov","RW","Pakhtakor",       "UPL",        24,   16,  2),
        ("Ilyos Zeytullaev",   "LW", "Pakhtakor",       "UPL",        25,   20,  4),
        ("Dostonbek Khashimov","ST", "Pakhtakor",       "UPL",        23,   14,  3),
        ("Farrukhbek Mamatov", "CB", "Pakhtakor",       "UPL",        28,   22,  0),
        ("Jakhongir Sidikov",  "RB", "Pakhtakor",       "UPL",        26,   18,  0),
        ("Murodjon Ahmadaliev","AM", "CSKA Sofiya",     "First League",27,  28,  6),
        ("Nodir Alijonov",     "CM", "FK Bunyodkor",    "UPL",        25,   20,  2),
        ("Jahongir Urinboev",  "LB", "Nasaf Karshi",    "UPL",        27,   16,  1),
        ("Bahodir Jalolov",    "ST", "Qarabag",         "Azerbaijan", 25,   22,  8),
        ("Ulugbek Asrorov",    "GK", "Spartak Moscow",  "RPL",        23,   12,  0),
        ("Ozodjon Turdiev",    "RW", "Pakhtakor",       "UPL",        23,   10,  2),
    ],
    "South Africa": [
        ("Ronwen Williams",    "GK", "Mamelodi Sundowns","PSL",       32,   56,  0),
        ("Veli Mothwa",        "GK", "AmaZulu FC",      "PSL",        32,   24,  0),
        ("Shu-Aib Walters",    "GK", "Kaizer Chiefs",   "PSL",        27,    8,  0),
        ("Thulani Hlatshwayo", "CB", "Mamelodi Sundowns","PSL",       35,   76,  6),
        ("Rushine de Reuck",   "CB", "Mamelodi Sundowns","PSL",       29,   28,  2),
        ("Bongani Zungu",      "CM", "Amiens SC",       "Ligue 2 FR", 31,   56,  2),
        ("Siyanda Xulu",       "CB", "SuperSport Utd",  "PSL",        31,   36,  1),
        ("Reeve Frosler",      "RB", "Kaizer Chiefs",   "PSL",        27,   34,  2),
        ("Terrence Mashego",   "LB", "Mamelodi Sundowns","PSL",       28,   24,  0),
        ("Hlompho Kekana",     "CM", "Mamelodi Sundowns","PSL",       37,   44,  3),
        ("Thabo Cele",         "CM", "SuperSport Utd",  "PSL",        27,   22,  1),
        ("Mothobi Mvala",      "CM", "Mamelodi Sundowns","PSL",       29,   32,  2),
        ("Teboho Mokoena",     "CM", "SuperSport Utd",  "PSL",        27,   38,  5),
        ("Themba Zwane",       "AM", "Mamelodi Sundowns","PSL",       33,   60, 10),
        ("Lyle Foster",        "ST", "Burnley",         "Championship",24,  24,  6),
        ("Evidence Makgopa",   "ST", "Al Qadsiah",      "Saudi Pro",  25,   20,  6),
        ("Percy Tau",          "LW", "Al Ahly",         "Egypt Prem", 30,   68, 15),
        ("Bafana Mthembu",     "RW", "Wydad Casablanca","BOTOLA",     25,   14,  2),
        ("Kermit Erasmus",     "ST", "Orlando Pirates", "PSL",        35,   64, 14),
        ("Lebo Mothiba",       "ST", "Strasbourg",      "Ligue 1",    28,   24,  8),
        ("Ethan Brooks",       "LB", "Mamelodi Sundowns","PSL",       23,   10,  0),
        ("Grant Kekana",       "CB", "Mamelodi Sundowns","PSL",       27,   16,  0),
        ("Gaston Sirino",      "AM", "Mamelodi Sundowns","PSL",       33,   28,  6),
        ("Keagan Dolly",       "RW", "Kaizer Chiefs",   "PSL",        30,   42,  8),
        ("Sibongiseni Mthethwa","CM","AmaZulu FC",       "PSL",       27,   18,  1),
        ("Thapelo Morena",     "RB", "Mamelodi Sundowns","PSL",       31,   40,  3),
    ],
}


POS_MAP = {
    "GK": "GK",
    "CB": "DEF", "LB": "DEF", "RB": "DEF",
    "CM": "MID", "AM": "MID", "DM": "MID",
    "LW": "FWD", "RW": "FWD", "ST": "FWD", "CF": "FWD",
    # passthrough for already-mapped values
    "DEF": "DEF", "MID": "MID", "FWD": "FWD",
}


def run():
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    total_added = 0
    for team_name, squad in SQUADS.items():
        row = cur.execute("SELECT id FROM teams WHERE name=?", (team_name,)).fetchone()
        if not row:
            print(f"  ⚠️  Team not found: {team_name}")
            continue
        team_id = row["id"]

        existing_names = {r["name"] for r in cur.execute(
            "SELECT name FROM players WHERE team_id=?", (team_id,)).fetchall()}

        added = 0
        for name, raw_pos, club, league, age, caps, goals in squad:
            if name in existing_names:
                continue
            position = POS_MAP.get(raw_pos, "MID")
            cur.execute("""
                INSERT OR IGNORE INTO players
                    (name, team_id, position, club, club_league, age, caps, goals_as_nat)
                VALUES (?,?,?,?,?,?,?,?)
            """, (name, team_id, position, club, league, age, caps, goals))
            p = cur.execute(
                "SELECT id FROM players WHERE name=? AND team_id=?", (name, team_id)
            ).fetchone()
            if p:
                cur.execute("""
                    INSERT OR IGNORE INTO squad_selections (team_id, player_id, confirmed)
                    VALUES (?,?,1)
                """, (team_id, p["id"]))
                added += 1

        conn.commit()
        total_added += added
        total_now = cur.execute(
            "SELECT COUNT(*) FROM players WHERE team_id=?", (team_id,)
        ).fetchone()[0]
        print(f"  {team_name:<35} +{added} → {total_now} total")

    total_db = cur.execute("SELECT COUNT(*) FROM players").fetchone()[0]
    print(f"\nTotal added: {total_added} | DB players: {total_db}")
    conn.close()


if __name__ == "__main__":
    run()
